### ISSUE TITLE
incorrect cast tracking

### ISSUE THREAD

**Issue by NotAdam** [Soreepeong/XivAlexander#1]
you don't correctly correlate casts with their subsequent effects, there's a field for this

effect: https://github.com/SapphireServer/Sapphire/blob/develop/src/common/Network/PacketDef/Zone/ServerZoneDef.h#L557-L563

cast: https://github.com/SapphireServer/Sapphire/blob/develop/src/common/Network/PacketDef/Zone/ClientZoneDef.h#L79

the same id can be found when cancelling a cast

**Comment by Soreepeong** [comment]
I'll check it out and add assertions for now; by any chance do you know whether action requests and responses got correlation ID too?

**Comment by Soreepeong** [comment]
This has been addressed in commit 70b4b1a62495fc0fede9dfc5bd17bdb60792808e. It seems that only ActionRequest and ActionEffect contain sequence number information, so other messages are processed just like before.
