### ISSUE TITLE
Removing Early Penalty

### ISSUE THREAD

**Issue by oiSlayer** [Soreepeong/XivAlexander#100]
Hey is there a way to remove the early penalty, or do I have to resort to using older version or editing the code? Sometimes it's hard to triple weave, and sometimes late double weaving because the early penalty sometimes goes up to 100ms. 

Also, is there a discord for this program?

**Comment by Soreepeong** [comment]
While triple weaving definitely is more than possible, at times it just won't work even on very low ping (<10ms). For double weaving, you might be experiencing this: https://github.com/Soreepeong/XivAlexander/pull/23#issue-582128977
You might want to try turning off `Use Delay Detection`, and see if you prefer that mode.

Also, no, I don't think discord for this is necessary.
