### ISSUE TITLE
Ping failure fills log while using VPN

### ISSUE THREAD

**Issue by BbHQZzS** [Soreepeong/XivAlexander#101]
Hello. I use WTFast VPN. The ping fails every second. Is there a way to disable this? Also see in the log the pingLatency is 0ms. I'm not sure if I have the correct settings if VPN is in use. Thank you. 

Log: https://gist.github.com/BbHQZzS/19a53d2ecb0f594637950f6674205965 

Runtime config:
```json
{
	"AlwaysOnTop": false,
	"ReducePacketDelay": true,
	"ShowControlWindow": false,
	"ShowLoggingWindow": true,
	"TakeOverAllAddresses": false,
	"TakeOverAllPorts": false,
	"TakeOverLoopback": false,
	"TakeOverPrivateAddresses": false,
	"UseAllIpcMessageLogger": false,
	"UseAutoAdjustingExtraDelay": false,
	"UseEffectApplicationDelayLogger": false,
	"UseHighLatencyMitigation": true,
	"UseHighLatencyMitigationLogging": true,
	"UseLatencyCorrection": false,
	"UseOpcodeFinder": false
}
```

**Comment by Soreepeong** [comment]
I've changed the program to stop trying after 10 consecutive failures, and no log will be printed about each attempt - only whether it started or stopped will be printed.
