### ISSUE TITLE
Is there a way to skip the initial injection prompt?

### ISSUE THREAD

**Issue by Axiphel** [Soreepeong/XivAlexander#102]
Sorry if this is dumb, but I didn't see anything in the config that indicated a way to inject without confirmation. Is there a way to do that?

**Comment by Soreepeong** [comment]
Try making a shortcut, and giving `-a load` as parameters.

1. Copy `XivAlexanderLoader32/64.exe`, right click on window background, and `Paste shortcut`.
2. Right click on newly created shortcut, select `Properties`, and append ` -a load` to `Target`.

**Comment by Axiphel** [comment]
Thanks! I saw the command line arguments and figured the solution was there, but wasn't sure where to put them (even though I've done that before with shortcuts).
