### ISSUE TITLE
Failed to Verify

### ISSUE THREAD

**Issue by moonlitglare** [Soreepeong/XivAlexander#103]
I'm getting this error and I don't know why.
![image](https://user-images.githubusercontent.com/20742787/125143258-1f792680-e0e8-11eb-9dd9-f03011565682.png)

**Comment by Axiphel** [comment]
You either do not have all the files placed into the folder or your antivirus is blocking the injection. Add an exclusion for the folder you have xivalexander in.

**Comment by moonlitglare** [comment]
That was it. For some reason, Windows Defender lost my settings when I had added the \game\ folder to the exclusions. Thanks Microsoft.
