### ISSUE TITLE
Virus threat detection

### ISSUE THREAD

**Issue by Toothpick** [Soreepeong/XivAlexander#104]
I keep getting this :
Threat severe:

Program:Win32/Wacapew.C!ml

Affected items:
file: C:\Users\User\Downloads\XivAlexander_1_14_8_2\XivAlexanderLoader32.exe

Upon searching for this in google it says this specific malware/trojan is known and designed to hack into the computer and gain access into information.

As well as : Trojan:Win32/Glupteba!ml

containerfile: C:\Users\User\Downloads\XivAlexander_1_14_8_5.zip

Whats the purpose of these files and why are they included? And are they safe to have in my PC from this release?

**Comment by Soreepeong** [comment]
This program employs the techniques that literally can also often be found in malwares. I am not going to bother to "prove" that this program is safe - just note that PDB file can be used to debug the compiled program, which should mean that the file is not infected by external virus.

**Comment by Toothpick** [comment]
I should have said that my expertise in coding are almost nonexistent. 
But I am aware that it does employ such techniques, which is why I said if its safe in this specific release/program : ) 

I just wanted a clarification or a reassurance, since I was worried why my anti-malware started giving me these weird notifications all of a sudden.

That said, I have been using this for a couple of months and it has been amazing, and I do appreciate your work immensely.  

Thanks for the clarification.
