### ISSUE TITLE
Lost connect when using longtime

### ISSUE THREAD

**Issue by SchwartzLizer** [Soreepeong/XivAlexander#105]
Hi I have problem when I using long time it will be show red poke ball but didn't disconnect from server and I use some skill Peloton effect skill will be apply too slow after use around 10 sec and if someone res me if after I accept it will be delay about 10 sec too this is bug or normally? but skill DPS is look like normally I'm not sure about this

**Comment by Soreepeong** [comment]
Are you using a VPN program?

**Comment by SchwartzLizer** [comment]
Yes i using NoPing
