### ISSUE TITLE
Question about S2C_ActorControlSelf 

### ISSUE THREAD

**Issue by itsKrepz** [Soreepeong/XivAlexander#106]
I'm not a native English speaker so I have some issue on this:
"S2C_ActorControlSelf
Use any action with cooldown, and possibly make it to rollback.
Spamming NIN Ten(4975) is the best way to cause the game to rollback the action."

I'm not sure what is a "rollback" and what is "NIN Ten", so I don't know which ability to use in order for me to find my S2C_ActorControlSelf value, could anyone explain it a little bit more? Or just show me an ability icon that I should use for this.

**Comment by Soreepeong** [comment]
Use **Ten**-Chi-Jin(**天**地人) in succession until this happens. You'll see that a Mudra action is cancelled.

https://user-images.githubusercontent.com/3614868/125471742-998f3c89-6cc4-4730-adb1-08215a32b2f1.mp4
