### ISSUE TITLE
Question on opcodes and configurations

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#107]
Hello, thank you for the great software.

I was wondering if it would be possible to further enhance the performance by changing the configuration/opcode values different from the default settings? I play in an extremely high ping :(

Also, if my ping fluctuates between 190ms ~ 200ms, would you recommend turning delay detection, latency correction off?

Thank you

**Comment by justin767** [comment]
anyone please help me :(

**Comment by Soreepeong** [comment]
1. No, opcodes are there to make the program work; if you change it and it doesn't fit the current game version, this program simply will not work.
2. I personally play having those options turned off. If your ping is around that, yes, I would recommend having those options turned off too, as for some reason game server's responses would be twice later than your ping, from my experience.

**Comment by justin767** [comment]
> 1. No, opcodes are there to make the program work; if you change it and it doesn't fit the current game version, this program simply will not work.
> 2. I personally play having those options turned off. If your ping is around that, yes, I would recommend having those options turned off too, as for some reason game server's responses would be twice later than your ping, from my experience.

Thank you so much for the detailed reply!!
