### ISSUE TITLE
Sub 600ms weaves with high ping plus some doubts

### ISSUE THREAD

**Issue by arguare** [Soreepeong/XivAlexander#109]
Been using XivAlexander for a little over a week as a DRG with a ping of 250ms no VPN with Delay Detection and Latency Correction turned off and after checking my logs I'm seeing a lot of sub 600 ms weaves (specially 535ms or so ones) https://i.imgur.com/ZeGGKe9.png

I barely know anything about software but with my settings shouldn't my lower weaves be around 675ms? I'm kinda worried about getting banned if SE somehow detects it (no idea if they even have the systems for it tho) or if someone checks my legs and reports me thinking I'm cheating.

On a smaller note, I don't know if it affects something but everytime I boot Alexander I get this error https://i.imgur.com/tqX05hK.png - Also, after comparing logs with a friend I realized my logs don't show LatencyEstimate, just SocketLatency (don't have an ss right now because servers are down, can get one later) and was wondering if that could be an issue.

**Comment by Soreepeong** [comment]
For first one, I need logs from XivAlex too. Use "Save" from Log window, but delete your IP address.

Do you know how much the ping fluctuates to the server? Try the following, and tell me the minimum and maximum values printed.
* Open Command Prompt (Windows+R -> `cmd` -> Enter/OK)
* Ping servers
  * `ping -t neolobby01.ffxiv.com` for JP servers
  * `ping -t neolobby06.ffxiv.com` for EU servers
  * `ping -t neolobby08.ffxiv.com` for NA servers
* After sufficient number of pings happened, press `Ctrl+C`.
* Tell me the statistics line printed.

When I try to play on 280ms connection to Chaos, the server's response time would fluctuate quite a lot despite jitter from ping command would stay low. Also, if the server takes more than 500ms to response, the game client will release the lock, so this should be happening even without XivAlex, if you're playing on that high ping, playing at around 30 FPS, and you can use action right after Jump/Dive(except Mirage) while you're being jumped.

For the second one, try clearing the log and "Network > Release All Connections", and see if it shows up again.

**Comment by arguare** [comment]
Here's the log (did the opener from the xivlogs SS, can provide more if needed): [xivA.log](https://github.com/Soreepeong/XivAlexander/files/6849934/xivA.log)

> For 0.535 ones, seeing that those are consistent, I would guess that it happens with XivAlex too?

It only happens when I'm using XivAlexander.

Ping to JP servers: https://puu.sh/HXMr1/700f9e0fcb.png
Ping to EU servers: https://puu.sh/HXMs5/a1de2c954a.png
Ping to NA servers: https://puu.sh/HXMt3/e503ab81ed.png
Forgot to mention, I play only on NA servers so it would be 250ms, but on bad days it can spike up to 300ms.

> For the second one, try clearing the log and "Network > Release All Connections", and see if it shows up again.

Tried doing that and it still shows.

**Comment by Soreepeong** [comment]
From the log and pings I see, your ping is too high for the program to work correctly. When I tried playing on ping that high, without xivalex, the game did let me use next action 500ms after last action, so it's working as intended, and xivalex is actually penalizing the user, whereas the game by default will ignore the animation lock of the second last action.

![image](https://user-images.githubusercontent.com/3614868/126371362-44fd115a-1457-48fd-b5dc-fb9d629297b2.png)

**Comment by arguare** [comment]
Then if I understood correctly and dont want to risk a report/ban, I should stop using XivAlex right? At least until I am able to play with lower ping (like with a VPN).

**Comment by arennf57** [comment]
Correct me if I'm wrong but the game has a 500ms animation lock, and you're weaving with 535ms, so it would appear to sqex you have a ping of 35ms

**Comment by arguare** [comment]
The way I understand it is that when your ping is high enough that it takes more than 500ms for your client to receive the 500ms animation lock order, the client just skips it letting you do 535ms weaves which is what happens in my case, correct me if I'm wrong please. Now, back when I didn't use XivAlex I would get 535ms weaves every now and then but seems that XivAlex makes them a long more frequent and consistent and that's what worries me.

Also, after checking JP players logs (which usually they have the lowest ping) I found that their weaves are between 650ms to 700ms, nowhere close to 535ms.
