### ISSUE TITLE
new patch opcodes

### ISSUE THREAD

**Issue by DemolitionMoon** [Soreepeong/XivAlexander#110]
new patch opcodes

    "C2S_ActionRequest": "0x0175",
    "C2S_ActionRequestGroundTargeted": "0x021d",
    "S2C_ActionEffect01": "0x0102",
    "S2C_ActionEffect08": "0x0345",
    "S2C_ActionEffect16": "0x02b6",
    "S2C_ActionEffect24": "0x0298",
    "S2C_ActionEffect32": "0x03a4",
    "S2C_ActorCast": "0x02a7",
    "S2C_ActorControl": "0x0264",
    "S2C_ActorControlSelf": "0x0314",
    "S2C_AddStatusEffect": "0x0151",

**Comment by WeegeeVenom** [comment]
Can anyone confirm if this works? I am currently occupied so I can’t personally.

**Comment by Evangel0201** [comment]
can confirm that it works

**Comment by WeegeeVenom** [comment]
Thank you! Will be gladly using this once I’m back on

**Comment by steponmepls** [comment]
Are you supposed to also fill this part of the config or will default values do for now?
```
"Server_IpRange": "0.0.0.0/0",
"Server_PortRange": "1-65535"
```

**Comment by DemolitionMoon** [comment]
i left mine like that, apparently some have that in their config and some people dont
so i just left it out of my opcodes post

**Comment by Soreepeong** [comment]
I tested it and it works, and it's applied to the new release. Thank you.
