### ISSUE TITLE
Latest release is causing malwarebytes and windows to cite Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by FloppyAl** [Soreepeong/XivAlexander#111]
I'm guessing it's a false positive but it's perplexing why this release out of all them seems to be throwing out this trojan warning? 

Here's the virustotal link:

https://www.virustotal.com/gui/file/017cbd9c4daf3b1542b5febd8bfa1d641756afc0f7bb6b4d101cfc38b05b4170/detection

**Comment by Soreepeong** [comment]
Malwarebytes false positive report posted: https://forums.malwarebytes.com/topic/276841-false-positive-reports/

**Comment by FloppyAl** [comment]
Thank you for the quick turnaround and being patient. Love XIVAlexander and I can't thank you enough for putting time into developing it. Have a great day!
