### ISSUE TITLE
Version mismatch 

### ISSUE THREAD

**Issue by ElliotSCS** [Soreepeong/XivAlexander#112]
The following image shows up whenever I try to run the loader. All I've done is download the zip from git, extract, and run the loader.

![image](https://user-images.githubusercontent.com/42980282/126410065-da022c08-c264-4c9b-94bd-b38b78213c40.png)

**Comment by Soreepeong** [comment]
Try this release: https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.8.7

Not sure how code signing the executables with self signed certificate "fixes" problems with false positive, but this is what it is. That error message says "The system cannot find the file specified," which indicates that something prevented extraction of XivAlexander component, which probably would be an antivirus software.
