### ISSUE TITLE
5.58 Performance..?

### ISSUE THREAD

**Issue by Kacenova23** [Soreepeong/XivAlexander#114]
Please forgive me if this sounds weird.  I downloaded an older version of XIVAlex over the weekend since my Ping was just getting... Absurd.  And I updated the Opcodes for 5.57 (I found an old thread in here from about 30 days ago) and on Gunbreaker and Dark Knight was having *zero* double-weaving issues, and even noticed the improve weaving issues on both classes that the buttons almost registered the moment I hit them.  I was running on v1.14.8.5, but I downloaded v1.14.8.6 and just deleted the .5 folder and unzipped the .6 and booted XIVAlexander up like normal.  There a setting I need to clear out first?

The double-weaving and everythign is nowhere near as instantaneous as it was over the weekend when I first started using this.  Is there something I have to edit in order to get the oGCD commands to be almost as responsive as they were earlier?  I'm VERY new to using this, so I apologize if this sounds very lost.  I can answer any follow-up questions if needed. 

https://github.com/Soreepeong/XivAlexander/issues/96

I'm playing on NA.  Anybody got any tips or recommendations?  I used the txt file in that thread and just copied and pasted them over.  I suppose one other tidbit was when I copied those 5.57 opcodes, it felt like there was hardly, if any, animation lock (I was paying attention to the GCD and hotbar, not the animations.  I'm just noting the times in which the abilities themselves registered felt VERY responsive with minimal delay) and absolutely NO clipping.  Now... I'm clipping a lot.  And I'm not sure if there's something I need to do or modify to get back to the same performance level XIVAlexander had over the weekend.

Thanks for the help.  And I'm sorry about the wall, just want to make sure it's understood what I'm trying to say. :)

**Comment by justin767** [comment]
How about checking if 'delayed detection' and 'latency correction' are turned off?

**Comment by Christoppolis** [comment]
I'd say i'm experiencing the same thing. XIVAlexander isn't feeling as consistent or effective as it previously was and it's definitely a more noticeable difference. 'delayed detection' and 'latency correction' are turned on, my anti-virus software/Defender have this software selected as an exception and opcodes are set up to date. If anyone has any recommendations or answers it would be nice, thank you.

**Comment by Kacenova23** [comment]
Both are on, Justin, and made sure the normal settings were on as well.  

Like, it doesn't feel like it's egregious;  It's just not as consistent when it comes to double-weaving, which makes doing Ultimate and Savage content rather challenging on certain parts depending on the phase/fight.  Any other settings we'd be able to check to test it out?  I'm open to any suggestions.

**Comment by justin767** [comment]
> Both are on, Justin, and made sure the normal settings were on as well.
> 
> Like, it doesn't feel like it's egregious; It's just not as consistent when it comes to double-weaving, which makes doing Ultimate and Savage content rather challenging on certain parts depending on the phase/fight. Any other settings we'd be able to check to test it out? I'm open to any suggestions.

I was told to turn OFF both 'delay detection' and 'latency correction' in such cases. But regardless, I do feel slight

**Comment by Kacenova23** [comment]
> > Both are on, Justin, and made sure the normal settings were on as well.
> > Like, it doesn't feel like it's egregious; It's just not as consistent when it comes to double-weaving, which makes doing Ultimate and Savage content rather challenging on certain parts depending on the phase/fight. Any other settings we'd be able to check to test it out? I'm open to any suggestions.
> 
> I was told to turn OFF both 'delay detection' and 'latency correction' in such cases. But regardless, I do feel slighty the same as you right now. The performance seems to fluctuate alot. I myself too are trying to do Ultimates from NA in Korean DC.

Oh well shit.  Yeah, I attempted that too.  Like, it's nothing outlandish and still is better than nothing, but it still would be nice to get back to where it's been in the past.  Would anybody know if maybe the fluctuation in performance could be due to server stress or connection or something?  

I really don't understand the specifics behind XIVAlexander on the level of some people, so I may be misusing things or assumptions.  I just wanna try and get the performance reliable again.  It worked flawlessly the two days before 5.58, so I'm wondering what's different for right now.

**Comment by justin767** [comment]
> > > Both are on, Justin, and made sure the normal settings were on as well.
> > > Like, it doesn't feel like it's egregious; It's just not as consistent when it comes to double-weaving, which makes doing Ultimate and Savage content rather challenging on certain parts depending on the phase/fight. Any other settings we'd be able to check to test it out? I'm open to any suggestions.
> > 
> > 
> > I was told to turn OFF both 'delay detection' and 'latency correction' in such cases. But regardless, I do feel slighty the same as you right now. The performance seems to fluctuate alot. I myself too are trying to do Ultimates from NA in Korean DC.
> 
> Oh well shit. Yeah, I attempted that too. Like, it's nothing outlandish and still is better than nothing, but it still would be nice to get back to where it's been in the past. Would anybody know if maybe the fluctuation in performance could be due to server stress or connection or something?
> 
> I really don't understand the specifics behind XIVAlexander on the level of some people, so I may be misusing things or assumptions. I just wanna try and get the performance reliable again. It worked flawlessly the two days before 5.58, so I'm wondering what's different for right now.

Guess we'll have to wait for developer's response for the time being..😭😭

**Comment by justin767** [comment]
Check the new release
