### ISSUE TITLE
Program not working properly

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#116]
It seems like few other users are experiencing similar problems right now, after the 5.58 patch.

The in-game response and double-weaving, while using XivAlexander, doesn't quite feel the same or seems to be working like it was before the newest release.

I fully understand how the developers are fully occupied and busy, and they sure have my full gratitue towards deveolping such savior add-on. But is there a chance in which they can have a look at this problem?

Thank you

**Comment by Soreepeong** [comment]
Try the latest release; I decided that "early penalty" feature is entirely unnecessary, so I've changed that into an opt-in feature.
