### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by sora80** [Soreepeong/XivAlexander#119]
how to fix this error when I do check for update 

https://gyazo.com/361c8b949b98aabd86099caa02b8b3c2

**Comment by Soreepeong** [comment]
It means that a file has become inaccessible/deleted when you tried to check for updates. New release should not crash in that case; if automatic update does not work, you'll have to download manually.

**Comment by sora80** [comment]
this normal ? 

https://gyazo.com/2a8c6465a11b24b74879bd3f4f1af6bb

**Comment by tkiapril** [comment]
These are generic troubleshooting guidelines, try and see if it works:

1. Delete everything related to XivAlexander you downloaded, and download the newest release at: https://github.com/Soreepeong/XivAlexander/releases/latest (use the link in the title).
2. Run the game and run `XivAlexanderLoader64.exe`. If it didn't work, run `XivAlexanderLoader32.exe`.
3. If the message `The requested operation requires elevation` appears again, right-click the executable file, and try `Run As Administrator.`
4. If it still won't work, please try adding `XivAlexander32.dll, XivAlexander64.dll, XivAlexanderLoader32.exe, XivAlexanderLoader64.exe` to the antivirus exclusion list, and then start over from re-downloading the files.
