### ISSUE TITLE
I dunno where to turn off delay detection and turning off latency correction

### ISSUE THREAD

**Issue by ForeverKnight26** [Soreepeong/XivAlexander#122]
Ive been confused where to disable said option since im using vpn but im not getting any 10ms on mudfish or going above 200+ ping but the log viewer says i should disable delay detection and latency correction but i dunno where

**Comment by tkiapril** [comment]
Sorry, it's a discrepancy caused due to changed terminology on the menus. on Function->Delay Correction, Integrate Server Delay is Delay Detection and Latency Sample Attenuation is Latency Correction. However, they should be off by default.

**Comment by tkiapril** [comment]
Documentation should make sense now. If your issue has been resolved, please close the issue. Otherwise, feel free to ask any questions. The issue will be closed by the maintainer if it goes stale.

**Comment by tkiapril** [comment]
Actually, I stand corrected. The options above are enabled by default, so you might want to disable it as it fits your needs.
