### ISSUE TITLE
Can this use in Steam platform?

### ISSUE THREAD

**Issue by ishiryuz** [Soreepeong/XivAlexander#123]
Can this use in Steam platform? I'm not sure I try select ffxivboot64.exe with XivAlexanderLoader64.exe.
But it seem run with window pc platform.

**Comment by tkiapril** [comment]
I'm speculating that it should work without problem since the game executable itself should be the same, but cannot be sure. Have you tried running it?

**Comment by Sorolyr** [comment]
I've been having issues with the steam version as well, I remember a year or two ago they made it so you couldn't log in if you launch straight from the ffxivboot.exe if you owned the steam store version of the game. I downloaded the latest XivAlexander release that uses a loader and I can't get it to work.

**Comment by tkiapril** [comment]
XivAlexander can still attach to running instances of the game, not just only launching it. Have you tried executing XivAlexanderLoader after you launched the game?

**Comment by ishiryuz** [comment]
Oh I see now I run XivAlexander after launch FFXIV. It work fine thanks.
