### ISSUE TITLE
Some questions about the page "How to find opcodes"

### ISSUE THREAD

**Issue by MnFeN** [Soreepeong/XivAlexander#126]
1. About "S2C_ActorControl": 

> S2C_ActorControl
Use a casted action, and cancel it by moving.
Find the one with actionId that you've just used.
0078 (Cure) is correct.
S2C_ActorControl(0x01c8) is the correct opcode to refer to.

My understanding is that when a cast is interrupted, it would generate a logline like "S2C_ActorControl(0x01c8): CancelCast: actionId=**0038**", and the actionId should match the skill ID. However, when I tested some magics like cure or clemency and stop it by movement, the actionId is always "0038", which is the same as in the example. The opcode I got is correct, so I am wondering if it is a bug.
   
2. The subtitle "S2C_Add**Action**Effect" is not consistent with all the other "S2C_AddStatusEffect". The former one looks like a typo.

**Comment by Soreepeong** [comment]
Both are fixed. Thank you for reporting!
