### ISSUE TITLE
Chinese Client 5.5 Release Opcode Configuration 

### ISSUE THREAD

**Issue by MnFeN** [Soreepeong/XivAlexander#127]
{
	"C2S_ActionRequest": "0x02e0",
	"C2S_ActionRequestGroundTargeted": "0x0226",
	"S2C_ActionEffect01": "0x0085",
	"S2C_ActionEffect08": "0x00ff",
	"S2C_ActionEffect16": "0x0110",
	"S2C_ActionEffect24": "0x03dc",
	"S2C_ActionEffect32": "0x03d5",
	"S2C_ActorCast": "0x01e6",
	"S2C_ActorControl": "0x008b",
	"S2C_ActorControlSelf": "0x0190",
	"S2C_AddStatusEffect": "0x02d5",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

**Comment by MnFeN** [comment]
> Note that if you share the file name too, then I can include into the release zip files.

Oh I just saw your reply. The file name is "game.CN.2021.08.10.0000.0000.json". Thanks for your development!

**Comment by Soreepeong** [comment]
Thank you! I've included the file into the release.

**Comment by Soreepeong** [comment]
By any chance, do you know the IP address range of all 3(?) Chinese datacenters?

**Comment by MnFeN** [comment]
Sorry I don't know how to get those IP addresses. There are 3 servers and it seems that the previous addresses were included in #43 . Btw, why do we need those addresses if we can fill in "0.0.0.0" and the program could still work properly?

**Comment by Soreepeong** [comment]
The other program for non-Windows players need the IP address range to figure out which opcode definition files to use. Also, I thought that other issue only got 2 IP address ranges instead of 3.

**Comment by MnFeN** [comment]
![host](https://user-images.githubusercontent.com/85232361/134229218-7d5517df-2d5e-413d-9804-e2050a9a2915.png)
Here are the three servers "MaoXiaoPang"（猫小胖）, "MoGuLi" （莫古力）, "LuXingNiao" （陆行鸟）from top to bottom.

**Comment by Soreepeong** [comment]
Thank you!
