### ISSUE TITLE
5.45 Korean Server Hotfix

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#128]
Hello,

There was a hotfix patch for Korean server today (August 12th).
May I ask when the updates will become available please? Gaming experience is so bad without XivAlexander :(

Thank you !!

**Comment by justin767** [comment]
Can anyone help please 🙏🙏🙏

**Comment by justin767** [comment]
"C2S_ActionRequest": "0x02fb",
	"C2S_ActionRequestGroundTargeted": "0x02fb",
	"S2C_ActionEffect01": "0x02dc",
	"S2C_ActionEffect08": "0x0197",
	"S2C_ActionEffect16": "0x02cd",
	"S2C_ActionEffect24": "0x0254",
	"S2C_ActionEffect32": "0x00cc",
	"S2C_ActorCast": "0x01b4",
	"S2C_ActorControl": "0x02b6",
	"S2C_ActorControlSelf": "0x00ae",
	"S2C_AddStatusEffect": "0x028c",

got these by following the instructions. It'd be great if anyone can check if its valid.

**Comment by Soreepeong** [comment]
Close! GroundTargeted should be 0x01ef; other than that, it worked fine.

```json
{
	"C2S_ActionRequest": "0x02fb",
	"C2S_ActionRequestGroundTargeted": "0x01ef",
	"S2C_ActionEffect01": "0x02dc",
	"S2C_ActionEffect08": "0x0197",
	"S2C_ActionEffect16": "0x02cd",
	"S2C_ActionEffect24": "0x0254",
	"S2C_ActionEffect32": "0x00cc",
	"S2C_ActorCast": "0x01b4",
	"S2C_ActorControl": "0x02b6",
	"S2C_ActorControlSelf": "0x00ae",
	"S2C_AddStatusEffect": "0x028c",
	"Server_IpRange": "183.111.189.0/24",
	"Server_PortRange": "1025-65535"
}
```
