### ISSUE TITLE
Ran XIVAlexanderLoader this afternoon and windows said "threat detected"

### ISSUE THREAD

**Issue by kanakakauai** [Soreepeong/XivAlexander#13]
I ran XIVAlexanderLoader.exe and this happened. 

Threat blocked
2/13/2021

Status:Removed

Threat detected: Trojan:Win32/Wacatac.B!ml
Alert level: Severe
Date: 2/13/2021
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected items: ~Downloads\plugins\XivAlexanderLoader.exe

I thought you might want to know, and wasn't sure if this was false positive.

**Comment by Soreepeong** [comment]
Yeah, hence the

> As it uses DLL injection, your anti-virus software might flag this add-on. You might have to add both XivAlexander.dll and XivAlexanderLoader.exe to exclusion list. Refer to your anti-virus software manual for instructions.

in the readme. It's inevitable for this kind of program.

**Comment by kanakakauai** [comment]
Yes I've added both to my exclusion list, but it still got flagged. My computer just keeps removing it :( 

Any suggestions

**Comment by Soreepeong** [comment]
Which antivirus software are you using? They will usually give you an option to restore and exclude it from detection notification.
Try looking for Quarantine feature of your antivirus, and try restoring files from there.

**Comment by kanakakauai** [comment]
malware bytes. It's seems to be working now. Thank you
