### ISSUE TITLE
Xivalxander window not showing up

### ISSUE THREAD

**Issue by ForeverKnight26** [Soreepeong/XivAlexander#130]
Hello again Im having issues when I start up the game with the XivAlexander loader the window with the options and stuff doesnt load also but i tried playing with it and it kinda works? I even open it in admin mode

**Comment by Soreepeong** [comment]
Are you sure that it isn't in system notification area (tray)? Does it work correctly if you run game launcher separately, run the game, and then load XivAlexander?
