### ISSUE TITLE
Latest version crashing in Chinese client

### ISSUE THREAD

**Issue by hyskylord** [Soreepeong/XivAlexander#132]
I saw the following error immediately after loading the latest v1.14.8.10 in Chinese client:

An unexpected error has occurred. Exiting FFXIV:
XivAlexander64(32? not sure).dll
kernel32.dll
ntdll.dll

Tried on JP client and also tried to roll back to v1.14.8.9 and both worked fine. Looks like there is some compatibility issue in the latest version.

**Comment by Soreepeong** [comment]
Does it still happen after resetting config (delete `config.runtime.json`)? Also, you can press `Ctrl+C` on the messagebox to copy everything; please copy everything and paste here using 1.14.8.11 which I will release shortly.

**Comment by hyskylord** [comment]
Hi,

  Thank you for your reply. I tried to reset the config and the game still crashed. The following is the complete message.
---------------------------
最终幻想14
---------------------------
《最终幻想14》发生意外错误，程序即将关闭。
2021-07-30_17:43

XivAlexander64.+24537
XivAlexander64.+76823
XivAlexander64.+7645E
XivAlexander64.+7650D
KERNEL32.DLL+17034
ntdll.dll+52651
---------------------------
确定   
---------------------------


> Does it still happen after resetting config (delete `config.runtime.json`)? Also, you can press `Ctrl+C` on the messagebox to copy everything; please copy everything and paste here using 1.14.8.11 which I will release shortly.

**Comment by Soreepeong** [comment]
Try the newest version. Was it the case where your latency was reported as 0 for whatever reason?

**Comment by hyskylord** [comment]
Yes, the issue was fixed in the latest version. Not sure if it is a VPN issue since the same VPN works for Japan client.
