### ISSUE TITLE
Using alexander alongside Mudfish causes an error window to pop up

### ISSUE THREAD

**Issue by Gbraker7000** [Soreepeong/XivAlexander#134]
Running mudfish and then trying to open alexander will cause the following message to pop up
![image](https://user-images.githubusercontent.com/7454491/130346775-6fffeece-59a4-4e98-8224-6c75c9711399.png) . While the game keeps on running on the background if you click ok the game and alexander will close.

Opening either in any order (mudfish into alexander and viceversa) will cause the error to pop up

**Comment by Soreepeong** [comment]
Which version are you using? Make sure you're using the most recent version.

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivAlexander/issues/132
