### ISSUE TITLE
today opcode please confirm 

### ISSUE THREAD

**Issue by gnomerock** [Soreepeong/XivAlexander#135]
```json
{
	"C2S_ActionRequest": "0x02dc",
	"C2S_ActionRequestGroundTargeted": "0x0152",
	"S2C_ActionEffect01": "0x03ca",
	"S2C_ActionEffect08": "0x03c4",
	"S2C_ActionEffect16": "0x00fa",
	"S2C_ActionEffect24": "0x0339",
	"S2C_ActionEffect32": "0x023c",
	"S2C_ActorCast": "0x015d",
	"S2C_ActorControl": "0x00b0",
	"S2C_ActorControlSelf": "0x02b6",
	"S2C_AddStatusEffect": "0x0387",
	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24",
	"Server_PortRange": "1025-65535"
}
```

**Comment by briankurtz249** [comment]
These coincide with the codes I manually found as well.

**Comment by arturhns** [comment]
Did mine for the first time today and the codes match with those I found too. Seems solid.

**Comment by Soreepeong** [comment]
[game.JP.2021.08.17.0000.0000.zip](https://github.com/Soreepeong/XivAlexander/files/7039997/game.JP.2021.08.17.0000.0000.zip)

you might as well extract this into xivalex folder

**Comment by Soreepeong** [comment]
@IckyBikkie should not matter, as long as you don't have some strange addon running alongside ffxiv

**Comment by IckyBikkie** [comment]
> 
> 
> @IckyBikkie should not matter, as long as you don't have some strange addon running alongside ffxiv and xivalex.

Even if my IP range is just 0's?

**Comment by ne0dym7** [comment]
@Soreepeong appreciate the quick fix, I was wondering if it is possible for me to manually update XivMitmLatencyMitigator on my end using these. since that tool pulls data from XivAlexander I'm not sure there's anything I can do besides wait for an update. sorry for hijacking this thread and TIA!

**Comment by YOxidized** [comment]
> @Soreepeong appreciate the quick fix, I was wondering if it is possible for me to manually update XivMitmLatencyMitigator on my end using these. since that tool pulls data from XivAlexander I'm not sure there's anything I can do besides wait for an update. sorry for hijacking this thread and TIA!

This is a good question; I was able to manually update the opcodes in a mirrored version of the old Latency Mitigator, but since the auto update feature was added, I find myself unable to do this, sadly.

**Comment by Soreepeong** [comment]
@ne0dym7 @YOxidized i've updated the definition for the time being. in case that i get late on updating the repository, you can run the script once, exit it, and then edit `definitions.json` created in the directory.

**Comment by YOxidized** [comment]
Works great, thank you!

**Comment by perks** [comment]
Hi, I edited the opcode definition with above, but when Alexander injects nothing is logged when performing actions.
