### ISSUE TITLE
A noob question about opcodes

### ISSUE THREAD

**Issue by Spanglish1337** [Soreepeong/XivAlexander#137]
Greetings,

I am from south america and I am just blessed to be able to find this plugin. I Just used it and tried it and with the default settings (I didn't change anything) it works amazing, I have never double-weaved before and it is an incredible feeling to be able to do so.

My question is, are opcodes somethings that needs to be updated every time FFXIV gets an update? Do we have to do it on our own? I tried to read the guide about finding opcodes but it looks very overwhelming

**Comment by Spanglish1337** [comment]
bump

**Comment by Soreepeong** [comment]
It needs to be updated every patch. Usually, people will figure out the new opcodes and create an issue, sharing their findings.

**Comment by Spanglish1337** [comment]
> It needs to be updated every patch. Usually, people will figure out the new opcodes and create an issue, sharing their findings.

Oh alright! That's nice, so they find the opcodes and we have to update it on our end or we just wait until you update the plugin?

**Comment by Soreepeong** [comment]
The former - you can use "Edit opcode configuration" or so to make it work after a game update.

**Comment by Spanglish1337** [comment]
Okay, then I wait until someone else finds out, because I still don't understand how, and then I copy paste that in Opcode Configuration! Thank you!
