### ISSUE TITLE
What are the optimal settings for high ping vpn users

### ISSUE THREAD

**Issue by Volfield** [Soreepeong/XivAlexander#139]
My OGCDs aren't firing up immediatly after the new updates.

Looking for the equivalent settings to: 
![ci5976dHwQ](https://user-images.githubusercontent.com/2647976/131585419-341a20dd-0212-47a7-b5c3-2df8b8a88559.png)

**Comment by Spanglish1337** [comment]
I play with 140 ping, I can double weave very comfortable with this plugin, I use the defaul options, but mine look different from yours.

![image](https://user-images.githubusercontent.com/89648547/131697706-ae99dc68-c9bf-4733-809b-f2904dbe92ad.png)

**Comment by Volfield** [comment]
Okay, i mode 3 and it seems to work semi equivalently to the settings of the older versions.
And yeah the settings look diferent because it was the older version of xivalex and it was working better than the new one.
I'll close the issue as it seems to be just how the new ver works.
