### ISSUE TITLE
Cannot run it for some reason, it says: "Entry Point Not Found" every time

### ISSUE THREAD

**Issue by silver5430** [Soreepeong/XivAlexander#14]
I opened when FFXIV was running, tried alot of things such as disabling anti-virus, downloading the file again, and restarting PC
https://i.imgur.com/70Tq1VH.png

**Comment by Soreepeong** [comment]
Ah, I only tested on Windows 10, and that API is only available on W10. I'll fix that later today.

**Comment by silver5430** [comment]
I am running Windows 10 albeit a very old version, it is version 1607

**Comment by Soreepeong** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription
Microsoft claims that the API is available fron 1607, but apparently it's not. As the usage for the API is purely for debugging, I'll just make the program not use the API if it's not found

**Comment by Soreepeong** [comment]
Fixed with b0c5847e40445b6f0cb01c31c9365ae3f0974a28. Try again after downloading the new release.

**Comment by silver5430** [comment]
Hi, I'm writing again to say that i was able to run it fine with the new release and it worked wonders. I'm so amazed that this is the power of people with low ping been having. Weaving feels so damn nice.
