### ISSUE TITLE
How do I turn off/uncheck "Compensate for Server Delay"? I'm having an error due to my vpn on mode 3

### ISSUE THREAD

**Issue by RinkoNakiri** [Soreepeong/XivAlexander#141]
I always used mode 2 because I always have receiving that error on mode, but I tried again the mode 3 and ignoring the error on the log but I think mode 3 is better than mode 2 for me, is there any way to disable or uncheck "Compensate for server delay" because I can't find it anywhere on the feature tab. thank you very much.

**Comment by tkiapril** [comment]
Mode 2 is supposed to be the non-compensating option (equivalent to unchecking the compensate option in the old versions.)

**Comment by RinkoNakiri** [comment]
is it okay to still use mode 3 even there is an error or ignore the "uncheck Compensate for server delay"? I mean, for me, it feels like it is more smoother than mode 2. Thank you very much.

**Comment by tkiapril** [comment]
What kind of error do you get? Please copy and paste it here, or post a screenshot. Also, unchecking 'Compensate for Server Delay' does not exist on the newer versions, it's equivalent to Mode 2.

**Comment by RinkoNakiri** [comment]
![mode3](https://user-images.githubusercontent.com/89952789/131990741-7a1ee7f3-391a-4ef4-a5fe-8598bd4d8e29.png)
![mode2](https://user-images.githubusercontent.com/89952789/131990790-8825c2db-8626-487a-b0f7-f47510319549.png)
Hello, this is what I get from using both mode 3 and mode 2, It feels more easy to double weave on mode 3 compare to mode 2, thank you very much.

**Comment by tkiapril** [comment]
That message is not an error, but a warning telling you that it may be unable to calculate appropriate delay reduction and thus the program may not have any effect. You might be able to get away with using mode 3, but the program might have no real effect.

**Comment by RinkoNakiri** [comment]
I see, I will stick with mode 2 then, thank you very much!
