### ISSUE TITLE
Steam Version dont reconize my subsciption. With XIV Alexander.

### ISSUE THREAD

**Issue by Glurak18** [Soreepeong/XivAlexander#142]
When i use xiv alexander on my german XIV Steam client version and i try to login i always get the message that my account is not allowed to play on this plattform cause of no licence or subsciption found. 

When i start the game normaly out of steam it works perfectly. Is there a way to fix this? 

And yes i have a Square enix version on this account aswell that has no active sub at the moment but a steam acc with a sub aswell

**Comment by tkiapril** [comment]
For use on Steam version for now, please launch the game to the title screen first and then launch XivAlexander. Launching the game from XivAlexander does not work for the Steam version.

**Comment by Soreepeong** [comment]
The launcher launched by XivAlexanderLoader is only applicable for international PC, Korean, or Chinese version users. Otherwise, you will have to launch the game first, and then run XivAlexanderLoader to load this program.
