### ISSUE TITLE
Always on Top setting does not get saved

### ISSUE THREAD

**Issue by Babbie** [Soreepeong/XivAlexander#145]
Despite there being a setting in the config.runtime.json, the setting for Always on Top is always on when the application is started.

**Comment by Soreepeong** [comment]
Runtime configuration file format has been slightly changed. Does the setting not persist even if you toggle it from XivAlexander menu? (Also, always on top settings is for the game window itself; control window is always set to always on top on startup by default.)

**Comment by Babbie** [comment]
Ah, I assumed the setting was for the control window.
Is there any chance that setting can be saved as well? For me, the window is not very useful, so I toggle it off every time, but I do want the window open so I can force quit the game easily if it freezes on shutdown (which happens often to me)

**Comment by Soreepeong** [comment]
Sure, I'll do that, but note that there is an XivAlexander icon in system notification area (tray area of taskbar). Look for a gear icon.

**Comment by Babbie** [comment]
Thank you for the tip! I was unaware. Also, thank you for the quick replies!
