### ISSUE TITLE
Tomorrow's 5.5 Patch

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#147]
Hello, thank you always for developing and providing this amazing software. This literally saved my LIFE with all other high-ping players out there.

I was wondering if there will be an update provided tmr? Since there is a 5.5 patch release in KR servers.

Thank you!

**Comment by Soreepeong** [comment]
Sure, I'll do that tomorrow, probably at latest 11pm.

**Comment by justin767** [comment]
> Sure, I'll do that tomorrow, probably at latest 11pm.

Thank you so much!!!

**Comment by Soreepeong** [comment]
Here you go: https://github.com/Soreepeong/XivAlexander/raw/main/StaticData/OpcodeDefinition/game.KR.2021.09.01.0000.0000.json

**Comment by justin767** [comment]
thanks !!!!!!!
