### ISSUE TITLE
Program not working after the update

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#148]
Hello, the recent updated XivAlexander does not seem to work with Korean server for some reason?
Nothing shows up on my Log screen

**Comment by Soreepeong** [comment]
Are you using this without installing? In that case, I forgot to include a file in the archive. Try downloading it again, and it should work. Otherwise, if you did install, check which files exist in `%APPDATA%\XivAlexander`.

**Comment by justin767** [comment]
> Are you using this without installing? In that case, I forgot to include a file in the archive. Try downloading it again, and it should work. Otherwise, if you did install, check which files exist in `%APPDATA%\XivAlexander`.

Works amazing again after re-installing!! Thank you for the help!

**Comment by ArmoredSavitar12** [comment]
Hi does Version matter ? I just downloaded the one on the github and my
region is japan . Do I need to change something ?

**Comment by yordleIRL** [comment]
I reinstalled and updated the files, to which it stopped working, it says it can't verify both x32 and x64 dll and both loaders, then my antivirus recognizes XivAlexanderLoader32.exe as a trojan file: 

Trojan:Win32/Sabsik.FT.A!ml

So what's going on about that? Whatever the response may be, should I use a different release instead?

**Comment by Soreepeong** [comment]
Version does not matter as long as it works, and I don't really care about antiviruses detecting it anymore.

**Comment by justin767** [comment]
> I reinstalled and updated the files, to which it stopped working, it says it can't verify both x32 and x64 dll and both loaders, then my antivirus recognizes XivAlexanderLoader32.exe as a trojan file:
> 
> Trojan:Win32/Sabsik.FT.A!ml
> 
> So what's going on about that? Whatever the response may be, should I use a different release instead?

Try disabling your anti-virus software during XivAlexander installation, and add the software as an exception for its virus detection? If you are using Windows defender, I had no problem after setting it up like this.
