### ISSUE TITLE
Incompatibility with VPN 'ReduceTheLag'

### ISSUE THREAD

**Issue by atraholt** [Soreepeong/XivAlexander#15]
Heyo, I'm kinda writing this as a proxy for a friend who's reliant on this VPN service by the name of [ReduceTheLag](https://www.reducethelag.com/).

The problem is that when XivAlexander injects itself into the FFXIV process to redirect network packets into it's own thread before passing it along, FFXIV crashes because that's **also exactly how ReduceTheLag operates**. It's a "hassle free" VPN service which has a bunch of process injection DLLs that will inject into a game to redirect the game's traffic to its servers. It runs as a Windows service that waits for a process it knows about to start and then begins to inject itself. If I am quick enough I can get XivAlexander in before RTL, but then RTL fails to run. 

My hope in writing this is if you know any way to make these processes interoperate or if all hope is lost when there's a battle inside the IPC going on.

If you need any kind of logs, I can provide them from either process. Feel free to ask for difficult debugging things; my day job is programming (though not in C, but programming is programming)

**Comment by Soreepeong** [comment]
Can you try again with the latest release? I've changed the program to hook import address table instead of function itself. If it still causes errors, if a messagebox pops up from the game, let me know the message.

**Comment by atraholt** [comment]
This seems to have done the trick! Thank you for helping out!
