### ISSUE TITLE
글로벌서버에서 한글패치이후 레지스탕스 최종무기버전이 적용되지않아 게임플레이에 지장이있다.

### ISSUE THREAD

**Issue by chachayo3** [Soreepeong/XivAlexander#150]
레지스탕스 최종무기버전이 적용되지않아 게임플레이에 지장이생기고있습니다

**Comment by Soreepeong** [comment]
* https://na.finalfantasyxiv.com/lodestone/topics/detail/6526ce95a595e8a557b55736f85f19687dc11883/
> Further main scenario quests, Save the Queen: Blades of Gunnhildr, and Resistance weapon upgrades are scheduled to be released in Patch 5.55.
* http://www.ff14.co.kr/news/notice/view/1976
> ※ 아래의 콘텐츠는 향후 패치에서 추가될 예정입니다.
> [5.55] 주요 퀘스트 Part2 / 장비 강화 임무 '세이브 더 퀸


아직 없는 게 정상입니다.
