### ISSUE TITLE
0ms VPN

### ISSUE THREAD

**Issue by defineonly** [Soreepeong/XivAlexander#151]
The logs are reporting that "your VPN or network might be reporting 0 ping. Unchecking "Compensate for Server Delay" is recommended." 

Has the option for "Compensate for Server Delay" been removed? I do not see the option in the current version since I'm using a VPN that emulates 0ms.

**Comment by Soreepeong** [comment]
Oh, I need to change messages. It should be "Use Mode 2" instead, as that mode does not use current latency information to work.

**Comment by defineonly** [comment]
I'll try it out. I'm assuming its also normal for the socket latency to say 'failed to resolve' in the control window where the ping latency/response delay medians are displayed.
