### ISSUE TITLE
Where are the mitigation options?

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#152]
With the newest released version, I do not see the window for choosing one of the three options for latency mitigation?
I only see this window.
<img width="296" alt="`" src="https://user-images.githubusercontent.com/82459386/134611534-4571a56f-6bab-422e-9c3e-023c7660857a.png">

**Comment by Soreepeong** [comment]
All the options are now accessible from the control window. Try "관리 창 보이기".

**Comment by justin767** [comment]
> All the options are now accessible from the control window. Try "관리 창 보이기".

Thank you!!
