### ISSUE TITLE
Port it as a Dalamud plugin instead?

### ISSUE THREAD

**Issue by Bananaman** [Soreepeong/XivAlexander#154]
Hi Soree, amazing work on this project. Lag compensation is something that Square should be doing themselves! It's crazy that the community has to fix the game's problems always.

I was thinking... since this is a plugin that injects into the memory of the game process, why not port it into a Dalamud plugin? It's able to give you full access to the game's memory and also ping detection (see the PingPlugin dalamud plugin). So isn't that enough to make a lightweight port of this feature? To read the current ping, and adjust all incoming "skill lock" timer commands accordingly?

Best Regards.

**Comment by Soreepeong** [comment]
You should try this one if you want to use the feature as a Dalamud plugin: https://github.com/UnknownX7/NoClippy

**Comment by Bananaman** [comment]
@Soreepeong Oh, huh! Thank you! I will experiment with both and decide which to use. :) You're awesome. <3

**Comment by Bananaman** [comment]
I did a check of the source code of NoClippy, in particular:

https://github.com/UnknownX7/NoClippy/blob/master/LagCompensation.cs

I see that it doesn't check ping at all, and instead adjusts the animation lock based on what ideal ping conditions would be. But I can't really say if the method they use is a good one or not.

I continue using XivAlexander instead @Soreepeong. Your solution seems much more advanced with algorithms and your knowledge of the network protocol etc. :)
