### ISSUE TITLE
EXDF 적용 시 오류

### ISSUE THREAD

**Issue by popotosalad** [Soreepeong/XivAlexander#155]
![제목 없음](https://user-images.githubusercontent.com/32959063/134794292-1ad624b0-1a3d-44b9-af69-ae5951f88833.png)

EXDF 플러그인을 임포트 할 때 오류가 발생합니다. 영어 클라이언트로 실행했고, 플러그인은  english w/ japanese를 골랐습니다.
플러그인을 드래그 & 드롭 하면 unexpected error가 발생합니다. 해결 방법이 있을까요

**Comment by Soreepeong** [comment]
일단 저 창이 두개가 뜨면 안 되는데, 설치 폴더로 복사한 파일이 여러개인가요? d3d11.dll(+d3d9.dll) 1-2개 또는 dxgi.dll(+d3d9.dll) 1-2개 또는 dinput8.dll 1개만 복사해 넣으셔야 합니다.
오류 메시지 내용이 저렇게 뜨는건 확인해 보겠습니다만, 혹시 압축 프로그램에서 바로 드래그해 넣으셨나요?

**Comment by popotosalad** [comment]
게임 폴더에는 XivAlexander64.dll만 d3d11.dll로 바꿔서 넣었습니다. 혹시 기존에 적용된 한글 채팅 패치 때문에 dinput8.dll 이 있던 게 문제였을까요?
메뉴에서 불러오기를 사용하면 저 깨진 글자로 나오는 오류가 발생하고, 드래그 해서 넣었을 때는 unexpected error가 발생합니다. 오류 메시지는 unexpected error 파일명 + 깨진 글자로 나옵니다. 파일은 압축 해제 한 상태에서 넣었습니다.

**Comment by Soreepeong** [comment]
게임을 켤 때 설치한 이후로는 XivAlexanderLoader32/64.exe를 이용하지 말고 XIVQuickLauncher이나 공식 런처 등을 이용해서 실행하시면 한번만 로드될 테니 그렇게 해주시고, 오류 메시지는 깨지지 않게 수정 중이니, 파일 올리면 그걸로 다시 한번 확인 부탁드립니다. 일단은 잠시만 기다려 주세요.

**Comment by Soreepeong** [comment]
[XivAlexander_1_14_8_19-test.zip](https://github.com/Soreepeong/XivAlexander/files/7231051/XivAlexander_1_14_8_19-test.zip)

이걸로 테스트해서, 오류 메시지가 어떻게 뜨는지 확인부탁드립니다.

**Comment by popotosalad** [comment]
공식 런처로 실행하니 아예 아무것도 로딩 되지 않습니다. XivAlexanderLoader로 실행해야 해당 창이 나오는데 오류 메시지도 여전히 깨진 상태입니다. 폰트 변경은 일단 EXDF 문제를 먼저 해결하고 싶어서 적용하지 않았는데, 이렇게 오류가 발생하는 상황에서도 한글 패치는 자동으로 풀리네요. 정상인가요?

**Comment by Soreepeong** [comment]
![image](https://user-images.githubusercontent.com/3614868/134801721-1339b57b-0444-40c6-a3c4-85cc2b77e747.png)

## "설치"했는데 자동으로 실행이 안되는 건
* 1번은 게임 설치경로에 d3d11.dll, 2번과 3번은 각 %APPDATA%\XivAlexander 및 %LOCALAPPDATA%\XivAlexander 입니다. 해당 폴더에 빨간색으로 표시한 파일이 있는 게 맞나요?

## 오류메시지에 대한 건
* 오류 메시지에 추가로 0x로 시작하는 오류 코드가 같이 뜨나요?
* 혹시 그게 뭐든간에 경로에 영문이나 숫자가 아닌 문자가 들어가 있으면, 없는 경로로 옮겨서 테스트 부탁드립니다. 지금 확인하는데 경로에 일부 문자가 들어간 경우 파일이 로드가 안 되는 문제가 있어 수정 중입니다.

**Comment by popotosalad** [comment]
방금 디렉토리 말씀하셔서 사용자 계정 명 변경하고 왔습니다. 사용자 명이 한글인 게 문제였는지 오류 메시지가 뜨는 건 해결 됐습니다. EXDF 파일을 불러오는 것까진 성공했는데 게임 클라이언트에는 적용이 안 되네요. 공식 런처로 실행했을 때 해당 창이 뜨지 않는 건 여전합니다.

![asd](https://user-images.githubusercontent.com/32959063/134803237-f837e324-5df0-4839-aac8-ff5275c30098.png)

파일은 다 들어가 있습니다.

**Comment by Soreepeong** [comment]
d3d11.dll 으로 복사를 했는데 자동으로 불러와지지도 않고 게임을 켤 때 오류가 뜨지도 않는다면, 올바른 경로로 올바른 파일을 복사했는지 혹시 모르니 다시 한번 확인 부탁드립니다. XivAlexander32.dll 이 아니라 XivAlexander64.dll 을 d3d11.dll 으로 복사해서 최종적으로 다음 경로로 들어간 것이 맞는지 (게임 폴더가 다르거나 스팀 설치일 경우 적당히 변경):

> C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\d3d11.dll

해당 기능은 게임을 켤 때 XivAlexander가 같이 로드되어야 작동합니다.

게임을 실행하고 Loader를 켠 다음에 컨트롤 창의 재시작 가능을 통해 재시작했을 경우 XivAlexander가 같이 실행되는지요?

**Comment by Soreepeong** [comment]
[XivAlexander_1_14_8_19-test2.zip](https://github.com/Soreepeong/XivAlexander/files/7231207/XivAlexander_1_14_8_19-test2.zip)

일단 한글 경로 관련 오류는 수정하였고, 설치만 확실하게 된 건지 확인해주시면 될 것 같습니다.

## 삭제
1. `%APPDATA%/XivAlexander` 완전 삭제 
2. `%LOCALAPPDATA%/XivAlexander` 완전 삭제 
3. 게임 설치 폴더 안 `d3d11.dll` 삭제

## 설치
1. `install.bat` 실행
2. 이용하고자 하는 게임 설치 폴더 (글썹 클라에 한국어를 먹이고자 할 경우 글썹 설치 경로 안의 `game` 폴더) 안에 `ffxiv_dx11.exe` 및 `ffxiv.exe` 가 있는지 확인한 후 거기로 `XivAlexander64.dll` 을 복사해서 `d3d11.dll` 으로 파일 이름 변경
3. 게임 공식 런처 (방금 붙여넣은 폴더 윗 폴더의 boot 폴더 안의 FFXIVBoot.exe) 를 통해 실행

## 세팅
1. `모딩 > 사용` 체크
2. `모딩 > 표시언어고정` 에서 원하는 언어 선택
3. `모딩 > 폰트 변경 > 프리셋 불러오기` 에서 `FontConfig/Mix.JpKr.json` 을 이용하되 만약 글썹이나 한썹 설치 경로가 기본값이 아닐 경우 파일 내용에서 게임 설치 경로 변경
4. `모딩 > EXDF 변환규칙 > 규칙 파일 불러오기` 에서 `ExcelTransformConfig/EnglishWithKorean.json` 및 `KoreanWithEnglish.json` 선택
5. https://github.com/adobe-fonts/source-han-sans/releases/tag/2.004R 에서 `Language Specific OTFs Korean (한국어)` 받아서 압축 풀고 전부 다 모든 사용자를 위해 설치
6. `재시작 > 아래 설정을 반영해 재시작`

이렇게 하고 나면 게임을 재시작하면서 프로그래스바가 두번 떠야 할 것입니다.

**Comment by popotosalad** [comment]
![제목 없음](https://user-images.githubusercontent.com/32959063/134804943-0ac7d92f-38b1-4429-bb58-a47a6a9b763b.png)

E클라를 사용하고 있기 때문에 표시 언어는 영어로 선택했고, 영어 + 일어기 때문에 굳이 폰트 변경은 적용하지 않았습니다. 타이틀 화면 로고가 J클라 로고로 바뀐 것으로 보아 뭔가 바뀌고 있긴 한데 정작 인게임에서는 변한 게 없습니다.

재시작을 눌렀을 때 뭔가 추가로 뜨는 건 없었습니다. 그냥 게임 창이 꺼졌다가, 다시 로더가 리로드 되는 것 뿐이었어요.

 혹시 뭔가 더 놓치고 있는 게 있을까요?

**Comment by Soreepeong** [comment]
저기서 schema.json 이 처음부터 들어가지 않도록 막혔어야했는데 왜 들어갔는지는 알아보아서 못 들어가게 고쳐야 합니다.

* 해당 항목(exceltransformconfig.schema.json)은 제거하고 다시 한번 재시작 메뉴로 재시작하고 뜨는 로그를 보여주시겠어요?
* 이 스크린샷은 loader을 게임 시작 후 별도로 켠 건가요? 어떻게 하든 게임을 실행할 때 loader를 건드리지 않고도 xivalexander가 자동으로 불러와져야 재시작 메뉴를 통하지 않고도 기능이 작동하게 됩니다.

**Comment by Soreepeong** [comment]
또한 설정 > 런타임/프로그램 설정 변경에서 한번 비교 부탁드립니다. 

![image](https://user-images.githubusercontent.com/3614868/134805591-7db21da3-ed61-45ef-a9e6-fcf58258f4c9.png)

**Comment by Soreepeong** [comment]
일단 영문자가 아닌 문자 관련으로는 진짜 최종(?) 수정을 했으니 https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.8.20 오류 메시지가 발생한다면 확인바랍니다.

**Comment by popotosalad** [comment]
해당 스크린샷은 XivAlexanderLoader.exe를 따로 실행한 뒤, EXDF 파일을 선택하고 재시작을 했을 때 나온 화면입니다.

이후 이것저것 시험해봐서 어떻게든 작동하도록 만들긴 했습니다. 무엇이 문제였는지는 정확히 모르겠지만 
1) 재시작을 눌렀을 때 ffxivboot.exe 파일을 사용하여 실행하라는 메시지가 뜸 
2) 다른 폰트 적용을 선택함 (gulim freestyle로 기억)
이 상황에서 수동으로 공식 런처를 사용해서 게임을 시작했을 때 폰트 설치를 하면서 EXDF도 적용이 되었습니다. 

그 이상으로 딱히 건드린 건 없는 데 해결이 됐네요. 주말의 귀중한 시간 할애해주셔서 감사합니다.
