### ISSUE TITLE
how to show Alexander?

### ISSUE THREAD

**Issue by YuleXiv** [Soreepeong/XivAlexander#156]
When I have already "Hidden" the alexander window, how do I bring it back up? I cannot find it anywhere

**Comment by Soreepeong** [comment]
See if a gear icon is on task bar's notification area (look for a tray icon).
![image](https://user-images.githubusercontent.com/3614868/134799137-43a16f0d-1fd1-418a-92d5-084f6aab9edd.png)

**Comment by YuleXiv** [comment]
> 
> 
> See if a gear icon is on task bar's notification area (look for a tray icon).
> ![image](https://user-images.githubusercontent.com/3614868/134799137-43a16f0d-1fd1-418a-92d5-084f6aab9edd.png)

feel silly now xD thanks very much
