### ISSUE TITLE
Chinese Client 5.55 Release Opcode Configuration

### ISSUE THREAD

**Issue by Cherryhy** [Soreepeong/XivAlexander#157]
{
	"C2S_ActionRequest": "0x00db",
	"C2S_ActionRequestGroundTargeted": "0x0140",
	"S2C_ActionEffect01": "0x006e",
	"S2C_ActionEffect08": "0x03c0",
	"S2C_ActionEffect16": "0x00d2",
	"S2C_ActionEffect24": "0x0297",
	"S2C_ActionEffect32": "0x01f1",
	"S2C_ActorCast": "0x00ef",
	"S2C_ActorControl": "0x01d8",
	"S2C_ActorControlSelf": "0x0354",
	"S2C_AddStatusEffect": "0x0315",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

**Comment by MnFeN** [comment]
Here are my results:

game.CN.2021.09.17.0000.0000.json

{
	"C2S_ActionRequest": "0x0140",
	"C2S_ActionRequestGroundTargeted": "0x035b",
	"S2C_ActionEffect01": "0x006e",
	"S2C_ActionEffect08": "0x03c0",
	"S2C_ActionEffect16": "0x00d2",
	"S2C_ActionEffect24": "0x0297",
	"S2C_ActionEffect32": "0x01f1",
	"S2C_ActorCast": "0x00ef",
	"S2C_ActorControl": "0x01d8",
	"S2C_ActorControlSelf": "0x0354",
	"S2C_AddStatusEffect": "0x0315",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

The first two are different and I think you might made a mistake:
> 1028: C2S_ActionRequest/GroundTargeted(0x0140): actionId=0e21 sequence=0020 (重斩 / Hard Slash)
> 1028: C2S_ActionRequest/GroundTargeted(0x035b): actionId=0e37 sequence=0021 (腐秽大地 / Salted Earth)

**Comment by dingma0720** [comment]
![2021-09-28 230103](https://user-images.githubusercontent.com/91583831/135201199-5b359ae8-6804-4de5-9e9e-700b4f6af968.png)
Dose anyone have this issue?

**Comment by dingma0720** [comment]
Does anyone have this issue?
![2021-09-28 230103](https://user-images.githubusercontent.com/91583831/135201419-15681d16-dcb8-4ad8-8a10-f0a35c22a10a.png)

**Comment by Cherryhy** [comment]
Yes MnFeN opcode is correct. Use this.
{
"C2S_ActionRequest": "0x0140",
"C2S_ActionRequestGroundTargeted": "0x035b",
"S2C_ActionEffect01": "0x006e",
"S2C_ActionEffect08": "0x03c0",
"S2C_ActionEffect16": "0x00d2",
"S2C_ActionEffect24": "0x0297",
"S2C_ActionEffect32": "0x01f1",
"S2C_ActorCast": "0x00ef",
"S2C_ActorControl": "0x01d8",
"S2C_ActorControlSelf": "0x0354",
"S2C_AddStatusEffect": "0x0315",
"Server_IpRange": "0.0.0.0/0",
"Server_PortRange": "1-65535"
}

My software have some setup issue, can't detect and find opcode C2S_ActionRequest and C2S_ActionRequestGroundTargeted.
But now when change the setup and i use 
1028: C2S_ActionRequest/GroundTargeted(0x0140): actionId=0e21 sequence=0020 (重斩 / Hard Slash)
1028: C2S_ActionRequest/GroundTargeted(0x035b): actionId=0e37 sequence=0021 (腐秽大地 / Salted Earth)
then get the same result. Thank you MnFeN.

**Comment by Soreepeong** [comment]
Thank you! I've reflected the opcodes into new release.

@dingma0720 Try downloading the newest version I've just updated, and create a new issue with the more detailed error message which should show up with the new release: https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.8.23
