### ISSUE TITLE
Game crashes when I click on keybind menu option in game

### ISSUE THREAD

**Issue by Racrido** [Soreepeong/XivAlexander#158]
![XIVAlexanderBug](https://user-images.githubusercontent.com/78163711/135174856-98caba13-36c5-406b-b7b4-2e87f36182cb.PNG)

Game crashes when I click on the keybind menu option in game. Removing both the xivalexander .dll files from the game folder and starting the game fixed this, but adding the files back still gave me the same problem.

**Comment by Soreepeong** [comment]
Can reproduce when I have EXDF Transformation Rules and/or Additional Game Root Directories enabled. Did you have those options enabled?

**Comment by Soreepeong** [comment]
This should be fixed now; check it out: https://github.com/Soreepeong/XivAlexander/releases

**Comment by Racrido** [comment]
Yes I had EXDF Transformation Rules enabled when the game crashed. Sorry for the late reply.

**Comment by Soreepeong** [comment]
Let me know if XivAlexander doesn't rebuild string table automatically after you update; if it doesn't, delete `%AppData%\XivAlexander\Cached\`.

**Comment by Racrido** [comment]
It was able to rebuild the string table automatically after updating it. However I'm still getting the same issue when I press the keybind system menu option it gives the same error. Removing all the EXDF Text Transformation files and restarting the game worked, but adding it back gave me the same problem.

**Comment by Soreepeong** [comment]
Can you share your whole runtime configuration, accessible from Configure menu? Mine is as following, and I can open keybind window without errors.

* Is the error exactly the same?
* What happens if you launch the game, after deleting `Cached` folder completely?

```json
{
	"C:\\Program Files (x86)\\SquareEnix\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv_dx11.exe": {
		"AdditionalGameResourceFileEntryRootDirectories": [],
		"AdditionalSqpackRootDirectories": [],
		"AdditionalTexToolsModPackSearchDirectories": [],
		"AlwaysOnTop": false,
		"AlwaysOnTop_GameMainWindow": false,
		"AlwaysOnTop_XivAlexLogWindow": false,
		"AlwaysOnTop_XivAlexMainWindow": true,
		"ChainLoadPath_d3d11": [],
		"ChainLoadPath_d3d9": [],
		"ChainLoadPath_dinput8": [],
		"ChainLoadPath_dxgi": [],
		"ExcelTransformConfigFiles": [
			"C:\\Users\\SP\\AppData\\Roaming\\XivAlexander\\ExcelTransformConfig\\EnglishWithJapanese.json"
		],
		"FallbackLanguagePriority": [],
		"HighLatencyMitigationMode": "SimulateNormalizedRttAndLatency",
		"Language": "SystemDefault",
		"LogAllDataFileRead": false,
		"OverrideFontConfig": "",
		"ReducePacketDelay": true,
		"ResourceLanguageOverride": "English",
		"ShowControlWindow": true,
		"ShowLoggingWindow": true,
		"TakeOverAllAddresses": false,
		"TakeOverAllPorts": false,
		"TakeOverLoopback": false,
		"TakeOverPrivateAddresses": false,
		"UseAllIpcMessageLogger": false,
		"UseDefaultGameResourceFileEntryRootDirectory": true,
		"UseDefaultTexToolsModPackSearchDirectory": true,
		"UseEarlyPenalty": false,
		"UseEffectApplicationDelayLogger": false,
		"UseHashTrackerKeyLogging": false,
		"UseHighLatencyMitigation": true,
		"UseHighLatencyMitigationLogging": false,
		"UseHighLatencyMitigationPreviewMode": false,
		"UseModding": true,
		"UseOpcodeFinder": false,
		"VoiceResourceLanguageOverride": "English"
	}
}
```

**Comment by Racrido** [comment]
I deleted the cached file and replaced my d3d11.dll file. I did forget to run through the install.bat file and that fixed it. 

Thanks, sorry for the trouble.
