### ISSUE TITLE
Can't find XivAlexanderLoader.exe

### ISSUE THREAD

**Issue by Rhaenotz** [Soreepeong/XivAlexander#16]
I can't find XivAlexanderLoader.exe in the folder, are you sure the exe is still there? Or do I need to execute the software another way?

**Comment by Soreepeong** [comment]
You might want to check if your antivirus software is on silent mode.

![image](https://user-images.githubusercontent.com/3614868/107997821-19928400-7027-11eb-8f26-64f44fd5ba44.png)
