### ISSUE TITLE
can't boot the game

### ISSUE THREAD

**Issue by vloslain** [Soreepeong/XivAlexander#162]
when I try to boot the game with play button, it shows alexanders window and game window few second 
then both of them disappears.
After uninstalling alexander game worked well.
Tried turning off window defender, re-installing game.
Don't know how to fix it.

**Comment by Soreepeong** [comment]
Try this one at here: https://github.com/Soreepeong/XivAlexander/issues/161#issuecomment-933263637

Also, as this probably is the same issue with the other one (#161), closing as duplicate for now. Please add to the other issue if you have anything to attach.
