### ISSUE TITLE
Can I view only one language?

### ISSUE THREAD

**Issue by vloslain** [Soreepeong/XivAlexander#163]
I don't know where to write it cause I haven't use githerb so I'm writing it here.
The past problem has been solved. thanks to you. also thanks for quick response.
This is just a suggestion. I speak Korean. But I'm playing a global server.
Your program is perfect, but there's one more thing I'd like to ask you about.
Being able to view both languages at the same time is very very convenient, but I wish there was an option to view only one language.
I don't know if it can be realized because I don't know anything about programming, but I'd be really happy if you could check it out.
thank you!

**Comment by Soreepeong** [comment]
Turn off EXDF transformation rules, and pick a language from "Force display language". Keep "Additional game root directories" settings, and you're good to go.
