### ISSUE TITLE
Release v1.14.8.26 fails to verify files

### ISSUE THREAD

**Issue by herrhuml** [Soreepeong/XivAlexander#164]
I've tried the v1.14.8.25_TEST3 version posted in #161 in hopes of fixing the issue and it works. The latest release however throws an error "failed to verify some or all of the following files". The dlls show up as v1.14.8.25 and so does the error popup window name.

![XivAlexanderLoader64_RWxP04nni4](https://user-images.githubusercontent.com/21083836/135840438-368c774a-c89b-4ce9-b970-c5f00dcd948c.png)

**Comment by Kanteron** [comment]
I also have the same problem.

**Comment by Soreepeong** [comment]
Try again. I've put the wrong files into the zip.

**Comment by herrhuml** [comment]
Alright, now it works, thanks.
