### ISSUE TITLE
Unable to do quest which require text input after applying EnglishWithJapanese.json

### ISSUE THREAD

**Issue by AkiyoAratemuso** [Soreepeong/XivAlexander#165]
After applying EnglishWithJapanese.json, the quest Pride-and-Seek which requires /say input "Beaver" no longer works.

Including the Japanese input in brackets doesn't work either. I'd assume the string check for the trigger is broken from the mod.

**Comment by Soreepeong** [comment]
That is expected at the moment, since you can't type newline(enter key) into chat box. It's probably fixable, but figuring out which string table contains the texts for these kind of quest steps will be a chore.

**Comment by Soreepeong** [comment]
Try the new release at https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.8.27 .

Make sure you clear the previous EXDF transform config file list, and add new ones.

**Comment by AkiyoAratemuso** [comment]
I'll give it a try, thank you very much for the quick fix. Just need RNG to give me a /say based quest.

**Comment by AkiyoAratemuso** [comment]
/s ビーバー and /s Beaver and /s beaver still doesn't work with Pride-and-Seek with the latest update

**Comment by AkiyoAratemuso** [comment]
> 
> 
> Just to check: you did update-install to the new version, and used `EnglishWithJapanese_SayQuestEnglish.json`? Did the game restart with a progress window?

Apologies, I've made a mistake in the installation process then. I'll re-verify next time. Sorry for the bad feedback!

**Comment by AkiyoAratemuso** [comment]
Warm regards. I'm here to report that this issue occurred again in Endwalker content. I assume this is because the SayQuest json has not been updated for Endwalker content, for obvious reasons.

I thought I'd reopen this issue just in case other users run into this. By my assumption, it should fix itself when @Soreepeong rerun the tools used to generate the files.

The quest name tested is "最良の貢献　Their Greatest Contribution". The keywords are "頼みがある I have a favor to ask".
Screenshot omitted due to potential spoiler. Will provide if requested.

**Comment by CharonM72** [comment]
As a workaround you can probably complete the quest by saying "頼みがある (I have a favor to ask)" in the chat (or whatever language combination you use) exactly how the prompt tells you to say it. Or, restart the game without text transformations.
I don't know how Soreepeong handles generating the exceptions but they're all listed in the end portion of the transforms json (if you want to add it yourself or something)

**Comment by AkiyoAratemuso** [comment]
> As a workaround you can probably complete the quest by saying "頼みがある (I have a favor to ask)" in the chat (or whatever language combination you use) exactly how the prompt tells you to say it. Or, restart the game without text transformations. I don't know how Soreepeong handles generating the exceptions but they're all listed in the end portion of the transforms json (if you want to add it yourself or something)

Its a line break/new line issue, not a replaced language issue. I've tried inputting both language.

**Comment by CharonM72** [comment]
Yeah I just tested it and indeed no combination seems to work. The only workaround would be to load the game without any transformations (or find the line in the game files and manually add an exception).

**Comment by Soreepeong** [comment]
This should have been a new issue, but anyway, I've updated the files in https://github.com/Soreepeong/XivAlexander/tree/main/StaticData/ExcelTransformConfig to reflect EW /say quests.
