### ISSUE TITLE
If i  set up Chinese fonts to International server will cause garbled.

### ISSUE THREAD

**Issue by CNLenoli** [Soreepeong/XivAlexander#167]
The Chinese font library is missing on the international server client. Direct use of Additional Game Root Directories and set up fonts will cause garble
![)GWVLF{$8VNZ%0P5XE}Z@FT](https://user-images.githubusercontent.com/28130440/136385808-d0445489-d09f-4e5c-9a55-8cbd05cf64d5.jpg)
d.

**Comment by CNLenoli** [comment]
yeah, i edit the game installation in Mix.JpCn.json. and i also setup the fonts SourceHanSansSC to my computer.
![image](https://user-images.githubusercontent.com/28130440/136477498-4db33f13-0eb0-4f92-82db-be6f2f97345b.png)

**Comment by Soreepeong** [comment]
The part you've taken screenshot of looks correct.
* See if files exist in `%APPDATA%/XivAlexander/Cached/JP/ffxiv/000000`
* Can you export log from logging window, and upload it with the whole Runtime Configuration?

**Comment by CNLenoli** [comment]
[logs.log](https://github.com/Soreepeong/XivAlexander/files/7307588/logs.log)
here are the logs

**Comment by CNLenoli** [comment]
i have searched there are nothing in %APPDATA%/XivAlexander/Cached/JP/ffxiv/000000
![image](https://user-images.githubusercontent.com/28130440/136479204-0655104b-0b3e-4c1b-abca-1ffcc38ecbee.png)

**Comment by CNLenoli** [comment]
thanks,I will test it with the latest version after your reply.

**Comment by CNLenoli** [comment]
i love your work! thanks

**Comment by CNLenoli** [comment]
Got it~ got it. It should be the reason that my Chinese game client is not updated.This software works very smoothly.Thanks for your work.
