### ISSUE TITLE
1.14.8.30: Path is not a directory

### ISSUE THREAD

**Issue by mousseng** [Soreepeong/XivAlexander#168]
Hello, the most recent version appears to have introduced an issue for some users.

![image](https://user-images.githubusercontent.com/8106757/136636905-5c60029e-773d-49ea-9fdd-8e363d823914.png)

Versions `1.14.8.24` and `1.14.8.28` didn't exhibit this behavior. I haven't debugged it myself, but there appears to be a change in what is now `Utils::Win32::TranslatePath()` - from
```
pathbuf = (relativeTo.empty() ? Dll::Module().PathOf().parent_path() : relativeTo) / pathbuf;
```

to

```
pathbuf = relativeTo / pathbuf;
```

As I said, haven't debugged it myself so this may be unrelated, but it _looked_ like the only change related to `EnsureDirectory()` (where this error appears to come from).

Let me know if you need more information.

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivAlexander/commit/2f28fdc778585b90c7248d8e3b55f46a3f289bcd#diff-bd14c56fca14cb812fdb4583607055b1ed8ae1860265fdc1ec7ef898c1191bd0

Yeah, this was it. It should be fixed now.
