### ISSUE TITLE
이게 무슨뜻이죠?

### ISSUE THREAD

**Issue by 39Mania** [Soreepeong/XivAlexander#170]
![오류](https://user-images.githubusercontent.com/92626777/137582022-c76e89f6-556c-4031-926f-84aeab9d76c7.png)
이미지파일이없다는게 무슨의미인지모르겟네요. 모드를 일단 다 지워야하나요?

**Comment by Soreepeong** [comment]
혹시 기존 dinput8.dll 교체하는 fk.7z라는 이름으로 배포되는 한글표시모드 쓰고 계셨나요? 잠시 그 파일(dinput8.dll) 이름을 dinput8.dll.old 등으로 바꾸고 한번 실행해보시겠어요?

**Comment by 39Mania** [comment]
아하 이게문제엿군요 다운한뒤 다시 이름을 바꿔야하나요?
