### ISSUE TITLE
폰트오류 해결방법이 궁금합니다!

### ISSUE THREAD

**Issue by TovK12** [Soreepeong/XivAlexander#171]
![제목 없음](https://user-images.githubusercontent.com/92634467/137588544-f9612efe-9817-4a29-9dd5-816292961f1b.png)

폰트 설치하라는걸로 설치완료하고 실행하면 위와같은 오류가 발생합니다

**Comment by Soreepeong** [comment]
`Mix.JpKr.json` 이용하고 계신다면, `추가 게임 루트 폴더`에 한썹 폴더 먼저 추가하셨나요?

**Comment by Soreepeong** [comment]
네, `Mix.`로 시작하는 건 한썹/중썹/글썹 섞어서 이용하는 것이기 때문에, 만약 한썹이 없다면 `SourceHanSansK.json` 으로 이용해 보세요.

**Comment by TovK12** [comment]
답변감사합니다. 알려주신방법으로 해보니 실행은되는데 한글채팅 패치가 적용이 안되네요 . 혹시 다른방법이 있을까요?

**Comment by Soreepeong** [comment]
기존 dinput8.dll 파일이 있었다면 지우셨나요? 모딩 메뉴에서 분명히 활성화하셨다면, 메인 창에서 `설정 > 프로그램 설정 변경`에서 뜨는 내용을 올려주시겠어요?

**Comment by Soreepeong** [comment]
![image](https://user-images.githubusercontent.com/3614868/137589260-fba5fb96-198b-4b13-8550-02c61f40c5d4.png)

이 항목이 켜져 있는지 다시 한번 확인하고 재시작 메뉴를 통해 재시작해보시겠어요? 설정 파일 내용을 보니 그 설정이 꺼져 있는 것으로 나오는데 (`"UseModding": false,`) 분명 켜져 있는 상태였다면 추가 정보가 필요할 것 같습니다.

**Comment by TovK12** [comment]
아아 감사합니다 ㅠㅠ 제가 컴맹이라 저런 설정이있었군요 천천히 읽어봤어야했는데 ㅠㅠ
질문할곳이없어서 이슈에다 질문했는데 친절하게 답변해주셔서 감사합니다!!!!

**Comment by TovK12** [comment]
해결되었습니다 감사합니다!!
