### ISSUE TITLE
Secondary language for duty finder

### ISSUE THREAD

**Issue by CharonM72** [Soreepeong/XivAlexander#173]
Hello,

I just found out that I can use your program to add Japanese to my English text and I absolutely LOVE it.

However, I noticed that the duty finder does not show the Japanese names for the duties. I was wondering if it is possible to edit the EnglishWithJapanese_SayQuestJapanese.json to display Japanese duty names?

Thanks so much!

![image](https://user-images.githubusercontent.com/1299220/137847980-af88ba4b-0910-439a-b4b8-8a7aefaad34d.png)

**Comment by Soreepeong** [comment]
You can use [FFXIV Explorer](https://github.com/goaaats/ffxiv-explorer-fork/releases), open up `game/sqpack/ffxiv/0a0000.win32.index`, and try to figure out which file contains the duty names. There were some reasons that I gave up trying to do that which I don't exactly remember.

**Comment by Soreepeong** [comment]
Actually, it works fine:

![image](https://user-images.githubusercontent.com/3614868/137848875-990b3cf4-9ee3-492a-a624-e671330684a4.png)


Add the following to `targetGroups.object`.
```json
      "^ContentFinderCondition$": [37, 38],
      "^ContentUiCategory$": [0],
```
* `ContentFinderCondition` contains duty names (`Sastasha (天然要塞 サスタシャ浸食洞)`)
* `ContentUiCategory` contains category names (`Trials (Shadowbringers)`)

**Comment by CharonM72** [comment]
This works perfectly! I don't know how you managed to do that so quickly. Thank you!
