### ISSUE TITLE
EXDF transformations when booting from XIVLauncher?

### ISSUE THREAD

**Issue by CharonM72** [Soreepeong/XivAlexander#175]
I noticed that EXDF transformations only load when XIVAlexander itself loads FFXIV (by restarting it through XIVAlexander). But when it does that, it does not load Dalamud injections. On top of that, it is inconvenient to launch FFXIV via XIVLauncher and then have to manually restart it and have XIVAlexander re-apply the transformations every time.

So, my question is, is there a way to launch via XIVLauncher (which also launches all my other tools), have the transformations applied, and still get Dalamud injected? or is that impossible?

**Comment by Soreepeong** [comment]
Does installing xivalex via loader not work in your case?

**Comment by CharonM72** [comment]
Oh, I have been just loading it alongside FFXIV all this time via XIVLauncher. I completely didn't notice that it can be installed to load with FFXIV. That fixes it! Thanks again!
