### ISSUE TITLE
ACT question

### ISSUE THREAD

**Issue by CharonM72** [Soreepeong/XivAlexander#176]
In the wiki, it says:

> FFXIV plugin for Advanced Combat Tracker will stop combining actions done by pets(Carbuncles, Egis, and Faeries) because their names will show up in the form of Eos (フェアリー・エオス) (Firstname Lastname) instead of just Eos (Firstname Lastname).
> You can use Advanced Combat Tracker > Option > Data Correction > Combatant Rename to fix this.

Does this renaming have to be done for every character separately, or is there a way to make ACT correct this for all characters that have pets? It doesn't seem like just correcting eg. "Ruby Carbuncle (カーバンクル・ルビー)" to "Ruby Carbuncle" works.

**Comment by Soreepeong** [comment]
Honestly, this was nothing more than a suggestion I've received, and then checked that the menu exists.

Immediate solution would be removing the lines containing `BNpcName` and `EObjName`.

For actual fix, it might be possible to hook onto Advanced Combat Tracker process and hijack what FFXIV plugin writes to the log file.

**Comment by CharonM72** [comment]
Yeah I noticed as well that RaidBoss (usually) doesn't work either, presumably because it no longer recognizes the names of attacks. 

Not only that, but DPS parsing results seem... wrong. I've been in a few high-end raids where one character did twice the DPS of others. No idea why...

I do like to see NPC names in both languages though; are pets in the same category as other NPCs? I don't imagine there's any way to exclude them?

I'll play around with the json a bit and see what happens.

**Comment by CharonM72** [comment]
Actually removing `BNpcName` and `EObjName` did only remove the pet names, NPC names are still translated. Excellent.

**Comment by CharonM72** [comment]
Here's a random question - the transform does translate all the songs in the Orchestrion. But the Orchestrion Dalamud plugin does not have the translations. Is that because it's a different text category, or is this just an issue with the Orchestrion plugin?

Sorry if this is a bit outside the scope of XIVAlexander.

**Comment by CharonM72** [comment]
Hello again.

If I want to comment out a line in the Excel Transform rules file, can I do it like this?

![image](https://user-images.githubusercontent.com/1299220/144675974-53507308-8c0e-4565-ad27-58152fb89411.png)

Also, the default file should probably exclude pets, just because it messes up ACT merging the damage/healing. That said, I talked with the ACT devs and it's possible they might change the way it reads pets to be language-agnostic. So we'll see what happens.
