### ISSUE TITLE
Matching game path with special characters

### ISSUE THREAD

**Issue by hyskylord** [Soreepeong/XivAlexander#18]
It seems like the config is supposed to support any UTF-8 characters, but when the game path contains special characters, the plugin reads the game path with pure lower case letters, but saves it with some capital case. It generates a new config every time I opened the plugin because they cannot match.

**Comment by Soreepeong** [comment]
That doesn't sound right. This program will query the path of game executable and save it as a constant, so it shouldn't be confusing capitalization problems when loading or saving configuration. It doesn't try to "correct" capitalization too - it saves and loads as what the system reports. 

Can you post the installation path of the game? I'll test it out later on today anyway.

**Comment by hyskylord** [comment]
@Soreepeong 
I just made some more test myself. It turns out the problem is because the game path was read differently. 
In my case when I open the plugin it will give either
 Process found: "C:\\Program Files (x86)\\盛大游戏\\最终幻想XIV\\game\\ffxiv_dx11.exe", or
 Process found: "c:\\program files (x86)\\盛大游戏\\最终幻想xiv\\game\\ffxiv_dx11.exe".
I solved it by configuring both of them, but still looks strange.

**Comment by Soreepeong** [comment]
Oh, I guess the executable path reported follows the capitalization used when executing the game? I'll make the configuration file to be case insensitive.

**Comment by Soreepeong** [comment]
This should be fixed in fbbdc83332bf9d235be74ef2e1f2a0e77cc9b056. I'll release the updated program when opcodes for game hotfixes are ready.
