### ISSUE TITLE
Installation Issue - Subscription Renewal

### ISSUE THREAD

**Issue by zedblanco** [Soreepeong/XivAlexander#180]
I have installed XIValexander, on each of the 3 installation options separately, for my steam version of the game, but when I log-in on the launcher is automatically takes me to the screen that shows as if I dont have a service account of subscription.

"This service account does not have a valid FINAL FANTASY XIV license for this platform or your subscription has expired.
To register a license, please visit the FINAL FANTASY XIV: Mog Station (https://sqez.to/Msp).

For further help with this error message, please check this FAQ (https://sqex.to/ffxivnovalid)."

Uninstalling XIValexander and removing the .json files when prompted, then restarting my XIV launcher allows me to login as normal. 

Thanks

**Comment by harrietrc** [comment]
I have the same issue and could only bypass it by installing [FFXIVQuickLauncher](https://github.com/goatcorp/FFXIVQuickLauncher), in combination with the 'Load once' option for XIVAlexander.

**Comment by erikbernardo** [comment]
> I have installed XIValexander, on each of the 3 installation options separately, for my steam version of the game, but when I log-in on the launcher is automatically takes me to the screen that shows as if I dont have a service account of subscription.
> 
> "This service account does not have a valid FINAL FANTASY XIV license for this platform or your subscription has expired. To register a license, please visit the FINAL FANTASY XIV: Mog Station (https://sqez.to/Msp).
> 
> For further help with this error message, please check this FAQ (https://sqex.to/ffxivnovalid)."
> 
> Uninstalling XIValexander and removing the .json files when prompted, then restarting my XIV launcher allows me to login as normal.
> 
> Thanks

what version of game you have? standard or steam?

**Comment by Crismoo** [comment]
Install, close the loader, open the game sign in and then open the loader load into running game, that solved it for me

**Comment by 2beyy** [comment]
> > I have installed XIValexander, on each of the 3 installation options separately, for my steam version of the game, but when I log-in on the launcher is automatically takes me to the screen that shows as if I dont have a service account of subscription.
> > "This service account does not have a valid FINAL FANTASY XIV license for this platform or your subscription has expired. To register a license, please visit the FINAL FANTASY XIV: Mog Station (https://sqez.to/Msp).
> > For further help with this error message, please check this FAQ (https://sqex.to/ffxivnovalid)."
> > Uninstalling XIValexander and removing the .json files when prompted, then restarting my XIV launcher allows me to login as normal.
> > Thanks
> 
> what version of game you have? standard or steam?

Can you tell me how you were able to uninstall Alexander XIV? Deleting the files doesnt seem to do the trick
