### ISSUE TITLE
Korean Sever 5.55 Patch

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#181]
Hello, will the program temporarily become unavailable for 5.55 patch for KR server on November 2nd?

Thank you!

**Comment by CharonM72** [comment]
Actually, I'm also curious if the Endwalker release (outside CN/KR) will affect XIVAlex. Given how it works, I doubt it, but I don't know...

**Comment by Soreepeong** [comment]
I don't have a subscription to Korean servers at the moment, and I'm not thinking to resub anytime soon.

**Comment by justin767** [comment]
> I don't have a subscription to Korean servers at the moment, and I'm not thinking to resub anytime soon.

Thank you, so we'll have to find out the opcodes by ourselves right..?

**Comment by justin767** [comment]
> I don't have a subscription to Korean servers at the moment, and I'm not thinking to resub anytime soon.

Thank you,

So from now on we'll have to find the opcodes ourselves right..?

Is there a way to verify and check if the self-found opcodes are correct and the program is functioning? Other than just executing skills in-game, is there a way to check it through examining the log and etc.? Thank You.

**Comment by Fprh5367** [comment]
Has anyone heard back about this yet? Mine doesn't work after today's patch RIP
