### ISSUE TITLE
Turns the Peacelover's Shirt invisible for females

### ISSUE THREAD

**Issue by Lightzy** [Soreepeong/XivAlexander#182]
Both myself and a friend have had an issue where the Peacelover's Shirt is invisible on females - the torso is completely invisible, and when trying on the piece over another glam, the game doesn't load a new model at all and leaves it as the previous gear's model. When that model is the first to be "loaded" (selected for the try on feature, or loading into the instance with it glammed on), the character appears torsoless.

Friend had this issue on a completely modless install, I myself removed all mods and even went as far as reinstalling the game to "fix" it - which only worked until I installed alexander onto the fresh install.

Have uninstalled and reinstalled several times to be completely positive, and as soon as Alexander is removed and the game rebooted, the top shows up completely fine. When it's installed again, it's visible until the game is booted with Modding > Enable turned on - appears fine if the game is booted with Alexander disabled. Enabling and reinstancing has no affect, just as disabling and reinstancing doesn't make the top show up if it's already invisible.

I'm assuming this has coincided with the addition of the ability to install TexTools Modpacks. I was using version 1.14.8.31 since 14/10 until today, when I updated to 1.14.8.35 and the issue persists. Unsure which version friend is running.

Have not found a similar issue with any other gear pieces as of yet.

![](https://cdn.discordapp.com/attachments/882326144702115840/903674957874204702/unknown.png)

**Comment by CharonM72** [comment]
I am having exactly the same issue.

**Comment by Soreepeong** [comment]
[XivAlexander_353cf75.zip](https://github.com/Soreepeong/XivAlexander/files/7499590/XivAlexander_353cf75.zip)

Can you test whether this works? I've confirmed that it happened on my side too, and did check that with this fix the item is properly visible.

**Comment by Lightzy** [comment]
Hmm. It does seem to make the Peacelover's Shirt visible again, but I've encountered a new issue.

This version seems to be incompatible with XIVlauncher and its plugins. Whenever I run the game with Alexander enabled, the game doesn't load any of the plugins I have installed, and the game crashes to desktop whenever I try to open the Dalamud settings or (curiously) press the Exit Game button. It seems to be prompting the game to crash on startup occasionally, about the time I assume it normally loads in said plugins.

Much like the invisible shirt issue from before, they load fine if Alexander isn't installed, or the game is booted without it enabled (such as the first time after it's hooked to the .exe)

Tried uninstalling and reinstalling a few times, as well as deleting and re-extracting the folder in case it's user error, but it seems consistent.

Thanks for looking into this!

**Comment by Lightzy** [comment]
Oops, wrong button!

**Comment by Soreepeong** [comment]
Personally I never encountered any conflicts with Dalamud, so I can't test it myself, but try the following.

There should be an option on FFXIVQuickLauncher which delays Dalamud load. Try extending the delay, so that it doesn't try to load while XivAlexander is starting up. Otherwise, try disabling Dalamud or launch the game via official launcher, and then run Dalamud via `%APPDATA%\Roaming\XIVLauncher\addon\Hooks\dev\Dalamud.Injector.exe` when the game shows up logos. 

If it indeed fixes the problem, I believe that there are stuff I can implement so that Dalamud does not attempt to inject while XivAlexander is loading.

**Comment by Lightzy** [comment]
It did manage to load plugins once last night after I wrote up the previous comment, something like 1 in 15 attempts all told. (was at 0ms delay)

Added 3000ms delay, relogged three times and 2/3 loaded plugins just fine. Upped it to 5000ms and all three attempts loaded fine.

So, looks like it is indeed something about them trying to load up at the same time! I wonder if it was causing problems for me because I know my computer isn't the fastest out there.

**Comment by Soreepeong** [comment]
[XivAlexander_61d4c57.zip](https://github.com/Soreepeong/XivAlexander/files/7508902/XivAlexander_61d4c57.zip)

This should prevent Dalamud from attempting to load before the game window shows up. Try this one by removing Dalamud delay-load from FFXIVQuickLauncher.

**Comment by Lightzy** [comment]
Yep, seems to be working on my end!

Thanks again!

**Comment by Soreepeong** [comment]
I'll close this issue when I make a next full release. Just keeping it open until then!

**Comment by CharonM72** [comment]
I'm still having this issue, with the latest version of XIVAlex. Is there something I'm forgetting to do?

**Comment by Lightzy** [comment]
I updated to v1.14.8.37 the other day and can confirm, the shirt has turned invisible again.

**Comment by Soreepeong** [comment]
This will be fixed in next release. Also, it should not have worked back in previous release, but I have no idea why did it work.
