### ISSUE TITLE
Multiple choice modpacks aren't multiple choice

### ISSUE THREAD

**Issue by Lunatory** [Soreepeong/XivAlexander#186]
Installing a modpack with a multiple choice wizard results in only being able to select one option at a time.

I've tried making a new advanced modpack based on the original and importing that, that didn't fix the issue.
I've tried manually adjusting the choices.json file, but it doesn't get applied and making any changes in Alex reverts the file to it's single selection option.

**Comment by Soreepeong** [comment]
It is currently unimplemented since from a cursory search from XMA I couldn't find one with multiple choices. Can you give me a link to one?

**Comment by Lunatory** [comment]
https://www.xivmodarchive.com/modid/34443 here's the one I tried using

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivAlexander/files/7508902/XivAlexander_61d4c57.zip

Try this one, and see if it works as you would expect.
