### ISSUE TITLE
Conflict between XIVAlexander and Bard Music Player/Error when unloading

### ISSUE THREAD

**Issue by KiraSilversoul** [Soreepeong/XivAlexander#187]
So first off XIVA seems to prevent BMP from playing. When attempting to workaround the issue and simply turn XIVA off temporarily, I hit the attached error message. I run numerous mods, but I disabled them all and still get this error.
![image](https://user-images.githubusercontent.com/93623529/139959100-d50238f0-c3cb-4b7d-928f-f7ba966080e9.png)

**Comment by Soreepeong** [comment]
Did you install XivAlexander, or is it from "Load once"? In any case, unloading is done on a chance basis, and is very likely to fail, and the only thing you can do when that message shows up is to restart the game using XivAlexander main window's Restart menu, unticking "Use XivAlexander" option.

**Comment by KiraSilversoul** [comment]
Full installed using the first option"Install XivAlexander as d3d9 and d3d11. " as recommended in install guide.

Is there no way to unhook XIVA even temporarily? I did Restart after unticking "Use XivAlexander" option, but for whatever reason doing so seemed to disable every other mod. I ended up uninstalling XIVA temporarily until a solution can be found.

Bard Music Player is a separate program, fairly common, it allows users to basically jukebox .midi files through the game's performance mode (I presume by automatically inputing the keys via the information from the .midi file). Somewhere along the pipeline, XIVA blocks the input from BMP.

**Comment by Soreepeong** [comment]
https://github.com/BardMusicPlayer/BardMusicPlayer/blob/a8d3e82b0c454207b215a1e13f42d7f1055bab32/BardMusicPlayer.Grunt/GameExtensions.Keys.cs#L37-L39

https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.mainwindowhandle?view=net-5.0

> The main window is the window opened by the process that currently has the focus (the TopLevel form). You must use the Refresh method to refresh the Process object to get the most up to date main window handle if it has changed. In general, because the window handle is cached, use Refresh beforehand to guarantee that you'll retrieve the current handle.
>
> A process has a main window associated with it only if the process has a graphical interface. If the associated process does not have a main window, the MainWindowHandle value is zero. The value is also zero for processes that have been hidden, that is, processes that are not visible in the taskbar. This can be the case for processes that appear as icons in the notification area, at the far right of the taskbar.

Because XivAlexander shows a window inside the game process, it seems that `MainWindowHandle` becomes XivAlexander window if you have a XivAlexander window open when BMP is running. After closing XivAlexander control window (no need to unload), and restaring BMP, it seems that the program works.

**Comment by KiraSilversoul** [comment]
"After closing XivAlexander control window (no need to unload), and restaring BMP, it seems that the program works." Can confirm the same, thanks!

**Comment by MoogleTroupe** [comment]
Well at minimum I can walk the dll list to find if Alexander is loaded, to alert the user about this problem, though it would be preferred if there is a way I can know what handle to send PostMessage/SendMessage, or if there is an api hook exposed to send button presses.

**Comment by Soreepeong** [comment]
@MoogleTroupe

Try using this as a drop-in replacement for `process.MainWindowHandle` as `TryFindGameWindow(process)`. It will pick the game window in particular out of all the windows belonging to the process.

https://github.com/goatcorp/FFXIVQuickLauncher/blob/e96f980fc4440acaf404c505660b85abc7a54250/src/XIVLauncher.Common.Windows/NativeAclFix.cs#L533-L554
