### ISSUE TITLE
Changing Temporal constants for XIV Alexander (edit)

### ISSUE THREAD

**Issue by cringeewaboo1337** [Soreepeong/XivAlexander#188]
Hi, 
there are 3 different modes for the XIVAlexander. Could you please briefly summarize them and which one to use to simulate double weaving without clipping?

Thanks

**Comment by FloppyAl** [comment]
It's under the wiki.

**Comment by cringeewaboo1337** [comment]
How do you change temporal constants? I'd like to try that.

**Comment by FloppyAl** [comment]
That's cheating and something not supported by the developer.

**Comment by Soreepeong** [comment]
Related constants are in https://github.com/Soreepeong/XivAlexander/blob/main/XivAlexander/App_Feature_AnimationLockLatencyHandler.cpp
