### ISSUE TITLE
A couple of questions.

### ISSUE THREAD

**Issue by Battler624** [Soreepeong/XivAlexander#189]
Does the region selection in XivAlexander matter? (I am playing from middle-east connecting to a NA server).

Is there a way to do load-once automatically (command line?) I dont want to install it completely.

The 3 Modes (Just read the other issue) how can I know which one works best for me? (I average 300 ping which sucks)

**Comment by Soreepeong** [comment]
1. Region apparently only matters for changing screencap file names.
    * Japan: `ffxiv_yyyymmdd_hhiiss_fff.png`
    * NA: `ffxiv_mmddyyyy_hhiiss_fff.png`
    * EU: `ffxiv_ddmmyyyy_hhiiss_fff.png`
2. Try running loader with `-help` for command line arguments. What you want to do can be done with `-a load`.
3. It depends. Just try all 3 and pick your favorite.
