### ISSUE TITLE
Latency response from XIVAlexander higher than actual latency

### ISSUE THREAD

**Issue by Onibus** [Soreepeong/XivAlexander#19]
The logs within XIVAlexander show `KeepAliveResponse` around 100ms average. Both pingplotter and nmap both report around 60ms while, oddly, Windows resource monitor more closely aligns with XIVAlexander. I can't put my finger on why XIVAlexander (and Resource Monitor) report higher latency compared to actual.

![image](https://user-images.githubusercontent.com/6449080/108241125-7ec6a200-7119-11eb-8d9f-bac41977d3b0.png)

**Comment by Soreepeong** [comment]
The server won't send KeepAlive response right away; it'll take time just like all other action requests. Subtracting the actual ping from KeepAlive response delay would let us calculate the duration of server delays, which we can use for ExtraDelay.

**Comment by Onibus** [comment]
Ah, so it's not simply an ICMP response but instead is a processed action much like a skill. In that case, I'll stop thinking of it as ICMP.
