### ISSUE TITLE
CN 5.57 Opcode

### ISSUE THREAD

**Issue by Zrost** [Soreepeong/XivAlexander#191]
```json
{
	"C2S_ActionRequest": "0x0145",
	"C2S_ActionRequestGroundTargeted": "0x0309",
	"S2C_ActionEffect01": "0x032e",
	"S2C_ActionEffect08": "0x020d",
	"S2C_ActionEffect16": "0x00df",
	"S2C_ActionEffect24": "0x018f",
	"S2C_ActionEffect32": "0x00ed",
	"S2C_ActorCast": "0x0116",
	"S2C_ActorControl": "0x00ca",
	"S2C_ActorControlSelf": "0x0245",
	"S2C_AddStatusEffect": "0x02e8",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}
```

First time finding opcode so not pretty sure if it is all correct. Please let me know if I need to correct any mistakes.

**Comment by burden-z** [comment]
it works for me, thx!

**Comment by Soreepeong** [comment]
What's the game version (or the file name of the opcodes file)? Please let me know the file content of `game\ffxivgame.ver` in the game installation directory.

**Comment by OAHaegt** [comment]
It is 2021.10.26.0000.0000 for me.

**Comment by MnFeN** [comment]
Double-checked, all opcodes are correct

**Comment by MnFeN** [comment]
> What's the game version (or the file name of the opcodes file)? Please let me know the file content of `game\ffxivgame.ver` in the game installation directory.

I tried to use the opcode file in the latest patch on the CN client (Windows 10), but it didn't work. I edited Server_IpRange to "0.0.0.0/0" and it worked normally again. I don't understand how this IP range actually affects the program, but I think it might be due to the server migration of MaoXiaoPang on Nov. 4. The LobbyHost is still ffxivlobby07.ff14.sdo.com, but the actual IP might differ from the previous one.

**Comment by Mitsuha-LYB** [comment]
> {
>	"C2S_ActionRequest": "0x02ec",
>	"C2S_ActionRequestGroundTargeted": "0x02ec",
>	"S2C_ActionEffect01": "0x03b1",
>	"S2C_ActionEffect08": "0x01e5",
>	"S2C_ActionEffect16": "0x02d5",
>	"S2C_ActionEffect24": "0x00e1",
>	"S2C_ActionEffect32": "0x00c7",
>	"S2C_ActorCast": "0x013a",
>	"S2C_ActorControl": "0x012e",
>	"S2C_ActorControlSelf": "0x0303",
>	"S2C_EffectResult5": "0x018d",
>	"S2C_EffectResult6": "",
>	"S2C_EffectResult6Basic": "",
>	"Server_IpRange": "0.0.0.0/0",
>	"Server_PortRange": "1-65535"
>}

CN client have updated to version 5.58, I tried to find out the opcode and  not sure if it is all correct, so please point out if there is anything wrong,thx.

**Comment by LHSVincent** [comment]
> 

Does this opcode work for your game?

**Comment by LHSVincent** [comment]
> > {
> > "C2S_ActionRequest": "0x02ec",
> > "C2S_ActionRequestGroundTargeted": "0x02ec",
> > "S2C_ActionEffect01": "0x03b1",
> > "S2C_ActionEffect08": "0x01e5",
> > "S2C_ActionEffect16": "0x02d5",
> > "S2C_ActionEffect24": "0x00e1",
> > "S2C_ActionEffect32": "0x00c7",
> > "S2C_ActorCast": "0x013a",
> > "S2C_ActorControl": "0x012e",
> > "S2C_ActorControlSelf": "0x0303",
> > "S2C_EffectResult5": "0x018d",
> > "S2C_EffectResult6": "",
> > "S2C_EffectResult6Basic": "",
> > "Server_IpRange": "0.0.0.0/0",
> > "Server_PortRange": "1-65535"
> > }
> 
> CN client have updated to version 5.58, I tried to find out the opcode and not sure if it is all correct, so please point out if there is anything wrong,thx.

Does this opcode work for your game? I tried that but it seems not work for me. By the way, I also change the "Server_IpRange" to the value same as 5.57 opcode.

**Comment by 6a0juu** [comment]
> > {
> > "C2S_ActionRequest": "0x02ec",
> > "C2S_ActionRequestGroundTargeted": "0x02ec",
> > "S2C_ActionEffect01": "0x03b1",
> > "S2C_ActionEffect08": "0x01e5",
> > "S2C_ActionEffect16": "0x02d5",
> > "S2C_ActionEffect24": "0x00e1",
> > "S2C_ActionEffect32": "0x00c7",
> > "S2C_ActorCast": "0x013a",
> > "S2C_ActorControl": "0x012e",
> > "S2C_ActorControlSelf": "0x0303",
> > "S2C_EffectResult5": "0x018d",
> > "S2C_EffectResult6": "",
> > "S2C_EffectResult6Basic": "",
> > "Server_IpRange": "0.0.0.0/0",
> > "Server_PortRange": "1-65535"
> > }
> 
> CN client have updated to version 5.58, I tried to find out the opcode and not sure if it is all correct, so please point out if there is anything wrong,thx.

Hello, C2S_ActionRequestGroundTargeted is not correct here. You can use Sacred Soil, Shukuchi, and Hissatsu: Soten to find this opcode as described in the wiki. The following configuration works fine for me. Have a try!  

`{
  "C2S_ActionRequest": "0x02ec",
  "C2S_ActionRequestGroundTargeted": "0x0357",
  "S2C_ActionEffect01": "0x03b1",
  "S2C_ActionEffect08": "0x01e5",
  "S2C_ActionEffect16": "0x02d5",
  "S2C_ActionEffect24": "0x00e1",
  "S2C_ActionEffect32": "0x00c7",
  "S2C_ActorCast": "0x013a",
  "S2C_ActorControl": "0x012e",
  "S2C_ActorControlSelf": "0x0303",
  "S2C_EffectResult5": "0x018d",
  "Server_IpRange": "109.244.0.0/16, 27.221.0.0/16, 119.97.0.0/16, 162.14.0.0/16",
  "Server_PortRange": "1-65535"
}`
