### ISSUE TITLE
Possible cross-compatability issue with Dalmud launcher/plugins

### ISSUE THREAD

**Issue by KiraSilversoul** [Soreepeong/XivAlexander#192]
Dalmud plugins repository and XivAlexander both seem to open their own hooked version of ff14 client. Tried to work around by starting Dalmud launcher after XivAlexander, plugins menu was there but no plugins were working. Clicking the menu caused immediate crash.

Dalmud site: https://goatcorp.github.io/DalamudPlugins/plugins.html

**Comment by Soreepeong** [comment]
Try https://github.com/Soreepeong/XivAlexander/files/7508902/XivAlexander_61d4c57.zip from https://github.com/Soreepeong/XivAlexander/issues/182

It effectively delays Dalamud from loading until the game's main window shows up.

**Comment by KiraSilversoul** [comment]
Ok it is able to be worked around. Looks like as long as XIVA is installed, and then dalmud launches fresh, you can have both running.
