### ISSUE TITLE
Issue doing quests that involve typing in say chat

### ISSUE THREAD

**Issue by Racrido** [Soreepeong/XivAlexander#193]
Any quests that involve typing something in say chat won't work. Unloading XIVAlexander and restarting the game will allow the quest to work properly. 

1. Using EXDF Text Transformation Tool EnglishWithJapanese.json
2. Updated to latest version and doesn't work. 
3. Removing the .json file from the import list and relaunching the game with XIVAlexander still loaded also fixes the issue so it seems limited to using EXDF Text Transformation Tool. Haven't tried it with other .json files.

**Comment by Soreepeong** [comment]
Which quest is it (what are you required to type), and are you using the latest version? Your file name should be named something like `EnglishWithJapanese_SayQuestEnglish.json`. See #165

**Comment by Racrido** [comment]
I updated to the latest version and it was an issue on my end with XIVAlexander loading the old .json file instead of the new one that I had imported. Sorry about that. Thanks for the help.
