### ISSUE TITLE
[Request] Separate latency-mitigation and modding tools

### ISSUE THREAD

**Issue by oorzkws** [Soreepeong/XivAlexander#194]
The project seems to have dual purposes now, would it be possible to split off the latency mitigation portion? Alternatively, build flags to toggle on/off the extra features.

Thanks!

**Comment by Soreepeong** [comment]
I'm not interested in doing that, but you can always make a fork and strip out all the features you don't need. Why do you want to get rid of the other features, though? If you don't enable modding, none of the mod related code will execute at all, minus configuration menu.

**Comment by oorzkws** [comment]
Two things, mainly. The first would be simplifying any troubleshooting as I would know what tools detour what bits ingame. The second is updates, mainly that it becomes necessary to check the notes/commit history for if the part I use needs any update versus the (larger amount of) other features.

**Comment by oorzkws** [comment]
With the advent of NoClippy, this feels a lot less important - having the logic happen within the game solves the separation issue.
