### ISSUE TITLE
after update v1.14.8.37 cannot apply Korean

### ISSUE THREAD

**Issue by vloslain** [Soreepeong/XivAlexander#196]
I was using Korean apply function. However, there was a problem that continued to force close while playing the game today, 
so I checked the update. After updating, a problem occurred. I made the same settings as before, but an error occurred in Alexander and Korean was not applied. The same error occurs even when reverting to the previously used v1.14.8.35 version. I would appreciate it if you could tell me how to solve it.

[XivAlexander_20211113_032259_809.log](https://github.com/Soreepeong/XivAlexander/files/7529676/XivAlexander_20211113_032259_809.log)
[XivAlexander_20211113_030703_887.log](https://github.com/Soreepeong/XivAlexander/files/7529677/XivAlexander_20211113_030703_887.log)
![image](https://user-images.githubusercontent.com/68831657/141524049-674fdaa5-a58d-4904-a3e1-4cb4c0affc20.png)

**Comment by Soreepeong** [comment]
It looks like your Korean installation might be corrupt. But first, try updating to the latest version. And then, see if the file `C:\Program Files (x86)\FINAL FANTASY XIV - KOREA\game\sqpack\ffxiv\0a0000.win32.index` indeed exists. If it does, proceed.

Open PowerShell, type `cd C:\Program Files (x86)\FINAL FANTASY XIV - KOREA\game\sqpack\ffxiv`, Enter, and then type `Get-FileHash -algorithm SHA1 .\0a0000.win32.*`. See if the Hash values match.

```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA1            347471EE605D185A09385F42EA3DCB72FAEF45A6                               C:\Program Files (x86)\FINAL FANTASY XIV - KOREA\game\sqpack\ffxiv\0a0000.win32.dat0
SHA1            0406FAB9B98715D5B8A44F6053FF36E835BF93BD                               C:\Program Files (x86)\FINAL FANTASY XIV - KOREA\game\sqpack\ffxiv\0a0000.win32.index
SHA1            9293E0AD035F9F6368CEF5E76A5999EDCDDC4FE5                               C:\Program Files (x86)\FINAL FANTASY XIV - KOREA\game\sqpack\ffxiv\0a0000.win32.index2
```

**Comment by vloslain** [comment]
I have checked the Korean server update file you mentioned. The most recent update was performed and the file exists properly. The Korean server also runs without problems.
However, I'm not sure what the PowerShell part means. I don't know where to fix it TT

**Comment by vloslain** [comment]
I just reinstalled GB launcher and solved problem. thank you for response!
