### ISSUE TITLE
Loading Alexander into game simply opens the loading window again?

### ISSUE THREAD

**Issue by Azurealistic** [Soreepeong/XivAlexander#197]
This is just something minor I noticed but say I pick the load-once option:

![image](https://user-images.githubusercontent.com/5000092/141605994-b269907c-0ea6-4a30-a509-86bcdd23c611.png)

I get a window like this:

![image](https://user-images.githubusercontent.com/5000092/141606001-4d63efb5-1cbf-415a-8ac1-4fcdcc2d960e.png)

When I click Load XivAlexander, it loads into the game and then opens this second prompt again. I feel like this shouldn't be the default behavior, after I've loaded it I just want to be able to start playing, not face another prompt that says the same thing. 

I'm unsure if this is intended or a bug, either way the ability to disable that pop-up from reoccurring would be nice.

**Comment by Soreepeong** [comment]
It probably is true that people will usually have only one instance of the game running. I'll make it close itself of there was only one game process running.

**Comment by retaker** [comment]
@Soreepeong There's a "major level" issue that if I do Install first and then do the "load once" again to a game which has already running, it will continuously show the prompt.
