### ISSUE TITLE
Region settings keep resetting.

### ISSUE THREAD

**Issue by kentoadd** [Soreepeong/XivAlexander#198]
Title says it all. Region keeps resetting everytime a new instance is opened. The "Remember Region" setting does not seem to do anything. This isn't too big of a problem, except when you take into account the fact that, when you want to change regions in xivalexander and you're using xivquicklauncher, you'll lose all dalmud functionality (probably since you're no longer loading the game from xivquicklauncher) everytime you restart the game from xivalexander to initiate the region change. 

Also, for some reason, it keeps defaulting to Region 2(NA), when I'm trying to make it stick to Region 1(JP) even AFTER changing the settings, both from xivalexander itself and the config file. I've tried installing, and I've tried loading it into an instance. Same results. As it stands, I can't have both running at the same time, except if I want my region to be set to NA in xivalexander, which I don't. Any help would be appreciated.

**Comment by flatulentfish** [comment]
I am having the same issue, it won't save the region setting but instead of it being stuck on 2(NA) it's 3(EU).

**Comment by Soreepeong** [comment]
What I found is that using `Restart > Region: ...` *without* having `Remember Region Settings` checked will not have any effect, but else than that, choosing region from launcher worked for me. Are you saying that the following didn't have any effect?
* Have `Remember Region Settings` checked.
* Choose `Region: North America`, then restart.
* Open `Restart` menu and confirm that `North America` is checked.
* Choose `Region: Japan`, then restart.
* Open `Restart` menu and confirm that `Japan` is checked.

On the other hand, FFXIVQuickLauncher does not let you change game region - it will stick to the region of your registered SE account. Changing language does not mean changing region.

https://github.com/goatcorp/FFXIVQuickLauncher/blob/99c3a9d08d05364822f813ec3d1e2970f17128c5/src/XIVLauncher/Windows/ViewModel/MainWindowViewModel.cs#L394-L396

**Comment by kentoadd** [comment]
Not exactly. I'll write a step by step on what I did just to make sure I don't forget and skip over something.

 So, say I launch FFXIV through the quicklauncher. The game starts with xivalexander loaded, all good. The region defaults to whatever (NA in my case, which is indeed the region setting for my SE account). Then I check the "Remember Region setting", change the region from "NA" to "JP", hit "Restart" through xivalexander, and the game restarts. The region does successfully change to JP, but doing it this way makes me lose the functionality of ffxivquicklauncher (can't access dalmud, probably because I'm no longer loading the game through the quicklauncher). So having done all that, I close the game, relaunch through ffxivquicklauncher, expecting xivalexander's region to default to JP, because of the "Remember Region setting" option, but it still defaults to NA. Just to be clear I never thought that this was a bug with xivalexander per se, but something I just had no idea how to get around.

>On the other hand, FFXIVQuickLauncher does not let you change game region - it will stick to the region of your registered SE account. Changing language does not mean changing region.

Aw that sucks. I feared this might have been the case. My SE account is NA because 1. All versions of ffxiv available where I'm from is NA and 2. I'm not actually in Japan, but Japan is the closest geographically to where I'm playing from. So am I forced to default to the NA setting if I want to use both quicklauncher and xivalexander or should I forward this to the quicklauncher team?

**Comment by Soreepeong** [comment]
The issue is reproducible - I'll fix it when I can. Anyway, the region settings literally don't matter for anything else than whether to display logo also in Japanese and the format of screencap file names. Nothing about network will change from specifying different region setting.

**Comment by kentoadd** [comment]
OOHH I see. Haha what a relief. I was afraid it affected the latency in some way. Anyways, I appreciate you taking the time to answer. Thanks.

**Comment by flatulentfish** [comment]
OH, yep I was thinking the same as kentoadd, thanks for the tool!

**Comment by Soreepeong** [comment]
Hooking `GetCommandLineA` and `GetCommandLineW` for some reason does not work when the game is launched via FFXIVQuickLauncher, and I have no idea why is this. Regardless, it seems that this issue doesn't matter much, so this might be dealt with later.
