### ISSUE TITLE
XivAlexander copies the FFXIV's Taskbar Icon

### ISSUE THREAD

**Issue by Nillinn** [Soreepeong/XivAlexander#199]
When you run XivAlexander, its taskbar icon turns into the same one as FFXIV. 
Is it possible to make it have another taskbar icon so it doesn't get treated as a second FFXIV instance? It can interfere with some things related to the regular FFXIV icon. 
For example, there's a plugin that is meant to minimize the game window, but it doesn't when XivAlexander is running, because the doubled taskbar icon interferes. And plugins that make the ffxiv icon flash when something happens will make that the FFXIV icon only stops flashing after the XivAlexander window is clicked on.
![Captura de tela 2021-11-17 155102](https://user-images.githubusercontent.com/94562218/142263776-170ee192-6878-44ef-8983-a80c7c27012a.png)

**Comment by CharonM72** [comment]
I've noticed the same issue - the plugins that flash the window flash the XIVAlex window instead of the FFXIV window, which is quite annoying. Similarly, plugins that bring the FFXIV game to the foreground don't work either.

**Comment by Soreepeong** [comment]
[This commit at Mini plugin](https://github.com/Eternita-S/Mini/commit/25f426c50349cbf5a14f6f60087099dccff5e185) should have fixed your issue. Regardless, XivAlexander will appear as a separate icon on taskbar in the next release.

**Comment by Nillinn** [comment]
Hi, thank you for the update. Unfortunately, XivAlexander main window is still grouped with the game on taskbar in the current V1.14.8.38 update
