### ISSUE TITLE
DRG Animation locks seem very short

### ISSUE THREAD

**Issue by CLERIE7K** [Soreepeong/XivAlexander#2]
Log of JP player weaving Dragonfire Dive + Geirskogul: https://i.imgur.com/qK2hjPr.png (2.532s between GCDs)
My log weaving Dragonfire Dive + Geirskogul: https://www.fflogs.com/reports/qZpQCr7TfHn29dKX/#fight=last&view=events&type=casts (2.456s between GCDs)
video: https://streamable.com/jxu79l

Is this intended?

**Comment by anyoneminion** [comment]
what is your ping normally?

**Comment by CLERIE7K** [comment]
about 70 or so according to exitlag. I'm guessing my real ping might be slightly higher. I forgot to mention my GCD in this video is 2.46, but either way it shows that my GCD isn't clipping from the double weave whereas the JP player is definitely clipping since his GCD can't be higher than 2.5s.

**Comment by Soreepeong** [comment]
As far as I know, DRG Jumps(except the og jump) have 1.1sec animation locks, and Statdiver got 1.5s animation lock, while everything else except LB would still have 0.6s.
So, GCD, DfD, Gk, GCD would mean 
`0.6s + 1.1s + 0.6s + 3 * <server response time> = 2.456s` so effective SRT would have been 0.052s which is not my intention; the value is hardcoded as 0.075s so it should have been 2.545.
Note though, as far as I know, ACT tracks via *response* while this program will try to make *request* intervals consistent - I"ll have to check if this has anything to do with the issue.

**Comment by CLERIE7K** [comment]
Okay. Ackwell mentioned that using DFD in melee range might have a lower animation lock because it doesn't "gapclose" so I tried it again from a distance.
https://streamable.com/dh1luc
https://www.fflogs.com/reports/rBmQPGakpcKt7H69/#fight=5&type=casts&source=1&view=events
2.50s GCD
According to the log it seems to be 2.495s between GCDs which is closer to the expected value. But like you mentioned the discrepancy might be due to ACT.

**Comment by Soreepeong** [comment]
Gapclosers always have the same animation lock duration; if target is far away, you will dash faster, and if it is close, then you will dash slower. Can you share the screencap of log window? I need to make it possible to copy timestamps along with logs....

**Comment by CLERIE7K** [comment]
FFLogs: https://www.fflogs.com/reports/91Qjp47ydKAFYbfT/#fight=1&view=events&type=casts
Alexander log: https://i.imgur.com/Ljp9Uyk.png
Video: https://streamable.com/e42fzn

Hope this helps.

**Comment by Soreepeong** [comment]
Thanks for the data!

```
28.926	REQ	0058	Chaos Thrust
29.099	REP	0.600	0.502
29.597	REQ	0060	Dragonfire
29.720	REP	1.100	1.052
30.772	REQ	0de3	Geirskogul
30.883	REP	0.600	0.564
31.446	REQ	0de4	Wheeling Thrust
```
Delays between actions: 0.671s, 1.175s, and 0.674s. It is working as intended from the viewpoint of client side (emulating 75ms flat server response time), and I don't think that we have to address &lt;10ms variations.

**Comment by CLERIE7K** [comment]
I see, thanks.
