### ISSUE TITLE
FFXIV client crash

### ISSUE THREAD

**Issue by CharonM72** [Soreepeong/XivAlexander#200]
I don't know if this is caused by XIVAlexander or not, but I thought I'd throw the log here in case it is.

[XivAlexander_20211118_113909_145.log](https://github.com/Soreepeong/XivAlexander/files/7564424/XivAlexander_20211118_113909_145.log)

**Comment by Soreepeong** [comment]
Which map did you try to teleport to? Also, check if the newest release (will be there very soon) fixes the problem, and try launching game via the official launcher too.

**Comment by CharonM72** [comment]
So far I have not yet seen this recur but I will keep an eye out. It seems to happen rarely when teleporting places, but the destination does not appear to affect it as far as I can tell.
I'll keep using the latest version and update if anything happens.
