### ISSUE TITLE
Constant Crash with FFXIV Client

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#201]
Hi, I've been experiencing a similar issue like the one below.
Alexander constantly keeps crashing with a pop-up msg saying that 'unexpected error has occurred' 'restart client'.
I only use the latency mitigation, no modding or any other utilities.
I'm attaching the log file.

Thank yo
[XivAlexander_20211118_113909_145.log](https://github.com/Soreepeong/XivAlexander/files/7567617/XivAlexander_20211118_113909_145.log)
u,

**Comment by Soreepeong** [comment]
Which map did you try to teleport to? Also, check if the newest release (will be there very soon) fixes the problem, and try launching game via the official launcher too.

**Comment by Soreepeong** [comment]
Did you accidentally upload the wrong log file? The file name is same with the other issue.

**Comment by justin767** [comment]
> Did you accidentally upload the wrong log file? The file name is same with the other issue.

Oops, looks like I did. But I'm having zero issues with the new version now, thank you!
