### ISSUE TITLE
Check update function not using system's default proxy.

### ISSUE THREAD

**Issue by retaker** [Soreepeong/XivAlexander#202]
It seems that the check update function in the client is trying to connect to github directly instead of using system's default proxy. 
I'm using clash for windows and set it as system's default proxy. As long as any software uses system's default proxy, it will redirect the packet and maintain a reliable connection to bypass the network limitations in some areas. 

Would you please also let the "check update" function in the client to use the proxy?

**Comment by Soreepeong** [comment]
Can you check whether `Check for updates` works when system proxy is set? Note that `Automatically detect settings` is not implemented.

[Release.zip](https://github.com/Soreepeong/XivAlexander/files/7616926/Release.zip)

**Comment by retaker** [comment]
> Can you check whether `Check for updates` works when system proxy is set? Note that `Automatically detect settings` is not implemented.
> 
> [Release.zip](https://github.com/Soreepeong/XivAlexander/files/7616926/Release.zip)

Update **successfully** with system proxy set. 

![image](https://user-images.githubusercontent.com/3334662/143984474-e1c1f163-9a24-4b07-91f3-cc248dbcf612.png)
But seems having some issue with TCP protocol. Will update my proxy software and try to download something with my browser.
