### ISSUE TITLE
directx fatal  error 11000002

### ISSUE THREAD

**Issue by jenkshi** [Soreepeong/XivAlexander#203]
hi, I get this error all the time and I don't know how to fix it. I searched for xivalexander logs but didn't find them, so this screenshot is the only thing I have.

![Screenshot 2021-11-21 213358](https://user-images.githubusercontent.com/47603870/142902249-90e64f4d-a73b-4b51-af52-59d3d4d58635.png)

**Comment by Soreepeong** [comment]
That error looks like your system or game installation is having a problem, instead of XivAlexander. You might want to check out https://www.reddit.com/r/ffxiv/comments/mah1so/directx_error_11000002_in_2021/
