### ISSUE TITLE
Can't unload 

### ISSUE THREAD

**Issue by FloppyAl** [Soreepeong/XivAlexander#205]
I installed XIValexander to open every time the game is launched. However I can't seem to unload or close it once the game is up. It says: "Another module is hooked already (try closing that one)" 

Any ideas how I can unload the tool when I don't need it?

**Comment by Soreepeong** [comment]
You cannot unload the program if it's installed. Though, if you did install, yet the error message does not describe that it's not possible when installed, then it's a bug that I have to fix. In any case, you can use "Restart" menu, by unticking XivAlexander. 

The other way involves setting an environment variable when running the game launcher (be it the official one or FFXIVQuickLauncher): add an environment variable named `XIVALEXANDER_DISABLE` of any value. This will technically still load the DLL, but will disable all XivAlexander features.
