### ISSUE TITLE
XivAlexander still copying FFXIV's taskbar icon

### ISSUE THREAD

**Issue by Nillinn** [Soreepeong/XivAlexander#206]
Thank you for addressing the issue earlier and for the update. Unfortunately, XivAlexander's main window is still grouped with the game on taskbar for me, in the current V1.14.8.38 update.

**Comment by Soreepeong** [comment]
I've checked it being displayed separated on Windows 11 at least. Are you on Windows 10? If you are, let me know the Windows version displayed in `cmd` (Command Prompt) like the following:

> Microsoft Windows [Version 10.0.19043.1348]
> (c) Microsoft Corporation. All rights reserved.

If this information is not displayed, type `ver` in the command prompt to get this output.

**Comment by Nillinn** [comment]
Yes, I'm on Windows 10.
Version 10.0.19042.1348

**Comment by Soreepeong** [comment]
Can you check whether this fixes the problem? 

[Release.zip](https://github.com/Soreepeong/XivAlexander/files/7616926/Release.zip)

**Comment by Nillinn** [comment]
It has fixed the problem with the taskbar icons. 
But now, I can't get the latency mitigation to work in this version of XivAlexander. Only works in the latest one. Do I need to change the Opcodes or something?

**Comment by Soreepeong** [comment]
The file I've attached is missing all opcode files. You can paste the json files from the other one to the directory.

**Comment by Nillinn** [comment]
Oh, I see. I pasted the json files and now it's working as it should. Both the icons and the latency mitigation.
Thank you a lot for the support
