### ISSUE TITLE
Not sure what setting to use for High Latency mitigation

### ISSUE THREAD

**Issue by ggcatito** [Soreepeong/XivAlexander#207]
Hi, I've been using the tool for about a month or so, but it was never really clear to me (even after reading all documentation), what mode works best for each scenario.  For example, I have about 200 ~ 220ms, playing on the NA Datacenter, and I use Mode 3, because it seemed to be the most complex and interesting one, but I actually don`t have any idea if it is the best for this high of a ping, even though I noticed that I can Double weave everytime and made jobs like machinist playable for me.  Here are the logs with each mode, from 3 to 1. Could you please explain what mode would be better and why ? 

**MODE 3 LOG WINDOW**
![image](https://user-images.githubusercontent.com/95214839/143843024-5f963c53-4c2f-416f-9d2c-7e343f145d7d.png)

**MODE 2 LOG WINDOW**
![image](https://user-images.githubusercontent.com/95214839/143844224-24951dc2-70b3-45b9-8dbb-0cf8fe68d75f.png)

**MODE 1 LOG WINDOW**
![image](https://user-images.githubusercontent.com/95214839/143843753-9b493234-0426-4291-a75e-02ff9edf1e66.png)

Thank you for making the game more enjoyable for high ping players like myself.

**Comment by Soreepeong** [comment]
I usually stick to mode 2, which has been how this program worked at the first release. 1 and 3 are provided as a YMMV-basis. The explanation I have will explain *how* will it work, but it's not like I have a good reasoning on *why* should you use any one of those. It's pretty safe to pick one and stick to it, as long as you can play without getting your actions clipped.

That said, either one of mode 2 or 3 looks good for you, judging from the length of wait times between actions reduced. Mode 1 tends to not work well when the ping is higher, and I'm not sure why, but then again it's not like I really cared about that, so yeah.

**Comment by ggcatito** [comment]
Thank you very much for the quick response! I hope this helps more people in the future! And also thank you for the tool, it is a godsend for high latency players!
