### ISSUE TITLE
Show XivAlexander client version number somewhere in the control window. 

### ISSUE THREAD

**Issue by clemmyn23** [Soreepeong/XivAlexander#208]
Feature request. 

Something like this would be useful to figure out which version is currently running 

(bad mockup here) 
![image](https://user-images.githubusercontent.com/6946253/143968873-a924c898-bd46-4f95-9b95-5b3b5b9208dd.png)

**Comment by Soreepeong** [comment]
![image](https://user-images.githubusercontent.com/3614868/143969066-10085b2d-11c3-4ca1-a709-305cbfcb6697.png)

Oh, definitely. I thought I put version to all window titles, but apparently except the real windows.
