### ISSUE TITLE
Actions stop working

### ISSUE THREAD

**Issue by guilhermesupe** [Soreepeong/XivAlexander#21]
After using the addon for a while I noticed 3 times a weird situation happening. It seems that randomly my actions stop working entirely. I press the buttons but the GCD doesnt start, seems like I'm not sending anything to the server anymore. Everything else works fine. I was not lagging at the time and was able to see other players actions as normal. I tried GCD,OGCDS, buffs and none of them worked. I tried to reload configuration, unload xivalexander, even close it entirely to no avail. The only way I could make the game to work again was to close the game entirely and re-open. This is the log I had for third time it happened.
[No-actions-log.txt](https://github.com/Soreepeong/XivAlexander/files/6033074/No-actions-log.txt)

**Comment by guilhermesupe** [comment]
Looking in the log I noticed this line: 021-02-23 23:30:21.775    S2C_ActionEffect: actionId=00d8 sourceSequence=06d9 wait=600ms->18446744073709551516ms

**Comment by Soreepeong** [comment]
Can you try again with the latest version? The log file got something that shouldn't appear anymore.

**Comment by guilhermesupe** [comment]
Yes, no problem I will start using the newest version. I was using v1.11 when the  new patch came out I just updated the OP codes. I will monitor if that happens in the newest version
