### ISSUE TITLE
Question on opcodes

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#210]
Hello, I did upload the opcodes for KR 5.57 patch, but my testing gives me the same value for both 'C2SActionRequest' and 'C2SActionRequest/GroundTargeted', does it sometimes happen?

**Comment by Soreepeong** [comment]
Which actions did you use? Never seen that before.

**Comment by justin767** [comment]
> Which actions did you use? Never seen that before.

![2](https://user-images.githubusercontent.com/82459386/144017748-915013fb-0556-48e7-bff5-881e6fb210d5.JPG)
![3](https://user-images.githubusercontent.com/82459386/144017750-a2a0ea4c-1628-4507-86b5-f95b040f0dcf.JPG)


I tested using DRK's hard slash and unleash. The first one is the log for hard slash, and the second one is for unleash(ground targeted). But it gives me the same opcodes.

**Comment by Soreepeong** [comment]
By ground targeted, I mean the actions that you click on ground to use it, like Shukuchi, Soten, and Sacred Soil.

**Comment by justin767** [comment]
> By ground targeted, I mean the actions that you click on ground to use it, like Shukuchi, Soten, and Sacred Soil.

omg I so dumb, found the correct opcode, thank you. Let me edit my previous post.
