### ISSUE TITLE
Question for EW release.

### ISSUE THREAD

**Issue by Brasolis** [Soreepeong/XivAlexander#211]
Hello, currently I'm running the installed version of XIVAlexander. Will I need to uninstall before the release of EW or will the client still run, just not have the latency mitigation in place right away?

**Comment by Soreepeong** [comment]
The game will run just fine, unless you use the modding feature built-in *and* the game has been changed drastically somehow (which is unlikely as the same modding application technique has just worked ever since 3.5). All you'll have to do is edit the opcodes, again unless somehow networking code has been changed much.

**Comment by Brasolis** [comment]
Thanks for the info!

**Comment by CharonM72** [comment]
On this topic, I imagine this is still largely an unknown, but what is the expectation for excel transforms? Will they continue to work for new Endwalker text strings (as I imagine they will)?

**Comment by Soreepeong** [comment]
Unless they shuffle around table column orders, it should just work if modding works.

**Comment by TechPoi** [comment]
Hello yes so just to confirm it is safe to keep the plugin installed for EW release if not using modding tools ?

**Comment by Soreepeong** [comment]
Yes, the plugin should simply not do its job if the game has changed a lot, but should not result in a crash.

**Comment by TechPoi** [comment]
ok just making sure i didn't need to uninstall for like any tos stuff or chances of a ban is all :) thanks

**Comment by Brasolis** [comment]
This has always technically been against TOS and bannable if they implement any cheat detection systems and actively went after it.

**Comment by Spanglish1337** [comment]
Yep! I don't think we will ever get any issues with this, unless it is talked about in-game.

I have tried to understand how to get opcodes but I still can't figure it out, complicated for me :(, I hope someone can find those soon after EW goes early access.

**Comment by CharonM72** [comment]
I can confirm that Excel Transforms appear to be working completely fine.

**Comment by Opblaaskaas** [comment]
XIVAlexander isn't working for me right now in EW, which was to be expected. Just figured I'd let people know!

**Comment by CharonM72** [comment]
Both Excel Transforms (text replacement) and the latency mitigation (using the opcodes posted in another issue) work for me. I haven't tried the other features.

**Comment by TrashmanJigs** [comment]
Thank you so much! That indeed worked perfectly. :)

**Comment by cringeewaboo1337** [comment]
Do I need to do anything to make XIValexander work for EW other than launching it normally?

**Comment by TechkiGuy** [comment]
If i download the v1.14.8.39 of XIV, do i need to config anything or just open XIV and the game ? (i only use for the latency mitigation, no mods.) Thank you in advance
