### ISSUE TITLE
Intl 6.00 Opcodes

### ISSUE THREAD

**Issue by Soreepeong** [Soreepeong/XivAlexander#213]
```json
{
	"C2S_ActionRequest": "0x00cb",
	"C2S_ActionRequestGroundTargeted": "0x037c",
	"S2C_ActionEffect01": "0x035a",
	"S2C_ActionEffect08": "0x01ba",
	"S2C_ActionEffect16": "0x02ce",
	"S2C_ActionEffect24": "0x02ed",
	"S2C_ActionEffect32": "0x023a",
	"S2C_ActorCast": "0x0108",
	"S2C_ActorControl": "0x017e",
	"S2C_ActorControlSelf": "0x02e6",
	"S2C_AddStatusEffect": "0x93db",
	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24",
	"Server_PortRange": "1025-65535"
}
```

AddStatusEffect size has changed. It's not vital for the functionality, so you can use this anyway.

**Comment by Soreepeong** [comment]
1. Open XivAlexander main window. See your taskbar's notification icons area and find a gear icon, if you don't know how to open one. 
2. Configure > Edit Opcode Configuration
3. Paste all that, and save.

**Comment by AwesomeJames2120** [comment]
Thank you so much dude!

**Comment by owopeachy** [comment]
thank you for the quick update <3

**Comment by Nanu308** [comment]
Awesome work on the quick fix!

**Comment by FloppyAl** [comment]
Thank you.

**Comment by Rossier** [comment]
These opcodes are not working for me. In fact, xivalexander hasn't been working for me for a few days already. I don't know what is wrong

**Comment by Spanglish1337** [comment]
Do we close and open FFXIV if we have it open, when we update opcodes?

**Comment by Soreepeong** [comment]
You don't have to restart the game or reload XivAlexander. Just change the configuration and save, and that's it.

**Comment by Spanglish1337** [comment]
> You don't have to restart the game or reload XivAlexander. Just change the configuration and save, and that's it.

Thank you, much appreciated! Thank you a lot for your work on this plugin.
