### ISSUE TITLE
Can't Load Again After Unload XIVAlexander

### ISSUE THREAD

**Issue by exeedz** [Soreepeong/XivAlexander#215]
How to repro:
- Load XIVAlexander
- Unload XIVAlexander
- Load XIVAlexander again

I assume by unload it will remove the hook, turns out it doesn't.
I'm doing this to change opcodes without restarting client

**Comment by Soreepeong** [comment]
Is this a case after installing, or from load once? Changing opcodes do not require reloading XivAlexander - opening Opcode editor and saving will apply the changes immediately. Anyhow, I'll check what's wrong.

**Comment by exeedz** [comment]
from load once

**Comment by dblack850** [comment]
This has just happened to me as well.

**Comment by Soreepeong** [comment]
I can't reproduce this - it unloads and loads just fine for me. Any particular settings that you've configured?

**Comment by exeedz** [comment]
Just default configuration.

Here's the error
![image](https://user-images.githubusercontent.com/5017342/145397529-0d56a84c-007c-4fc3-8f57-337ed1115b39.png)

1. I login from launcher (both default and xivlauncher effected), still on main menu
2. Start xivalexander64.exe, choose "load once" then "load"
3. then from xivalexander menu i choose "unload"
4. repeat step 2
5. error shows up

**Comment by SeaCKei** [comment]
Having the exact same problem aswell, need to restart the game everytime i unload it so i can load it again

**Comment by Soreepeong** [comment]
Why do you want to load it again, by the way? If you're trying to apply different opcodes, simply saving in opcode editor will do.

**Comment by SeaCKei** [comment]
For my case, i have another application (Auto Synth) that will not work when Alex is running so what i used to do is turn Alex off if im using Auto Synth and turn it back on after im done.

**Comment by Soreepeong** [comment]
Is it a .NET based program? As a workaround for now, you can close XivAlexander windows (just hide it without exiting), including main, log, and configuration windows, and *then* run other program, and it should work.

**Comment by SeaCKei** [comment]
> 

I believe its a .NET based program yea.The workaround is great and i think ill keep doing this from now on LOL.
Thanks for the help!

**Comment by dblack850** [comment]
AutoSynthesis and Alexander have _always_ worked fine together for me and still does.

**Comment by dblack850** [comment]
> 

This was exactly what happened to me before installing. I can’t remember why I did it but I know that loading and unloading Alexander always worked before. It’s a non-issue for me now, using the installed DLL.

That said, is there a problem with renaming the DLL “dxgi.dll” for any possible conflicts with Dalmud plugins?

**Comment by Soreepeong** [comment]
As a workaround, you can copy xivalex files to another folder and launching it from there. While I can't replicate this problem, it's probably about the program not being completely unloaded, and this error is caused by that. Having XivAlexander in an alternative directory will make the system treat two copies of XivAlexander to be different ones.
