### ISSUE TITLE
Installed Xivalexander not working

### ISSUE THREAD

**Issue by Rossier** [Soreepeong/XivAlexander#218]
I was using the older version of xivalexander that required me to run it manually everytime i opened the game and that worked fine. But I recently switched to the version that allows you to install xivalexander to launch with the game launcher. Initially it worked, and a few days before the ew it stopped working. I've changed the opcodes but it still feels as if I'm playing without xivalexander even though it's loaded. Any idea what might be the problem?

**Comment by Soreepeong** [comment]
Just to make sure, open `Opcode Configuration` and copy and paste everything to here. Also, are you using a proxy or VPN or some sort? Try checking on `Networking > Troubleshooting > Take Over All Addresses`.
