### ISSUE TITLE
미구현 아이템의 이름이 공백으로 표시되는현상

### ISSUE THREAD

**Issue by SiddimChest** [Soreepeong/XivAlexander#219]
![Screenshot 2021-12-04 at 13 58 12](https://user-images.githubusercontent.com/95053706/144697760-a2f70987-a9a6-4eef-ae2d-5e3576c3308c.png)
![Screenshot 2021-12-04 at 13 58 24](https://user-images.githubusercontent.com/95053706/144697765-f474a021-46d0-4341-9fdf-5881b4a822d4.png)

위와 같이 한글패치를 적용하면 미구현 아이템의 이름이 공백으로 표시되는데 미구현아이템은 일본어로 출력되게 하는법 없을까요?
아예 공백으로 나와서 불편하네요

**Comment by SiddimChest** [comment]
두개 언어 같이 사용하게 하여서 아이템이름이 공백으로 나오는 문제는 해결했는데 스킬명이랑 스킬내역 컷씬이 공백으로 나오는 문제는 아직 해결하지 못하고있네요

**Comment by Soreepeong** [comment]
#220 으로 통합해서 이슈 관리하겠습니다.
