### ISSUE TITLE
6.0 업데이트 이후 한글 패치 사용시 발견된 문제 목록

### ISSUE THREAD

**Issue by SiddimChest** [Soreepeong/XivAlexander#220]
6.0이후 퀘스트 컷씬에서 NPC보이스 미출력
6.0이후 퀘스트 컷씬에서 NPC대사자막 미출력
6.0이후 퀘스트 컷씬에서 선택지 미출력
6.0이후 스킬칸 공백화 일본어조차도 써있지 않음

일본어/한국어 혼합패치 사용기준으로 발견한 버그입니다
수정될수있을까요?

**Comment by Soreepeong** [comment]
당장은 못하지만 나중에 한번 확인해 보겠습니다.

**Comment by Soreepeong** [comment]
[Release.zip](https://github.com/Soreepeong/XivAlexander/files/7683468/Release.zip)

한번 확인해 보시겠어요? 다른 언어의 정보를 섞는 중, 한국어에 정보가 아예 존재하지 않으면 다른 언어를 가져다 썼지만, 한국어가 빈 텍스트일 경우 비어있는 그대로 적용하던 걸, 비어있을 경우 다른 언어를 가져다 쓰도록 수정하였고 일단 수정된 것 같아 보입니다.

**Comment by Soreepeong** [comment]
이걸로 해 보세요: 중복되어 나오는 경우가 있어, 다른 언어간 텍스트가 동일하거나 한쪽 언어에만 존재하는 경우 한 가지로만 나오도록 수정하였습니다.

[Release_2.zip](https://github.com/Soreepeong/XivAlexander/files/7683732/Release_2.zip)

**Comment by Soreepeong** [comment]
아예 새 릴리즈를 올렸으니 확인해 보시기 바랍니다.
