### ISSUE TITLE
Unexpected error occurred when trying to install XIVAlexander

### ISSUE THREAD

**Issue by nayaflask** [Soreepeong/XivAlexander#222]
I get this error when I try to install.

![alexerror](https://user-images.githubusercontent.com/95555240/144731522-bfe8a4cb-3766-4745-b108-d0352162efe6.PNG)

**Comment by stormraider1314** [comment]
same problem here!

**Comment by Soreepeong** [comment]
Do you have Reshade or stuff installed? While it worked for me™, compatibility with other addons aren't guaranteed. Try removing other addons, install XivAlexander, and then reinstall other addons again.
