### ISSUE TITLE
XIV Alexander not working since 6.0 (Steam User)

### ISSUE THREAD

**Issue by Primordial94** [Soreepeong/XivAlexander#223]
Hello.. English is not my first language.. Sorry for any mistakes..

Since 6.0 the XIV Alexander is not working for me.. I use Exit lag and the Steam Version of the game.. The program doesn't work with and without Exit Lag.

![XIV Alexander](https://user-images.githubusercontent.com/95634512/144877516-1d14f3f8-5247-4160-a0b9-08004751649e.png)

Thank you !

**Comment by Soreepeong** [comment]
What do you mean by "doesn't work"? Try opening the logging window, and see whether anything gets printed.

**Comment by Primordial94** [comment]
> 

![XIV Alexander 2](https://user-images.githubusercontent.com/95634512/144878893-13748d02-ddd4-4c7f-9363-f1c39b70a3ef.png)

Thank you for the fast response!

**Comment by Soreepeong** [comment]
When did you download the program? I have replaced the file some time ago to include opcodes file. Refer to #213 and see if opcodes are correctly set.

**Comment by retaker** [comment]
Have you updated the opcodes for 6.0 from the issues?

Primordial94 ***@***.***> 于 2021年12月6日周一 23:58写道：

**Comment by Primordial94** [comment]
> When did you download the program? I have replaced the file some time ago to include opcodes file. Refer to #213 and see if opcodes are correctly set.

2-3 months ago... the opcodes were different.. I Copied and pasted the new ones and now is working just fine.. Thank you so much!
