### ISSUE TITLE
Unrecoverable error after 10 minutes 

### ISSUE THREAD

**Issue by FrozenSneak** [Soreepeong/XivAlexander#224]
![Screenshot (5)](https://user-images.githubusercontent.com/95650806/144906453-e775814f-1a1c-4053-899c-2d84fd2ee8ab.png)

Does anyone know what's causing this issue?

**Comment by retaker** [comment]
Click the Export Log button next time and upload it to this issue.

**Comment by Soreepeong** [comment]
Something looks wrong with the game launch arguments, too. Are you indeed using the official launcher?
