### ISSUE TITLE
Auto 'yes' without confirmation?

### ISSUE THREAD

**Issue by AKoseki** [Soreepeong/XivAlexander#225]
Is it possible to start the program silently? As in, I open the program and it would detect the xiv application and then it would "auto click yes" and inject instead of me needing to click yes ?

**Comment by Azurealistic** [comment]
To add onto this, is it possible to have a config/setting where it completely skips the install/load screen and simply loads the program silently?

**Comment by Soreepeong** [comment]
Giving `-a load` argument should do what you want. You can make a shortcut to Loader by dragging loader exe file while holding Alt key. After making one, right click on the shortcut file, and add "-a load" to the end of "Target".

```
XivAlexanderLoader64.exe -a load
```

There should be a wiki article on command line options; it will be there sometime after.

**Comment by AKoseki** [comment]
Thank you, this is perfect!
