### ISSUE TITLE
Not loading EXDF transforms?

### ISSUE THREAD

**Issue by CharonM72** [Soreepeong/XivAlexander#228]
In the latest version, I have loaded an EXDF transform file, as seen below, but it does not load the transforms when booting FFXIV. Not sure what the issue is.

![image](https://user-images.githubusercontent.com/1299220/145501091-39449723-3c44-4ff3-b70c-2ba79031a2b3.png)

**Comment by Soreepeong** [comment]
Is there anything printed about it in log window?

**Comment by CharonM72** [comment]
Here's the log window:

![image](https://user-images.githubusercontent.com/1299220/145501993-b5862899-5a5f-4974-b880-4b47feb4276b.png)

**Comment by Soreepeong** [comment]
It works fine for me. Can you try deleting files in `%appdata%\XivAlexander\Cached\` and try again? Also, share your runtime config json file.

**Comment by CharonM72** [comment]
I don't see a cache folder in either `AppData\Local\XivAlexander` or `AppData\Roaming\XivAlexander`.

Here is the json I'm using, although I also tested it with the json provided in the release download:
[EnglishWithJapanese_SayQuestEnglish.txt](https://github.com/Soreepeong/XivAlexander/files/7689514/EnglishWithJapanese_SayQuestEnglish.txt)

(GitHub won't let me upload json files so i changed the extension to .txt but it's the same content)

**Comment by Soreepeong** [comment]
I mean the program configuration file that can be found in `%appdata%\XivAlexander\config.runtime.json`. It might be possible that something is disabling modding.

**Comment by CharonM72** [comment]
Here you go, from the Roaming folder:
[config.runtime.txt](https://github.com/Soreepeong/XivAlexander/files/7689524/config.runtime.txt)

Again, had to convert it to .txt.

**Comment by Soreepeong** [comment]
Yeah, for some reason, modding is turned off. Turn that on, and it should work.

**Comment by CharonM72** [comment]
OHH i forgot it was turned off by default in a new install lol.

Well that was stupid of me. Anyway it works now, thanks.
