### ISSUE TITLE
폰트 바꾸는법을 질문해도 될지 모르겠네요ㅠㅠ..

### ISSUE THREAD

**Issue by dspzlqlp** [Soreepeong/XivAlexander#229]
기존  fk.7z 라는 한글폰트 추가 패치를 써써 한글폰트만 추가해서 잘 하다가
이번에 알렉산더 처음 써서 dinput8.dll 을 원 상태로 되돌렸습니다.

근데 옛날 한글폰트랑 폰트가 좀 다른지 SourceHanSansK 폰트는 배경이 밝은 곳에선 글자가 좀 얇아서 보기가 어려워서 

https://github.com/Soreepeong/XivAlexander/wiki/%ED%8F%B0%ED%8A%B8-%EA%B5%90%EC%B2%B4-%EC%84%A4%EC%A0%95

이거보고 제가 새로운 폰트 json 파일을 만들어보려고 해봤는데요
SourceHanSansK.json 처럼 글로벌 서버 폰트는 그대로 두고 "한글영역 폰트만 추가"하는 방식으로요

그래서 SourceHanSansK.json 메모장 열고 
모두바꾸기로 SourceHanSansK 를 원하는 폰트이름으로 바꿨는데 
바뀐게 없어서요 ㅠㅠ 제가 이렇게 파일 열어서 뭐 해본건 처음이라..

 

1. 혹시 알렉산더 폰트 패치 방식은 시스템 일본어,메인화면 일본어 이런건 그대로 놔두는것 같은데

채팅창에 출력되거나 npc나 꼬친 이름 일본어까지 바꾸게 되나요? SourceHanSansK.json 폰트로 했더니 메인화면이나 캐릭터 일본어 폰트는 그대로인데 인게임 채팅을 비롯한 기존 일본어 폰트도 바뀐것 같더라고요

2. SourceHanSansK.json  안에는 SourceHanSansK 라고만 되어있는데 
윈도우 폰트 설정 열어보면

light nomal regular heavy 이렇게 굵기별로 메타파일??이름이 다 다른것 같은데 패치 json 파일 만들때 light nomal regular heavy 를 골라서 적용할 수는 없을까요? 

3.
https://github.com/Soreepeong/XivAlexander/blob/main/StaticData/FontConfig/SourceHanSansK.json
SourceHanSansK.json 메모장 여니 위 링크처럼 된 코드가 나와서

모두바꾸기로 SourceHanSansK 를 gulim 으로 바꿔보고

SourceHanSansK-heavy 로도 바꿔봤는데

새로만든 2개의 json 파일 죄다 그냥 SourceHanSansK 글꼴로 나오더라고요

바꿨을때 설치 과정 박스는 나왔었는지만요

어떻게하면 글로벌 서버 폰트는 그대로 두고 한글 폰트를 다른걸로 바꾸는 json파일을 만들 수 있을까요 ㅠㅠ??

**Comment by Soreepeong** [comment]
1. `targets`에서 `font{}.tex`에 들어가는 것이 로그인 후, `font_lobby{}.tex`에 들어가는 것이 로그인 전 (메인 메뉴/캐릭터 선택 등) 화면에 반영되는 폰트이고, 일본어가 나오는 부분이라면 그 부분은 항상 AXIS로 사용되니 참고바랍니다.
2. 그게 `weight`에 해당되는 것으로, "thin", "extralight", "ultralight", "light", "semilight", "normal", "regular", "medium", "semibold", "demibold", "bold", "extrabold", "ultrabold", "heavy", "black", "extrablack", "ultrablack" 또는 1 ~ 1000 까지의 값이 입력 가능합니다. 자세한 사항은 해당 폴더에 있는 `fontconfig.schema.json`을 참고해 보세요.
3. 찾아바꿀 때 "SourceHanSansK" 뿐만 아니라 "Source Han Sans K"도 바꾸어야 합니다. 후자가 진짜 폰트 이름이고, 전자는 폰트이름+설정묶음을 지칭하는 부분입니다. `sources` 안에 하위 오브젝트의 `familyName`을 설정해 보세요.

**Comment by dspzlqlp** [comment]
감사합니다 해결 했습니다 !
