### ISSUE TITLE
Game crashes at random times be in mid dgn or during a cutscene 

### ISSUE THREAD

**Issue by Riibbon** [Soreepeong/XivAlexander#230]
Hello for awhile now ive been having game crashes at random intervals and with the que times being so long now id like to find out what is the cause, I bought the game on steam but play through xivlauncher and get hit with this error at times 
![image](https://user-images.githubusercontent.com/95907040/145540497-31ac395f-cb2d-42f7-8ed6-c54e32b0cdc2.png)
With that being said i also have the log file from xivalexander itself
[XivAlexander_20211210_191255_177.log](https://github.com/Soreepeong/XivAlexander/files/7691137/XivAlexander_20211210_191255_177.log)
Any help would be appreciated and if nothing can be done that is fine also

**Comment by Soreepeong** [comment]
"See details" should really be expanded by default. Anyway, the error is "A fatal DirectX error has occurred.(11000002)", which XivAlexander doesn't touch at all. You can try updating to the latest version of graphics drivers, but seeing that there have been a lot of people experiencing that error with or without XivAlexander or FFXIVQuickLauncher/Dalamud, your best bet is hoping SE to fix their software, or fall back to using DX9 version for the time being.

**Comment by Riibbon** [comment]
Thank you for the quick reply, but yeah ive always been updated to the latest drivers and apologies i took the ss before opening it and seeing so myself.

**Comment by Soreepeong** [comment]
Also, try uninstalling Immerse stuff. Installing Nvidia Studio Drivers might help too as they're *believed* to be more stable. Anything that touches the game's graphics stuff might be a culprit too; try disabling Dalamud and don't run OBS for a run for testing purposes too.

**Comment by Riibbon** [comment]
Will do, will give it a shot the next time it crashes. Thank you
