### ISSUE TITLE
Unexpected Error when installing XivAlexander

### ISSUE THREAD

**Issue by Zephsi** [Soreepeong/XivAlexander#231]
I get the below when trying to install XivAlexander

![image](https://user-images.githubusercontent.com/95912518/145557563-4db94d73-31d4-4371-bebe-26725d60a108.png)

**Comment by Soreepeong** [comment]
It's likely that your antivirus is the culprit. Try adding to exceptions or turning off your AV. If you're using BitDefender, you'll have to restart your PC too.

**Comment by Zephsi** [comment]
That fixed it thank you. Sorry forgot that downloading the updated version wouldn't still be whitelisted. Appreciate the answer to my silly question :)
