### ISSUE TITLE
Korean display language on international client?

### ISSUE THREAD

**Issue by wacomintuos** [Soreepeong/XivAlexander#232]
I play on Japanese server but I want to use Korean display language mod with XIVAlexander.

When I select Korean display language from Modding -> Force Display Language (x64 only) -> Korean, my client is still in Japanese language.

Is it because Korean client is not installed so I cannot use its assets? Any way to use Korean display language on international?

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivAlexander/wiki/EXDF-Transformation-Rules

Yes, you'll have to install the client, and add to additional game root directories.
