### ISSUE TITLE
Crash after waiting queue and enter Now Loading Screen 

### ISSUE THREAD

**Issue by gwynnS** [Soreepeong/XivAlexander#233]
This is my log

[XivAlexander_20211210_224613_416.log](https://github.com/Soreepeong/XivAlexander/files/7693899/XivAlexander_20211210_224613_416.log)

**Comment by Soreepeong** [comment]
Try reinstalling your graphics driver. This error doesn't look like a problem with XivAlexander, as the search results bring out some graphics related errors which this program doesn't touch.
