### ISSUE TITLE
had this crash twice today, once in cutscene and another in world

### ISSUE THREAD

**Issue by Dedoooo** [Soreepeong/XivAlexander#234]
https://prnt.sc/22ntijk is it caused by xivalexander itself or ff14?

**Comment by clemmyn23** [comment]
Just got the same crash. 

Log here (doesn't look that useful?) 
[XivAlexander_20211211_171054_137.log](https://github.com/Soreepeong/XivAlexander/files/7696543/XivAlexander_20211211_171054_137.log)

**Comment by clemmyn23** [comment]
Hmmm seems to be a duplicate of https://github.com/Soreepeong/XivAlexander/issues/230#issuecomment-990727621
See comments inside for explanation

**Comment by Dedoooo** [comment]
i believe both times the crash occured as i was tabbing back in the game.

**Comment by Soreepeong** [comment]
Just try again. I don't know why, but it occasionally would show that error message: `Unable to launch application. Launch using the ffxivboot.exe file.(0)`. Using [https://github.com/goatcorp/FFXIVQuickLauncher](FFXIVQuickLauncher) might prevent this from happening.
