### ISSUE TITLE
XIVAlexander breaks Discord streaming

### ISSUE THREAD

**Issue by mattskiiau** [Soreepeong/XivAlexander#235]
Unsure if this is something that can be addressed.
While running FFXIV, Discord and XIVAlex as Admin mode, When turning on Discord stream, black screen will be shown.

**Comment by CharonM72** [comment]
I have an issue streaming if I stream using Discord's auto game detect thing. If I manually click "share screen" and then choose the FFXIV client, then it streams fine. Another alternative would be streaming the entire display, but of course then it streams everything on that display, so be careful.

**Comment by Soreepeong** [comment]
Try hiding the XivAlexander main window. Also, you shouldn't be running either program as Administrator, especially if you're playing on international servers. Other than that, it works for me; are you running any other addons, or something like FRAPS?

**Comment by mattskiiau** [comment]
Thanks the suggestions here resolved the issues. 

May I enquire about the comment of "you shouldn't be running either program as Administrator, especially if you're playing on international servers"

It seems to be working in admin now for me.

**Comment by Soreepeong** [comment]
It's just a general suggestion: don't run anything as Administrator if it works without Administrators permissions. It reduces the chances of programs breaking the entire system should it bug out badly.

**Comment by mattskiiau** [comment]
Thank you, noted.
Everything sorted. Thank you all!
