### ISSUE TITLE
WSAIoctl SIO_TCP_INFO Invalid Argument

### ISSUE THREAD

**Issue by Nanu308** [Soreepeong/XivAlexander#238]
An error is showing up in the logs, and at times outside of these errors i get a random disconnect from the FFXIV servers with the error code 90006.

Unsure if this is related to XIVAlexander or not. I can provide further logs if needed, but i do not wish to post my IP publicly of course. 

```
2021-12-12 07:30:41.334    SocketHook    10dc: WSAIoctl SIO_TCP_INFO v0: 00002726 (An invalid argument was supplied.)
2021-12-12 07:30:41.334    SocketHook    1160: WSAIoctl SIO_TCP_INFO v0: 00002726 (An invalid argument was supplied.)
```

**Comment by Soreepeong** [comment]
This "error" doesn't even need to be printed, as it's completely ignorable. Your problem probably is at something else.

**Comment by Nanu308** [comment]
If you believe it is a non issue then i shall close the issue, regardless ty for the quick answer
