### ISSUE TITLE
Action macros broken when text transformation rules are applied.

### ISSUE THREAD

**Issue by AkiyoAratemuso** [Soreepeong/XivAlexander#239]
Heya, I've noticed that action macros (e.g. /ac Reflect) are broken when text transformation rules are applied. Both languages of the skill is not recognized as a valid action, and have to rely on them being auto translated to work.

Will this be too much effort to fix and categorized under will not fix?

**Comment by Soreepeong** [comment]
Either you can disable transforming action names, or you'll have to auto-translate feature. Edit exdf transformation rule json files to remove lines containing "Action".
