### ISSUE TITLE
Unable to log into XIV after installing Alexander

### ISSUE THREAD

**Issue by ShinsoTheOnion** [Soreepeong/XivAlexander#240]
I installed XIVAlexander as Dinput8.dll for DX11 version and afterwards I'm unable to log into FFXIV. Tried both quicklauncher and the normal launcher. It will state that my credentials are incorrect. Double/triple checked and was able to log into the site but the launcher doesn't work.

**Comment by Soreepeong** [comment]
XivAlexander has absolutely no effect on launchers. Only errors occurred after launching the game itself might be related to XivAlexander.

**Comment by ShinsoTheOnion** [comment]
Yeah I noticed that they made an official post after I posted this issue. I'll try again shortly and let you know.
