### ISSUE TITLE
Export font as .ttmp2?

### ISSUE THREAD

**Issue by mkarer** [Soreepeong/XivAlexander#241]
Is there a way to export the the generated font as .ttmp2 to use it with TexTools/Penumbra?

**Comment by Soreepeong** [comment]
You can just compress the folder containing `.ttmpl` and `.ttmpd` files into a `.zip` file, and then rename it to `.ttmp`.

**Comment by mkarer** [comment]
Thanks, that's what i tried at first, but it didn't work.

TexTools error for every single file (font1.tex + lots of .fdt files):
Import Stage: Index Writing
Error: Length cannot be less than zero.
Parameter name: length

Penumbra doesn't display an error, but fonts don't change either.

If it's supposed to work that way it's propably a TexTools/Penumbra issue?

**Comment by Soreepeong** [comment]
As far as I know, TexTools does not support changing files in `000000`, which includes fonts. For Penumbra, you have to have the plugin loaded as soon as possible, and need to have the font ttmp activated before you log in.

**Comment by mkarer** [comment]
Ah, that's propably what TexTool was trying to tell me with that weird error.

Thanks for the hint, I thought Penumbra would replace the files already after loading, but it seems it requires me to actually log in, which I wasn't able to do earlier because of queue times. I tried it again now, after actually logging in with a character the fonts are getting replaced.

I'll stick to XivAlexander though - although I don't need any of the other features I prefer having the correct fonts already when launching the game. Thanks again, appreciate it. :)

**Comment by toshiya14** [comment]
> Ah, that's propably what TexTool was trying to tell me with that weird error.
> 
> Thanks for the hint, I thought Penumbra would replace the files already after loading, but it seems it requires me to actually log in, which I wasn't able to do earlier because of queue times. I tried it again now, after actually logging in with a character the fonts are getting replaced.
> 
> I'll stick to XivAlexander though - although I don't need any of the other features I prefer having the correct fonts already when launching the game. Thanks again, appreciate it. :)

Sorry to bother you. I compressed the mod cache folder into zip and then renamed it to `ttmp` but the mod makes every font disappeared.
I see that you said you have successfully replaced the fonts?
Did you do any additional actions to make the `ttmp` pack?
