### ISSUE TITLE
'Check for updates' function not working

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#242]
![1](https://user-images.githubusercontent.com/82459386/146778996-ba4f5cab-4951-448c-9d1c-def461408932.JPG)

Hello, whenever I click 'check for updates' on XivAlexander, the popup msg above shows up.
Same thing happens for 'unload xivalexander' button.

Any solutions? Thanks.

**Comment by Tamamog** [comment]
![image](https://user-images.githubusercontent.com/92046897/146975039-692b0ad5-15d0-4293-a34d-606acffff27f.png)
This is what happens when I try to update,  running it in admin mode.

**Comment by Soreepeong** [comment]
1. Above message happens when downloaded files are corrupt. It should not happen - I'm going to make a new release later today; please check out again later.
2. It should not be updated while the game is running. I'll change it so that it gives you more helpful error message.
