### ISSUE TITLE
S2C_AddStatusEffect not working when checking opcodes manually

### ISSUE THREAD

**Issue by Elevation1** [Soreepeong/XivAlexander#243]
When looking for opcodes manually, the S2C_AddStatusEffect code is not working correctly.  Any time we use buff applying actions, such as Rampart (as labeled in the guide), the log message only provides us with S2C_ActionEffect01.  We only receive an S2C_AddStatusEffect message when applying buffs to another party member, and even then, the opcode message does not match the current opcode listed in the config.

**Comment by Soreepeong** [comment]
I've added support referring to [following](https://github.com/ravahn/machina/blob/master/Machina.FFXIV/Headers/Global/Server_EffectResult.cs) , but whether it works I don't know yet. Will have to wait until the servers come up.

**Comment by Elevation1** [comment]
Doesn't seem to be working with the new patch.  Still giving me S2C_ActionEffect01

**Comment by Soreepeong** [comment]
Yes, I didn't update it yet. You can try this test version out. Only exe/dll files are in here; no opcodes or other files.
[Release_a30aefdf.zip](https://github.com/Soreepeong/XivAlexander/files/7750899/Release_a30aefdf.zip)
