### ISSUE TITLE
Anyone found 6.01 opcodes?

### ISSUE THREAD

**Issue by LarxyCouteau** [Soreepeong/XivAlexander#244]
Anyone found opcodes yet? I couldn't figure out how to find them.

**Comment by giatoai159** [comment]
```
{
	"C2S_ActionRequest": "0x0188",
	"C2S_ActionRequestGroundTargeted": "0x02d4",
	"S2C_ActionEffect01": "0x01d0",
	"S2C_ActionEffect08": "0x02b0",
	"S2C_ActionEffect16": "0x02be",
	"S2C_ActionEffect24": "0x0288",
	"S2C_ActionEffect32": "0x0238",
	"S2C_ActorCast": "0x02f2",
	"S2C_ActorControl": "0x01fb",
	"S2C_ActorControlSelf": "0x02c2",
	"S2C_AddStatusEffect": "",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}
```
This is what i can find by following the guide, there's no S2C_AddStatusEffect in the logs though but I can triple weave so it works?

**Comment by priamos1** [comment]
I couldn't follow the guide because when I rightclick on the xivalexander on the windows toolbar the menu I get doesn't look like the menu in the tutorial pic at all. It's missing a lot of the options that it wants me to mess with.

**Comment by MrDarkRainBow** [comment]
```
{
	"C2S_ActionRequest": "0x0188",
	"C2S_ActionRequestGroundTargeted": "0x0188",
	"S2C_ActionEffect01": "0x01d0",
	"S2C_ActionEffect08": "0x02b0",
	"S2C_ActionEffect16": "0x02be",
	"S2C_ActionEffect24": "0x0288",
	"S2C_ActionEffect32": "0x0238",
	"S2C_ActorCast": "0x02f2",
	"S2C_ActorControl": "0x01fb",
	"S2C_ActorControlSelf": "0x02c2",
	"S2C_AddStatusEffect": "0x01d0",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}
```
I got the same results on my end and it seems to be working fine

**Comment by Kawaii-Miku** [comment]
> I couldn't follow the guide because when I rightclick on the xivalexander on the windows toolbar the menu I get doesn't look like the menu in the tutorial pic at all. It's missing a lot of the options that it wants me to mess with. The guide is honestly not very good.

I have the same issue. I don't understand it and the guide is impossible to follow. I just want to reduce the effects of latency.

**Comment by leonglaves** [comment]
> ```
> {
> 	"C2S_ActionRequest": "0x0188",
> 	"C2S_ActionRequestGroundTargeted": "0x0188",
> 	"S2C_ActionEffect01": "0x01d0",
> 	"S2C_ActionEffect08": "0x02b0",
> 	"S2C_ActionEffect16": "0x02be",
> 	"S2C_ActionEffect24": "0x0288",
> 	"S2C_ActionEffect32": "0x0238",
> 	"S2C_ActorCast": "0x02f2",
> 	"S2C_ActorControl": "0x01fb",
> 	"S2C_ActorControlSelf": "0x02c2",
> 	"S2C_AddStatusEffect": "0x01d0",
> 	"Server_IpRange": "0.0.0.0/0",
> 	"Server_PortRange": "1-65535"
> }
> ```
> 
> I got the same results on my end and it seems to be working fine

 how do I apply this properly? When i change my code excluding the bottom two lines it doesnt work.

**Comment by NotRanged** [comment]
Instructions: 
- show the alexander control window (should be in system tray if you've got it hidden
- Configure -> Edit Opcode Configuration
- Overwrite what's there with the above

Works fine for me. Ty for the codes!

**Comment by VanitasDecay** [comment]
> Instructions:
> 
>     * show the alexander control window (should be in system tray if you've got it hidden)
> 
>     * Configure -> Edit Opcode Configuration
> 
>     * Overwrite what's there with the above
> 
> 
> Works fine for me. I didn't skip any lines. Ty for the codes!

Worked like a charm, I'm new to this kind of thing. Ty for the info!

**Comment by TsunStar** [comment]
Tried changing the opcode, still not working, Tried both methods, both overwriting and not overwriting the bottom 2 lines, but i can't get it to work

**Comment by tasuiken** [comment]
what if the config option is just... not there? is there any way to install it manually? i'm not sure what changed, i could access it before 6.01 to change 6.0 opcodes

**Comment by rainbow-shaman** [comment]
If you dont mind me asking, what is OPcode and do we need to change it ? sorry for asking i just found this program yesterday and very new to this
