### ISSUE TITLE
Does anyone find 6.01 opcode?

### ISSUE THREAD

**Issue by LHSVincent** [Soreepeong/XivAlexander#245]
I tried to find the opcode by my own, but I failed. Does anyone find the right one?

**Comment by leonglaves** [comment]
People have posted it in previous issue posts. But im not even sure how to change the opcode because the guide provided in wiki seems out of date. Any help would be appreciated

**Comment by LHSVincent** [comment]
> People have posted it in previous issue posts. But im not even sure how to change the opcode because the guide provided in wiki seems out of date. Any help would be appreciated

It does not work for my actually.
For the opcode, copy the opcode, and overwrite with the latest json file. JP for Japanese server.

**Comment by leonglaves** [comment]
Dont overwrite the bottom two codes.

**Comment by LHSVincent** [comment]
> Dont overwrite the bottom two codes.

Thanks!
