### ISSUE TITLE
having trouble after 6.01

### ISSUE THREAD

**Issue by SpaceIndigo** [Soreepeong/XivAlexander#246]
![image](https://user-images.githubusercontent.com/96485623/146951001-4277069d-24b7-4933-9685-17c17dab20b3.png)
not sure what i should do

**Comment by Heinzen** [comment]
The error message says this file is already being used by another process. Try manually killing alexander/XIV processes and restarting everything else again.

**Comment by Soreepeong** [comment]
The updater will show a better error message from next version. For now, when then message shows up, do as heinzen said.

**Comment by SpaceIndigo** [comment]
> The updater will show a better error message from next version. For now, when then message shows up, do as heinzen said.

getting this message when a try to check for updates

**Comment by Soreepeong** [comment]
I mean, you can always update the program yourself by downloading again.

**Comment by SpaceIndigo** [comment]
> Reference in ne

already tried that but still no luck, dont know whats happening just stopped working after yesterday's patch

**Comment by Soreepeong** [comment]
Yes, the release file hasn't been updated for 6.01 yet. Refer to #244 to get it working again.

**Comment by SpaceIndigo** [comment]
> Yes, the release file hasn't been updated for 6.01 yet. Refer to #244 to get it working again.

oh, cheers mate
