### ISSUE TITLE
Unable to double weave

### ISSUE THREAD

**Issue by VanitasCloud** [Soreepeong/XivAlexander#247]
Since 6.01 I can't double weave as tank or even single weave as SAM

**Comment by Heinzen** [comment]
Did you update the OPCodes?

**Comment by VanitasCloud** [comment]
> Did you update the OPCodes?

oh, how I do that?

**Comment by Heinzen** [comment]
It is explained in this other issue. https://github.com/Soreepeong/XivAlexander/issues/244

**Comment by VanitasCloud** [comment]
Ty so much, now I can double weave again in both jobs. Also, ty for making this plugin, it makes the game playable in Argentina.
