### ISSUE TITLE
Crashing on gathering.

### ISSUE THREAD

**Issue by Nothinghan** [Soreepeong/XivAlexander#248]
Last update and today update's, give me a crash sometime when im starting gathering.  I have been playing for 9 hours today, leveling up and everything was ok, but at the moment i've started gathering, XivAlexander crashend, closing FFXIV.

**Comment by Soreepeong** [comment]
* Does attempting to gather on another node make any difference, or are those all the same?
* Try disabling all network related features. Does it help?
* Do you have modding enabled? If then, does turning it off help?

**Comment by Nothinghan** [comment]
1 - It happens randomly. Sometimes on the first 3 nodes, other times, 20 min Gathering. - This part of the test i've made with Alexander on and Off. On, as mentioned before, Off, normal, no crashes.
2 - Could you please, explain this method?
3 - Only Gshade. Tested with Gshade on and off, same results as mentioned above. Do not appear to interfere on the Alexander.

**Comment by Soreepeong** [comment]
2. Turn all checkboxes off from Networking menu in XivAlexander control window.
3. I'll take that as you aren't using XivAlexander's modding features.

Also, by crashing, did it show any error message, or did it just silently quit? If it's the former case, try to export the log file first.

**Comment by Soreepeong** [comment]
1. Right click on Start button.
2. Click on "Computer Management".
3. Navigate to "System Tools" > "Event Viewer" > "Windows Logs" > "Application".
4. See if there's any error entry mentioning the game, and if you find any, let me know what it says below. 

![image](https://user-images.githubusercontent.com/3614868/147187040-85d48c64-f8b8-4603-ad6c-7d50c02b36ec.png)

**Comment by Nothinghan** [comment]
2 - Ok, i will do that tomorrow. I was not aware of those options, i've just instaled and used.
3 -  As per iten 2, i've just installed and used Alexander, no modifications performed.  I use the Launcher from Steam.

Related to the event viewer, this can be a little bit complicated. Im from Brazil, and thanks for your hardwork, that make possible for LA players, play better. So, the event viewer is on Portuguese.

![image](https://user-images.githubusercontent.com/16171360/147187305-ca12c533-ce33-40bd-b1d2-1d5cac9af458.png)

![image](https://user-images.githubusercontent.com/16171360/147187350-ba5acb45-5ac3-44f9-b180-b5c5d4909e05.png)

![image](https://user-images.githubusercontent.com/16171360/147187438-99f93638-c46a-460a-93ea-81dae7b21247.png)

![image](https://user-images.githubusercontent.com/16171360/147187481-3b56f034-1f4c-466e-84f7-1ee5aeed9839.png)

**Comment by Nothinghan** [comment]
![image](https://user-images.githubusercontent.com/16171360/147187654-226155e9-5c83-4b18-89f4-abc9ac12dc95.png)
I always have been installing with the first option, this could be the issue?

**Comment by Soreepeong** [comment]
[Release_959687d.zip](https://github.com/Soreepeong/XivAlexander/files/7767523/Release_959687d.zip)

Can you use this instead (just press on the first installation option again), and see if the error window pops up, and when it does, press on `Export Logs` and upload it.

**Comment by Nothinghan** [comment]
Will do, thanks.

**Comment by Nothinghan** [comment]
[XivAlexander_20211227_132949_697.log](https://github.com/Soreepeong/XivAlexander/files/7780984/XivAlexander_20211227_132949_697.log)

**Comment by Soreepeong** [comment]
Is this crash about gathering? The error message (DirectX error) itself suggests that the error happened outside of the reasons from XivAlexander since this programs touches nothing about DX.
