### ISSUE TITLE
Seems to be not working after 6.01 patch

### ISSUE THREAD

**Issue by lplp21** [Soreepeong/XivAlexander#249]
It looks like it functions all normal but logs does not show any recordings of shortened delays.
Is it currently not functioning?

**Comment by Soreepeong** [comment]
Did you update?

**Comment by lplp21** [comment]
I did. 
I'm just reinstalling again checking for if I missed sth

**Comment by Soreepeong** [comment]
Post the logs, and let me know if you're using a VPN, and if then, which one it is.

**Comment by lplp21** [comment]
Working fine after reinstallation. I guess sth was screwed up after deletion
ty
