### ISSUE TITLE
"Unnatural" 1.5 GCD clip

### ISSUE THREAD

**Issue by man-im-unoriginal-af** [Soreepeong/XivAlexander#25]
https://user-images.githubusercontent.com/31392390/109601261-79c21380-7b59-11eb-9540-0b985feb1344.mp4

This is **definitely** going to look like a cheat if it isn't already. This should probably be manually disabled

**Comment by Soreepeong** [comment]
Your video: 
* 0.099 -> 1.532
* 1.700 (168ms)
* 2.466 (766ms)
* 3.066 (600ms)

https://user-images.githubusercontent.com/3614868/109602961-741dfb00-7b64-11eb-82b2-9ad38c8c0b27.mp4


Mine (Playing on KR, without XivAlexander enabled)
* 0.166 -> 1.649
* 1.766 (123ms)
* 2.399 (633ms)
* 3.016 (617ms)

I personally don't see a problem.
