### ISSUE TITLE
not sure what to call this but 

### ISSUE THREAD

**Issue by STALAGMO** [Soreepeong/XivAlexander#250]
i got this showing up in the log viewer and the program isnt working anymore for me even tho i updated and all and tried todo a fresh install still get the same thing and doesnt work
![ztkk](https://user-images.githubusercontent.com/96582506/147251466-65381186-53e9-4a0a-831a-c2a3679993f1.png)

**Comment by oultrox** [comment]
It happened to me once and I just had to unload the program and load it inside the running game. Not sure if it works for ya or you have tried already.

**Comment by Soreepeong** [comment]
That error means that the program failed to read latency information. I think you can ignore that for now. Open up opcodes window by pressing `O` key on the main window or using `Configure > Edit Opcode Configurations`, and see if it matches [this](https://github.com/Soreepeong/XivAlexander/blob/main/StaticData/OpcodeDefinition/game.JP.2021.12.16.0000.0000.json) file. If it does, try checking all in `Network > Troubleshooting`.

**Comment by striderik** [comment]
I also started having this issue which started 4 days ago, same message on log viewer, program opens just fine but its not working and i dont get the logs showing latency and ping whenever i use an action
if the info on my opcodes doesnt match the one you linked, should i make changes?
so far only tried checking all in network > troubleshooting but wont work
ty

**Comment by STALAGMO** [comment]
> I also started having this issue which started 4 days ago, same message on log viewer, program opens just fine but its not working and i dont get the logs showing latency and ping whenever i use an action if the info on my opcodes doesnt match the one you linked, should i make changes? so far only tried checking all in network > troubleshooting but wont work ty

well for me what i did is i uninstalled  XIValexander from The game files since i had it installed then i deleted all the XIValexander files i had on my pc, after that i went back here downloaded the latest version which Has number 41 in it make sure yours is the latest aswell after that i started to just turn it on when im ingame so i just loging get into the instance and then run xiv alexander and use option loadonce and i stopped having issues so far
