### ISSUE TITLE
I love this tool. I have a simple question.

### ISSUE THREAD

**Issue by oultrox** [Soreepeong/XivAlexander#252]
This tool singlehandedly restore my faith in my rotations and my DRK and I seriously love it. Is there a way to support you or donate?

**Comment by KeysFate** [comment]
How long you been using it? Been thinking to get into it and also donate if it works that well

**Comment by oultrox** [comment]
I have almost a week using it. It's just amazing. It feels such smooth my gameplay now. I regret 0. Just touch the opcodes when needed and you set, and also it has so much support and engineering. I love it

**Comment by oultrox** [comment]
It may also be the first time I'm experiencing latency less than 100ms in a mmo in a kind of way, which is why I feel it unreal but it's so much pleasant.

**Comment by Soreepeong** [comment]
Thanks for the idea, but it'll be alright.

**Comment by oultrox** [comment]
That's okay. At least I wanted to let you know that you're awesome and your tool is the best. 

> Thanks for the idea, but it'll be alright.
