### ISSUE TITLE
Dalamud Support?

### ISSUE THREAD

**Issue by Sequincer** [Soreepeong/XivAlexander#253]
Any plans to make a dalamud plugin for high latency mitigation? Are any of the alternatives like DoubleWeaver or NoClippy any good from a reliability and safety point of view?

**Comment by Soreepeong** [comment]
This program does not need to be a Dalamud plugin, and it won't be registered to the main plugin repository even if I made one, forcing you to use external repository. At that point, it isn't different much from installing XivAlexander separately.
