### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#254]
![캡처](https://user-images.githubusercontent.com/82459386/147320178-6f2dc20f-70fa-48ee-8135-1cead5cb83d2.JPG)

What do the highlighted lines mean? Does it mean that XivAlexander is not working properly?
How do I go about solving the problem?

Thank you.

**Comment by Soreepeong** [comment]
It means that the target servers do not support pinging. It checks out, as Korean xiv servers will reject ping requests. You can just ignore it.

**Comment by justin767** [comment]
> It means that the target servers do not support pinging. It checks out, as Korean xiv servers will reject ping requests. You can just ignore it.

Thanks. By looking at my ping and other latency status, would you recommend I go about using Mode 2 or Mode 3 for latency mitigation? My VPN gives me 140ms ping in average.

**Comment by Soreepeong** [comment]
I recommend Mode 2 for your case, as it looks like your vpn also is preventing XivAlexander from measuring accurate latency.

**Comment by justin767** [comment]
> I recommend Mode 2 for your case, as it looks like your vpn also is preventing XivAlexander from measuring accurate latency.

Thanks again. Sorry to keep bothering you but just one more question. I still can't seem to use the 'check for updates' button. Whenever I click it the below image pops up. (I'm using the newest release).
Do you think it's safe to just ignore it? I don't really care for this function, I just need the latency mitigation and double weaving to work.
![1](https://user-images.githubusercontent.com/82459386/147320761-e6567d25-a778-4c2c-aaf7-1d8a1f19691c.JPG)

**Comment by Soreepeong** [comment]
Just download the new release from github and install it again, and make sure to turn off all instances of the game when updating/installing. That message means that some file wasnt copied correctly on installation.

**Comment by justin767** [comment]
> Just download the new release from github and install it again, and make sure to turn off all instances of the game when updating/installing. That message means that some file wasnt copied correctly on installation.

I did exactly the same thing but it keeps showing up.. I don't know why it's happening

**Comment by justin767** [comment]
> Just download the new release from github and install it again, and make sure to turn off all instances of the game when updating/installing. That message means that some file wasnt copied correctly on installation.

When I try to unload XivAlexander on the control window, this also shows up.
![2](https://user-images.githubusercontent.com/82459386/147321129-58a62044-74b2-42ba-9b1b-62e7d4ca0bc8.JPG)

**Comment by Soreepeong** [comment]
It's normal if you installed it. Also, you can probably ignore that error message, if the program works correctly otherwise. All that Check for Updates button does is opening github page anyway.

**Comment by justin767** [comment]
> It's normal if you installed it. Also, you can probably ignore that error message, if the program works correctly otherwise. All that Check for Updates button does is opening github page anyway.

Are there any additional folder/file other than XivAlexander folder itself that I have to delete for complete removal of XivAlexander before re-installing? Like appdata or something..

**Comment by Soreepeong** [comment]
%APPDATA%/XivAlexander and %LOCALAPPDATA%/XivAlexander are the two folders.

**Comment by justin767** [comment]
> %APPDATA%/XivAlexander and %LOCALAPPDATA%/XivAlexander are the two folders.

Well still the same problem? But these problems have nothing to do with the functioning of latency mitigation right? That's all what matters to me really..

**Comment by Soreepeong** [comment]
Yeah, it should just work.

**Comment by justin767** [comment]
> Reference in new issu

Sorry, I deleted the file and attempted re-installing it, but whenever I load the game, this msg shows up and I am unable to load XivAlexander..
![1](https://user-images.githubusercontent.com/82459386/147322780-6accc247-9e98-4cb0-bf0a-fe32c1414fd9.JPG)

**Comment by Soreepeong** [comment]
If installing did not work, then copy all files into that directory (%LOCALAPPDATA%/XivAlexander), and try again.

**Comment by justin767** [comment]
> If installing did not work, then copy all files into that directory (%LOCALAPPDATA%/XivAlexander), and try again.

You're the best. Check for updates function now works too. Thank you.
