### ISSUE TITLE
Latency mitigation not working

### ISSUE THREAD

**Issue by Aevanathema** [Soreepeong/XivAlexander#255]
So, since the 6.01 update happened I can no longer double weave w/ the latency mitigation (it used to be perfectly smooth). I checked opcodes, the default values were correct- I'm on the most updated version of xivAlexander.

**Comment by oultrox** [comment]
Works for me without problems. 

Pleasse ensure you have this in your OPcodes. 
`{
	"C2S_ActionRequest": "0x0188",
	"C2S_ActionRequestGroundTargeted": "0x02d4",
	"S2C_ActionEffect01": "0x01d0",
	"S2C_ActionEffect08": "0x02b0",
	"S2C_ActionEffect16": "0x02be",
	"S2C_ActionEffect24": "0x0288",
	"S2C_ActionEffect32": "0x0238",
	"S2C_ActorCast": "0x02f2",
	"S2C_ActorControl": "0x01fb",
	"S2C_ActorControlSelf": "0x02c2",
	"S2C_AddStatusEffect": "",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}`

**Comment by Aevanathema** [comment]
Perfect, thank you. I was struggling a bit with the OPcodes it seems. :)
