### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by VynIyrnberk** [Soreepeong/XivAlexander#256]
Hi, i just updated to the latest version (as of 17 hrs ago) and it randomly crashes FF for me. I tried with both textools and without and it crashes both instances 

I attached the log when the error window popped out
[XivAlexander_20211226_202848_231.log](https://github.com/Soreepeong/XivAlexander/files/7776981/XivAlexander_20211226_202848_231.log)

**Comment by Soreepeong** [comment]
The error looks like something about DirectX 11, which XivAlexander doesn't touch at all. Can you try disabling all other plugins, including Dalamud?

**Comment by VynIyrnberk** [comment]
I will give it a try and get back to you :D

**Comment by VynIyrnberk** [comment]
Hi would just like to update:
So far I let the game run for an hour, didnt crash even once, so it's probably something with Dalamud

Thank you for the assistance! I'll update again if it'll crash
