### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by Heinzen** [Soreepeong/XivAlexander#258]
Has Alexander been tested for the MacOS version of the game?

**Comment by retaker** [comment]
Use [XivMitmLatencyMitigator](https://github.com/Soreepeong/XivMitmLatencyMitigator) instead if you're on Mac OS, Game Consoles(PS4/PS5), or want to apply this solution to a custom VPN server running on Linux operating system.

**Comment by Soreepeong** [comment]
I have no idea. You'll have to see whether it works. One thing I know is though that the installing mode won't work. If it works, then you'll be using Load once.
