### ISSUE TITLE
Question on obtaining ActionRequest2 using IPC type finder

### ISSUE THREAD

**Issue by hyskylord** [Soreepeong/XivAlexander#26]
Hi,
  Here is a question about how to obtain ActionRequest2 opcodes. I'm parsing on NA datacenter with all jobs I have but couldn't find the "RequestUseAction2": "0x03a0" type. Thanks.

**Comment by Soreepeong** [comment]
I'll update the readme soon. Meanwhile, can you see if ground targeted actions generate that message? The only reason I know that this message exists is that PvP Shukuchi generated this message.

**Comment by hyskylord** [comment]
Yes, healer's ground healing actions (Asylum/Sacred Soil/Earthly Star) will generate this. I don't have other jobs with ground targeted actions but I think this is the case.
