### ISSUE TITLE
Possible TODOs

### ISSUE THREAD

**Issue by Soreepeong** [Soreepeong/XivAlexander#260]
1. Reduce cooldowns by measured immediate fps (interval of PeekMessage returning nothing)
2. If there is an upcoming cooldown/animlock expiry during rendering next frame, pause the game, and resume the game when cooldown expires(+1ms?)

First, check if this is necessary, by seeing outgoing network traffic timestamps, and checking whether all interval is above supposed cooldown

--

* Reflect filesystem folder structure in TexTools mod menu
* Make a control(window) for configuring individual modpacks
* Ditch menus and make a real config window?

**Comment by oultrox** [comment]
Do you have in mind which jobs are going to be affected by this?

**Comment by Soreepeong** [comment]
All jobs for sure, as this should prevent gcds from being delayed by like up to 16ms.

**Comment by oultrox** [comment]
Ah great. Just got a bif confused with the issue title; Sounds pretty cool that delay reduction (Altho I for I, I'm perfect with what I got).
