### ISSUE TITLE
Game process doesn't end after installing

### ISSUE THREAD

**Issue by shugoliven** [Soreepeong/XivAlexander#262]
Hi, ever since I installed Xivalexander, everytime I exit the game, it just goes on a black screen and the process keeps running, I need either to end it via Task Manager or "Force Exit Game" on Xivalexander tray icon.

Is this a known issue? I've searched and found nothing. Is there any option I need to choose here?

Thanks in advance.

**Comment by Soreepeong** [comment]
While that doesn't happen on my side, I've added an option to make XivAlexander skip cleanup process and just terminate itself when the game itself requests to quit. It will be accessible from Configure menu on the control window, once it's released.

**Comment by shugoliven** [comment]
Thank you very much! :)

**Comment by Soreepeong** [comment]
If the game does not quit even after the upcoming release, then you'll have to share me the logs, so that I can see whether other addons might be interfering with normal exit process.

**Comment by CharonM72** [comment]
In my case I notice FFXIV sits on a black screen after exiting for about 30 seconds or so before it eventually closes. I'm pretty certain this is related to XIVAlexander being installed so yeah I can confirm this as well.
