### ISSUE TITLE
Modifying the EXDF Transformation Rules

### ISSUE THREAD

**Issue by neo-royalty** [Soreepeong/XivAlexander#264]
I'd like to modify the game's script in a way that changes just the NPC dialogue to Japanese but keeps the rest of the UI in English, so basically the same as the language learner tool but without the English text in the textboxes and without the Japanese text in the rest of the UI elements (I know I'll probably run into some issues trying to guess the right romanization/katakana names and stuff at times, but I'll cross that bridge when I get there)

Are there some quick edits I could do to the json to accomplish that?

**Comment by Soreepeong** [comment]
There are multiple places you'll get dialogues, and it's kind of impossible to get it correct all the time. That said, what you want is in `sentence` and `mixed` target groups. Grab `EnglishWithJapanese_SayQuestJapanese.json`, and modify the rules to contain only the following:

```json
{
    "targetGroups": ["sentence", "mixed"],
    "replaceTo": "{2}"
}
```

**Comment by neo-royalty** [comment]
Fair enough. Will try once I can safely log out and back in again without being hit by a 1k+ queue, thanks.

**Comment by Soreepeong** [comment]
Remvoe `CompanionTransient`, `ContentFinderConditionTransient`, and other stuff ending with `Transient` to prevent descriptions of something from being displayed in Japanese. You might want to grab FFXIV Explorer or Godbert and see which files listed in `sentence` group contain stuff you do not want translated in Japanese, and then remove those lines.

**Comment by neo-royalty** [comment]
Thanks a lot for your help, it's doing exactly what I was hoping for now. Awesome tool
