### ISSUE TITLE
Controller Inputs Disabled After New Update

### ISSUE THREAD

**Issue by jekyll87** [Soreepeong/XivAlexander#266]
Conditions:
- Booted game through normal launcher (no ACT or XIVLauncher)
- Enabled XIVAlexander

Results:
- Controller inputs and click inputs on crosshotbar become disabled. I.e. I can't press either the button on controller or click on the action with mouse. Controller will work fine on menus. I tried everything including a full reboot and only able to replicate when I boot up the latest version of XIVAlexander

**Comment by jekyll87** [comment]
Additionally, I noticed unloading XIVAlexander will not fix the issue. A full reboot of the game is required without booting up XIVAlexander in order for the inputs to be enabled again.

**Comment by Soreepeong** [comment]
I just checked, and gamepad works fine for me, regardless of whether the addon installed, or when doing Load Once. Are you on default XivAlexander configuration? Try turning off the new features (synchronize framerate), and see whether it makes any difference. If it doesn't, then you'll have to find more specific conditions to trigger input getting disabled,

**Comment by jekyll87** [comment]
I am on default configuration so let me try disabling new features to check if it resolves.

**Comment by jekyll87** [comment]
Just went back and this version of XiVAlexander causes my game to not allow me to interact with anything other than menus (originally thought it was just abilities because I was in an instance), I wasn't able to teleport, interact with NPCs, or use the hotbar.. It doesn't seem to be specific to controller. Removed the updated feature as well and still occurred. Rolled back and works fine. May be an isolated incident for me though? Difficult to troubleshoot since I have to restart the game with a 1K person queue. Is there a file I can provide?

**Comment by jekyll87** [comment]
Update: "Issue Inputs disabled after a single action #267" seems to be identical to mine.

**Comment by Amiral-Benson** [comment]
I got the same issue, _Load once_, default configuration, French client.
Unloading didn't fix the issue.

**Comment by Soreepeong** [comment]
Can you share the log file when no further actions become possible?

**Comment by Soreepeong** [comment]
I'll manage stuff in #267. Please post additional information to that issue.
