### ISSUE TITLE
Inputs disabled after a single action

### ISSUE THREAD

**Issue by MatLauar** [Soreepeong/XivAlexander#267]
I tried it twice today with the latest vesion. I play on a keyboard and after using a single action, every other action was "softlocked", as in none of them could be used. The conditions were as follows:

1st try:
 - Installed XivAlexander as d3d9 and d3d11
 - Set it to run th game launcher and load xivalexander when game has started.
 - logged into the game
 
 2nd try:
 - uninstalled xiv alexander
 - opened the game
 - Load xiv alexander

Used a single weapon action (true thrust as a drg on a striking dummy) on the first try, and afterwards all actions were "disabled". 
The input was still going through as I could still walk, open menus, get into a dungeon by myself, switch jobs, chat, emote and my hotbars were still "clicking". I could not execute any actions, teleport, or enter a house.

On the second try I used second wind with the same results.

**Comment by Josiki121** [comment]
I'm also having the same issue after 1 action all the other are disabled I tried on battle classes and crafting class and the result was the same

**Comment by Soreepeong** [comment]
1. Everything works fine.
2. You use a weaponskill/spell/ability.
3. No further weaponskill/spell/ability works, but you can access everything else.

Is this right?

* Can you check whether https://time.is/ reports a huge time drift?
* Does this only happen on the latest version (.44)? Does it not happen on .43?

**Comment by nikolai-stem** [comment]
good day, also confirming this issue occurs on latest release (.44) with mouse/keyboard input as well
1) start FFXIV
2) start XIVAlexander
3) Press any key bound to hotbar
4) Actions occurs, subsequent key presses or mouse clicks do not trigger any actions
 - icons do not flash, no action occurs

Issue is not present on .43

**Comment by Soreepeong** [comment]
Can you share the log file when no further actions become possible?

**Comment by MatLauar** [comment]
>     * Can you check whether https://time.is/ reports a huge time drift?

There is no time drift.

>     * Does this only happen on the latest version (.44)? Does it not happen on .43?

Yes, I tested .43 and it worked like a charm.

>     * By "actions not working", does hotbar icon not flash at all, or it does display keypress/click effect but results in nothing?

The hotbar icons do flash, but it results in nothing. 

Here are the logs from before I tried turning off Force the Game to Use More CPU Time:

[XivAlexander_20211231_084314_609.log](https://github.com/Soreepeong/XivAlexander/files/7796098/XivAlexander_20211231_084314_609.log)

And here are the files from after I turned it off:

[XivAlexander_20211231_084730_849.log](https://github.com/Soreepeong/XivAlexander/files/7796100/XivAlexander_20211231_084730_849.log)

Here are the log files from the test release(same issues):

[XivAlexander_20211231_085650_290.log](https://github.com/Soreepeong/XivAlexander/files/7796109/XivAlexander_20211231_085650_290.log)

**Comment by Soreepeong** [comment]
Thank you for the log files. It does indicate problems. I'll see what's causing animlock adjustments to become wrong.

**Comment by Soreepeong** [comment]
Try this one. While I don't know what is causing this, this change will prevent providing the game with excessive animation lock duration information. Share the logs when you test this one, too. Turn IPC Finder off when you aren't using it, so that log file doesn't get unnecessarily large.
[XivAlexander_96e89cf.zip](https://github.com/Soreepeong/XivAlexander/files/7796289/XivAlexander_96e89cf.zip)

**Comment by jekyll87** [comment]
I tried that one and it does not seem to lock up the game. Here's the log

[XivAlexander_20211231_083817_850.log](https://github.com/Soreepeong/XivAlexander/files/7796319/XivAlexander_20211231_083817_850.log)
:

**Comment by Soreepeong** [comment]
The log looks fine, as in the problem that I suspected (uninitialized variables which should have been initialized) looks fixed. Can you weave stuff comfortably? Also, try turning back on the other configuration that I suggested to turn off, like "Force the game to use more CPU" and "Synchronized framerate" stuff.

**Comment by jekyll87** [comment]
I actually had the other stuff on during the above log. I can weave comfortably as well.
