### ISSUE TITLE
XivAlexander not autolaunching when installed

### ISSUE THREAD

**Issue by Thorgak** [Soreepeong/XivAlexander#268]
This only started becoming a problem for me since endwalker but when starting the game the program doesn't auto launch, I don't get any error messages or problems to indicate why and when using load once it works fine so i've been using that as a workaround.

Have tried uninstalling and reinstalling while deleting the config files that the installer prompts me to as well as doing that process in Administrator but no success. The installation seems to be successful each time but then the program doesn't launch. I'm using the quick launcher and have gshade installed.

**Comment by Soreepeong** [comment]
I guess it doesnt exactly work too well with gshade then. I'll see if anything can be done about it. Meanwhile, maybe try installing as DInput8?

**Comment by Thorgak** [comment]
Tried installing as DInput8 with no success, tried uninstalling gshade and reinstalling xivalexander but also no success so seems unrelated to gshade? Any other suggestions on things to try or information that can help?

**Comment by Thorgak** [comment]
Potentially on an unrelated matter - XivAlexander just errored after having reinstalled and using the latest version, not sure if this warrants creating a separate issue, here's the log file.
[XivAlexander_20211231_202308_906.log](https://github.com/Soreepeong/XivAlexander/files/7796998/XivAlexander_20211231_202308_906.log)

**Comment by Soreepeong** [comment]
1. I've confirmed that GShade works fine, if XivAlexander installer is ran after GShade installation.
2. That error log looks like nvidia drivers did something bad. XivAlexander just tries to catch all error and show, and this one probably isn't about XivAlexander.

Open up your FFXIV installation folder, go into `game` folder, and right click on `d3d11.dll` and open Properties to confirm that it's XivAlexander dll. If it's not, then run the installer again. Otherwise, I can't think of reasons that it wouldn't work at the moment.

**Comment by Thorgak** [comment]
Just confirmed the d3d11.dll file is the XivAlexander one and the program still didn't launch, there is another d3dd11.dll thats a .syslink file showing it belongs to GShade, could this be causing problems?

**Comment by Soreepeong** [comment]
Can you take a screencap of the game folder? Also, just to check, if you completely get rid of GShade, does it work? By completely removing it, you also need to delete symlink file from game directory.

**Comment by Thorgak** [comment]
I believe the other day when I first opened the ticket I tried uninstalling both XivAlexander and GShade and then reinstalling XivAlexander alone and the problem was still there. I didnt delete the Symlink file though, I'll give that a try now. 
![image](https://user-images.githubusercontent.com/33519408/147863167-0b0e6e60-3374-4e0e-8b39-0e441d148ff4.png)

**Comment by Thorgak** [comment]
After uninstalling GShade and deleting the symlink file and reinstalling XivAlexander alone the problem still persists. My folder now looks like this: 
![image](https://user-images.githubusercontent.com/33519408/147863270-51d4a8ff-ab71-4505-9dd8-94fad1b56ce0.png)

**Comment by Thorgak** [comment]
Finally managed to resolve the problem - had the error pop up again relating to display drivers so I updated them and after restarting the PC XivAlexander automatically launched as intended. Thanks for the assistance and sorry for any hassle as a result of me not updating drivers, sort of surprised that turned out to be the solution though.
