### ISSUE TITLE
Will this make playing in NA server from Korea possible?

### ISSUE THREAD

**Issue by totlwkr43753** [Soreepeong/XivAlexander#271]
Hi, my friend just introduced this add-on to me.
I recently moved to Korea and was wondering if this would make playing in NA data center viable from Korea.

I noticed the gifs you included in the introduction, where you played in Balmung from Korea. How was it? Is the high ping (150ms) almost of no issue with the program?

Thanks, and happy new year.

**Comment by Soreepeong** [comment]
It's around 140ms, and it works just fine with the program.

**Comment by totlwkr43753** [comment]
Awesome, do you also play in NA dc from Korea?

**Comment by oultrox** [comment]
I play from Chile to NA. 180 ms around. Works like I was in NA totally ... like  75ms.

**Comment by totlwkr43753** [comment]
> I play from Chile to NA. 180 ms around. Works like I am in NA totally ... like 75ms or even less.

No kidding! Which latency mitigation mode do you use among the three options? I'm trying out each one but they all feel the same to me lol.

**Comment by oultrox** [comment]
I'm using the default configuration on this matter which is Mode 3: Simulate Normalized RTT and Latency.
