### ISSUE TITLE
xivalex version doesn't change when updating from 1.14.8.44 to .45

### ISSUE THREAD

**Issue by randomxivraider** [Soreepeong/XivAlexander#272]
i tried the update option from Check Updates prompt on the app itself and clean reinstall from downloading the latest zip under Release section. Still when you run alex, it's under 1.14.8.44

**Comment by Soreepeong** [comment]
I probably didn't update version names correctly. You can use it as-is for now.

**Comment by randomxivraider** [comment]
> I probably didn't update version names correctly. You can use it as-is for now.

thanks Soree
