### ISSUE TITLE
Constant game crashing issue

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#275]
Hello,

My game client is constantly crashing with the following message log.

Thanks.

[XivAlexander_20220101_135627_569.log](https://github.com/Soreepeong/XivAlexander/files/7798162/XivAlexander_20220101_135627_569.log)

**Comment by Soreepeong** [comment]
Try turning off framerate and cpu related settings from Configuration menu, and see if it still happens. Don't forget to test stuff out after disabling/uninstalling XivAlexander, too.

**Comment by justin767** [comment]
> Try turning off framerate and cpu related settings from Configuration menu, and see if it still happens. Don't forget to test stuff out after disabling/uninstalling XivAlexander, too.

I deleted XivAlexander and all the relevant files in appdata. Upon re-downloading, should I run XivAlexander first before loading the game client for initial setup? How should the steps be?

**Comment by justin767** [comment]
> Try turning off framerate and cpu related settings from Configuration menu, and see if it still happens. Don't forget to test stuff out after disabling/uninstalling XivAlexander, too.

<img width="576" alt="1" src="https://user-images.githubusercontent.com/82459386/147862754-3280a79b-7db9-4de5-bde8-e66fb0fe6eba.png">
I disabled these two options and suddenly XivAlexander got downgraded to 1.14.8.44 for some reason..
What do these two options do exactly?

**Comment by justin767** [comment]
> Try turning off framerate and cpu related settings from Configuration menu, and see if it still happens. Don't forget to test stuff out after disabling/uninstalling XivAlexander, too.

![1](https://user-images.githubusercontent.com/82459386/147862871-83d807fe-2cda-4a59-b156-cfa4c0723886.JPG)
It's keep happening

**Comment by justin767** [comment]
> Try turning off framerate and cpu related settings from Configuration menu, and see if it still happens. Don't forget to test stuff out after disabling/uninstalling XivAlexander, too.

![1](https://user-images.githubusercontent.com/82459386/147863034-36dbd2ac-fa30-4ddf-a69f-9a86a7c288e1.JPG)
this also pops up when I click check for updates

**Comment by Ustymk** [comment]
The big error is the same one I get when my game closes as I hit logout.

**Comment by Soreepeong** [comment]
Let me know if [1.14.8.43](https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.8.43) works fine. Also, if you can, can you pinpoint the version that started to cause the errors?

For the last error message, it probably is about Github rate limiting. Also, since something with your installation was wrong, it probably is creeping up again. Check if a file named `config.xivalexinit.json` exists in game installation directory; if it does, delete it, and try reinstalling XivAlexander.

**Comment by justin767** [comment]
> 

I tried running XivAlexander with the new fps option turned off. So far it's working fine.

**Comment by justin767** [comment]
> Let me know if [1.14.8.43](https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.8.43) works fine. Also, if you can, can you pinpoint the version that started to cause the errors?
> 
> For the last error message, it probably is about Github rate limiting. Also, since something with your installation was wrong, it probably is creeping up again. Check if a file named `config.xivalexinit.json` exists in game installation directory; if it does, delete it, and try reinstalling XivAlexander.

I tried running XivAlexander with the new fps option turned off. So far it's working fine, and for some reason, I feel like it's harder for me to double-weave with this option turned on. I get around 80~100 fps during battle.
