### ISSUE TITLE
Game Freezes then Crashes During Login Queue

### ISSUE THREAD

**Issue by Ustymk** [Soreepeong/XivAlexander#276]
My game keeps crashing after it launches and I am waiting in queue the game client freezes and won't respond. I tried manually uninstalling xivalexander then running the game only to reinstall by loading once when already past the queue. However, when I relaunch the game it still continues to crash mid queue logging into my character. I even did a file restore and fresh install of ffxiv, this did not fix the crashing with xivalexander.

**Comment by Soreepeong** [comment]
So you uninstalled XivAlexander, and turned on the game, but it crashed while logging in, even before doing load once with XivAlexander?

**Comment by Ustymk** [comment]
Yea what I would have to do to go around the game freezing is uninstall xivalexaner, launch the game, get past the queue, then install xivalexander and load once. 

But I recently also installed the Immerse Gamepack FINAL which is the better sound demo for ffxiv for positional audio. It's possible that there is a conflict between the new audio system ffxiv has and xivalexander.

**Comment by Ustymk** [comment]
It's also worth noting that I launch ffxiv through Steam launcher and not the direct Square Enix launcher or a 3rd party launcher. Maybe this is a problem with Steam. The only other program I run alongside xivalexander is ExitLag as a vpn to reduce my ping and stabilize my connection.

**Comment by Ustymk** [comment]
Maybe I am hitting load once after installation when xivalexander is already running? Could that be causing a crash on login?

**Comment by Ustymk** [comment]
After some troubleshooting (uninstalling and reinstalling, manual installation, settings tweaking) I have come to the conclusion that theres something going on with the autoloading so I am forced to use load once every time for now until I figure out what is causing the crashes.

**Comment by OAHaegt** [comment]
I'm having the same issue——just that I am not launching it through steam, but with the Shengqu launcher since I am playing in Chinese server. The game just freezes to Not Responding when I launch it without any error messages, but it is launchable with Alex uninstalled.

**Comment by OAHaegt** [comment]
Update: I originally installed XivAlex as d3d9 and d3d11, but after reinstalling it using dinput8.dll for dx11, this was fixed.

**Comment by justin767** [comment]
> Update: I originally installed XivAlex as d3d9 and d3d11, but after reinstalling it using dinput8.dll for dx11, this was fixed.

Do you no longer crash?

**Comment by justin767** [comment]
> Update: I originally installed XivAlex as d3d9 and d3d11, but after reinstalling it using dinput8.dll for dx11, this was fixed.

What's the difference between 1st and 2nd installation options?

**Comment by OAHaegt** [comment]
> > Update: I originally installed XivAlex as d3d9 and d3d11, but after reinstalling it using dinput8.dll for dx11, this was fixed.
> 
> What's the difference between 1st and 2nd installation options?

Well, I thought it was fixed since I was able to launch the game without crash for a few times, but now it begins to crash again. I suppose that this is not the issue.

**Comment by Soreepeong** [comment]
Can you run `FINAL FANTASY XIV System Information` and post the result? This probably is about XivAlexander conflicting with some other software, so seeing a list of installed and/or running problems may help. Also, if you can, find the log in Event Viewer and post; refer to [this](https://github.com/Soreepeong/XivAlexander/issues/248#issuecomment-1000030610) for how.

**Comment by OAHaegt** [comment]
![image](https://user-images.githubusercontent.com/54366667/147993822-ce5039f6-c043-4f84-87b8-5fa871354c34.png)
![image](https://user-images.githubusercontent.com/54366667/147993858-fac61466-a525-45c0-ac24-ce35edd33541.png)
These are the error log from the Event Viewer for two of the crashes. I will post what FINAL FANTASY XIV System Information says in the next comment.

**Comment by Soreepeong** [comment]
Is the `.NET Runtime` error above the second pic about xiv, or is it irrelevant?

**Comment by OAHaegt** [comment]
![image](https://user-images.githubusercontent.com/54366667/147994152-3f066e7e-5a1d-4151-ae31-af58aa4361de.png)
I think that one is about ASUS's armoury crate application. Not sure if this is relevant. Also, how do I find the FINAL FANTASY XIV System Information executable?

**Comment by OAHaegt** [comment]
![image](https://user-images.githubusercontent.com/54366667/147994237-59fdefa9-2ddf-43ad-9d8e-7a86e1623dcb.png)
The one below is relevant though.

**Comment by Soreepeong** [comment]
It is only present for international release. Seeing that it's crashing on Chinese client though, maybe it's about difference in 5.5x and 6.0x?

Try the latest version, and try turning off all features you can from the menu, and can you see whether it doesn't crash?

**Comment by OAHaegt** [comment]
I am also playing endwalker on MANA, and Alexander on the international version is working perfectly for me, but some other people in the thread also saying that their 6.0x international version is also crashing? I just installed v1.14.8.43 on Chinese client, and the first launch didn't crash. I will try restarting it for a few times and see if it is working as expected.

**Comment by Soreepeong** [comment]
If it crashes on .43, then it probably is a different problem you're having, as it looked like other people were having issues with the features introduced in .44. In any case, disabling all features and seeing whether it works is a good place to start!

**Comment by OAHaegt** [comment]
Upon exiting the game I had this error log that I saw some other people also had on a few other threads, but launching the game with .43 is not crashing the game. I guess the issue is still with .44.
[XivAlexander_20220103_184613_941.log](https://github.com/Soreepeong/XivAlexander/files/7804710/XivAlexander_20220103_184613_941.log)
](url)

**Comment by Soreepeong** [comment]
Try the latest version, as I don't really have any useful debug info stored for not most recent version (even when I should I often forget...) If you can get a stack trace containing a lot of XivAlexander entries, it's going to be helpful.
