### ISSUE TITLE
High Latency Mitigation / Modes

### ISSUE THREAD

**Issue by connnker94** [Soreepeong/XivAlexander#277]
First Thank You for this great launcher 
my question is there are 3 modes in the High latency mitigation!
Mode1 Mode2 Mode3 
which one is best to you use ? if I'm looking for the best possible mode and no latency + safe also ? 
its set to mode 3 now [ simulate normalized RTT AND LATENCY ] .

kindly.

**Comment by Soreepeong** [comment]
Anything is fine, as every mode tries to abide to the game's supposed restrictions. You'll have to see for yourself whether it's effective for you though.
