### ISSUE TITLE
Inquiry in regards to usage with low ping.

### ISSUE THREAD

**Issue by TOMETRAT** [Soreepeong/XivAlexander#278]
Hi, I haven't really seen any issues or tickets in regards to this.

Currently, on the times when the server is not lagging (not on peak hours) I have about 18ms - 20ms (I basically live next to the server)

Lately, i've seen that on peak hours my ping is around 150ms - 180ms fluctuating. This might be due to their server implementation on fixing the 2002 errors because this hasn't happened prior to the patch.

**My inquiry is this:**
After the servers stabilize, if im constantly at around 18ms - 23ms for my ping, is it worth it to use the High Latency Mitigation of XivAlexander? If so, would I be gimping myself by using the Mode 2/Mode 3 in which it simulates 75ms or a stabilized ms rate? Or should I use the Mode 1 of Subtract Latency?

**Comment by Soreepeong** [comment]
It really depends on virtually everything. You'll have to see for yourself which of the 3 modes is the most effective you at the given hour. I just stick to mode 2.
