### ISSUE TITLE
Changing Font Size

### ISSUE THREAD

**Issue by neo-royalty** [Soreepeong/XivAlexander#279]
RE: Using the text replacement mod for English UI with Japanese dialogue

Is there a way to modify the font only for the NPC textboxes? Specifically I'm trying to upsize the English client's font size to the Japanese client's.

**Comment by Soreepeong** [comment]
You can set "Force Display Language" to "English" while starting the game client in Japanese.

**Comment by neo-royalty** [comment]
Wow I didn't expect the solution to be this simple, awesome. Thanks a lot.
