### ISSUE TITLE
Question on new fps lock feature

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#280]
Hi

1. When you say 'works best with jobs with static GCD', do you mean excluding ones like SAM, NIN, etc that grants themselves with additional sks?

2. What is the relationship with fps and GCD clipping, latency?

3. Will the difference in clipping and double-weaving noticeable with/without using the newly added feature?

Thank you.

**Comment by Soreepeong** [comment]
1. Probably yes. DRG for example got consistent cooldowns on the other hand.
2. Check this out: https://docs.google.com/document/d/13ggP7PoOs-ic6ve_Huo4A2-3Mx7ozeRPXzC7N_edgHU/edit#heading=h.6ahuhfypggom
3. This is going to affect in a long run, as in using 1 more gcd in a 8 minute run; it won't have any immediate effects.

**Comment by justin767** [comment]
> Reference in ne

Thanks.

**Comment by justin767** [comment]
> 1. Probably yes. DRG for example got consistent cooldowns on the other hand.
> 2. Check this out: https://docs.google.com/document/d/13ggP7PoOs-ic6ve_Huo4A2-3Mx7ozeRPXzC7N_edgHU/edit#heading=h.6ahuhfypggom
> 3. This is going to affect in a long run, as in using 1 more gcd in a 8 minute run; it won't have any immediate effects.

Is it possible to have smoother gameplay when having the framelock and fps synchronization off? I just tried and I'm feeling this way.

**Comment by justin767** [comment]
> 1. Probably yes. DRG for example got consistent cooldowns on the other hand.
> 2. Check this out: https://docs.google.com/document/d/13ggP7PoOs-ic6ve_Huo4A2-3Mx7ozeRPXzC7N_edgHU/edit#heading=h.6ahuhfypggom
> 3. This is going to affect in a long run, as in using 1 more gcd in a 8 minute run; it won't have any immediate effects.
https://github.com/Soreepeong/XivAlexander/issues/280#issuecomment-1004269220


> 1. Probably yes. DRG for example got consistent cooldowns on the other hand.
> 2. Check this out: https://docs.google.com/document/d/13ggP7PoOs-ic6ve_Huo4A2-3Mx7ozeRPXzC7N_edgHU/edit#heading=h.6ahuhfypggom
> 3. This is going to affect in a long run, as in using 1 more gcd in a 8 minute run; it won't have any immediate effects.

Is it possible to experience smoother gaming and weaving without the framework and framing options turned off? Because I tried those features, but disabling both of them feels the best for me.

**Comment by Soreepeong** [comment]
These new features are completely optional, and should not have any noticeable effect in the very moment you're playing the game.
