### ISSUE TITLE
Anyone got 6.05 Opcodes?

### ISSUE THREAD

**Issue by claw751** [Soreepeong/XivAlexander#285]

**Comment by ArmoredSavitar12** [comment]
try this
{
	"C2S_ActionRequest": "0x034d",
	"C2S_ActionRequestGroundTargeted": "0x01a3",
	"S2C_ActionEffect01": "0x033e",
	"S2C_ActionEffect08": "0x01f4",
	"S2C_ActionEffect16": "0x01fa",
	"S2C_ActionEffect24": "0x0300",
	"S2C_ActionEffect32": "0x03cd",
	"S2C_ActorCast": "0x0307",
	"S2C_ActorControl": "0x02cf",
	"S2C_ActorControlSelf": "0x0096",
	"S2C_EffectResult6": "0x0203",
	"S2C_EffectResult6Basic": "0x0330",
	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24",
	"Server_PortRange": "1025-65535"
}

**Comment by claw751** [comment]
> 

Not all heroes wear capes, thanks

**Comment by sainishwanth** [comment]
Ayy thanks.

**Comment by Sequincer** [comment]
What about "S2C_EffectResult5": ?

**Comment by GaiaNihil** [comment]
how do I implement this codes? the steps on the installation page dont explain so well for me (noob to this kinda of stuff)

**Comment by sainishwanth** [comment]
Open up XIVAlexander, under Configure there should be an option called "Edit OpCode Configuration"
