### ISSUE TITLE
Game client crashes upon exit

### ISSUE THREAD

**Issue by WickedTrap** [Soreepeong/XivAlexander#287]
Hello,

I'm currently seeing this issue wherein the game client is getting stuck upon exit.

Steps:
1. Download latest XIVAlexander release.
2. Use the first option during installation. Also tried to install as dinput8.dll
3. Run game using QuickLauncher.
4. Press exit
5. Game client gets stuck and need to force quit.

Issue is not seen after I uninstall XIVAlexander and will return if I install it again.

**Comment by Soreepeong** [comment]
Does it happen if you enable `Quick exit` or something like that from Configure? While it technically can corrupt your files, it is very unlikely and it never corrupted files for me for more than a year.

**Comment by WickedTrap** [comment]
I just tried now to enable it and it solved the crash issue. Thanks. :)
