### ISSUE TITLE
Question: Install option with GShade

### ISSUE THREAD

**Issue by WickedTrap** [Soreepeong/XivAlexander#288]
Hello,

If I'm using GShade and I can see that it created a "d3d11.dll" file, should I choose the install option "Install XivAlexander as dinput8.dll for DirectX 11 version"?

Thank you.

**Comment by Soreepeong** [comment]
When I tested it, the following worked at least for me:

> Install GShade as d3d11.dll first, and then install XivAlexander as d3d11/d3d9 mode. It should just work. Uninstall XivAlexander before updating ReShade/GShade, and then install XivAlexander only after update is complete.

**Comment by WickedTrap** [comment]
Thanks for the suggestion. Tried to add it to auto start with QuickLauncher and now the client does not get stuck when exiting even if the Quick Exit option is disabled. :)

**Comment by WickedTrap** [comment]
Edit: It seems that adding it to auto launch with QuickLauncher is not working fine. So I will install it separately.
