### ISSUE TITLE
slow loading times, also weird issue when exiting

### ISSUE THREAD

**Issue by Rekuja** [Soreepeong/XivAlexander#289]
was fine until i updated, noticing it takes longer than usual to switch zones (teleporting) and also when i exit game, my screen stays black for a while until i click into it.

doesnt happen with xivalexander uninstalled

potential bug?

**Comment by DAOWAce** [comment]
Do you use mods with Penumbra/TexTools?

I had the slow loading issues when using Penumbra, but after taking the time to switch the mods over to Alexander, the slow loading went away.

Still have the black screen on exit though, which typically lasts around 10 seconds.

**Comment by Soreepeong** [comment]
Can you upload your `config.runtime.json`? You might have checked a debug option that will noticeably slow down everything.

**Comment by Rekuja** [comment]
hey we can mark this as resolved, I believe the "use more CPU" was causing the issue, turned that off and everything was fine. Maybe ensure this isn't on by default? just in case it causes problems for other people?

Pretty weird since my PC is very powerful, 32gb ram, 5.20ghz, 3070 gtx

**Comment by DAOWAce** [comment]
>  I believe the "use more CPU" was causing the issue, turned that off and everything was fine. 
No change to the black screen here toggling the CPU time option.

> For exiting, can you try turning on Configure > Quick Game Termination?
Rather not cause the application to force quit.  Never liked doing that in my lifetime of using PC's (only for problematic processes).  I can workaround the black screen regardless, it's just a minor annoyance.
