### ISSUE TITLE
Game won't launch with xivalex

### ISSUE THREAD

**Issue by latch001** [Soreepeong/XivAlexander#290]
edit: I played around with this a bit more and properly read all the text in the .exe. I found that xivalex works fine if I use the "Load once" option, however none of the install options work for me. The third option (for dx9) seems to install fine, but xivalex doesn't run when the game launches. For the other two options, after hitting the play button on the launcher xivalex opens with the log window but the ffxiv itself never launches. I have tried disabling firewall/antivirus, running the 32 and 64 bit versions of xivalex, etc. but none of these options fixed the problem for me. 

Since it still works fine using the "Load once" option I am not too worried about this issue anymore however if there is a way for me to install xivalex without this problem I'd still be interested in knowing it, thanks.

**Comment by Soreepeong** [comment]
By "ffxiv itself never launches", does it quit some time later, or does it freeze after showing a black window, or does it not do anything at all after showing xivalex window?

**Comment by latch001** [comment]
It does not do anything at all after the launcher closes and the xiv window opens. No black screen/crash


________________________________

**Comment by latch001** [comment]
Thought I should also post the log that is displayed in the viewer, although as far as I can tell it doesn't contain any helpful info for the issue.

`2022-01-09 21:40:36.703	SocketHook	Waiting for game window to stabilize before setting up redirecting network operations.
2022-01-09 21:40:36.806	General	XivAlexander initialized.
2022-01-09 21:40:36.869	General	Freed game mutex \BaseNamedObjects\6AA83AB5-BAC4-4a36-9F66-A309770760CB_ffxiv_game_common.
2022-01-09 21:40:36.869	General	Freed game mutex \BaseNamedObjects\6AA83AB5-BAC4-4a36-9F66-A309770760CB_ffxiv_game00.`
