### ISSUE TITLE
How to tell when working

### ISSUE THREAD

**Issue by Reidlos65** [Soreepeong/XivAlexander#292]
Im sure this is a dumb question to the experts here, but is there a distinctive thing that says yes its working somewhere sides feel?  Log isnt outputting anything and dont see a clear yes or no on it working

**Comment by Soreepeong** [comment]
You can enable logging from "Networking > Latency and Timing Handler" and open the log window. Stuff will get printed when you use actions, including what are the animation lock durations.

**Comment by Reidlos65** [comment]
ok, wasnt working in the first session but reinstalled and worked it again and seems to be logging now
