### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by GaiaNihil** [Soreepeong/XivAlexander#296]
After the recent update (6.05) I did the same steps as always to instal and load the new version, and it just doesnt work. I uninstalled gshade, xiv launcher, reinstalled the game and also did a clean driver installation. Still doenst work.
![Screenshot_3](https://user-images.githubusercontent.com/85113915/148591323-67885204-176a-4230-a13f-28dab1336f4e.png)
![Screenshot_4](https://user-images.githubusercontent.com/85113915/148591327-c02132e2-39d9-4029-887f-d7ca27e30d57.png)
this is how my game files from both boot and game folders look like right now

**Comment by Soreepeong** [comment]
Try deleting dinput8.dll, and use install as d3d11/d3d9 option, and see if it works before installing GShade over it.

**Comment by GaiaNihil** [comment]
Working now. Ty!
