### ISSUE TITLE
Action entries not showing in logging window

### ISSUE THREAD

**Issue by RF4416** [Soreepeong/XivAlexander#299]
After loading XIV, the logging window displays the "Start tracking" line, but when entering combat and using abilities the usual action delay logging information is not showing up which makes me think that the program is not functioning for me as it should.

I believe my settings are completely default (Reduce Packet Delay on, Mode 3, and Use Logging enabled) so I am unsure of why nothing is showing as being logged.

**Comment by Soreepeong** [comment]
Try downloading the newest release, extract it all first, and then using it. If it doesn't work, try ticking on all entries in `Networking > Troubleshooting.`
