### ISSUE TITLE
Should I disable the new optional feature if using VPN (1.13a)

### ISSUE THREAD

**Issue by FloppyAl** [Soreepeong/XivAlexander#30]
Hello, 

Since I use a VPN, my system shows ffxiv's ping at 25-30 (in reality it's closer to 200), which would I'm assuming mess with the calculation of RTT by the program. Should I disable this feature in this case? 

Side note: Thank you for this amazing app, it's a lifesaver for me at 200ms.

**Comment by Soreepeong** [comment]
Try opening the log window, and if it also shows reduced latency that does not reflects the actual latency, you'll probably want to turn off the option.

**Comment by FloppyAl** [comment]
Thank you, just checked the log and it does not show the actual latency. Have turned it.
