### ISSUE TITLE
Ipc finder cannot find the address of S2C_EffectResult6Basic or S2C_EffectResult6

### ISSUE THREAD

**Issue by boxingbunny** [Soreepeong/XivAlexander#300]
The HP recorded every time is always incorrect, when I grant a buff on myself.

**Comment by boxingbunny** [comment]
And I feel latency when double weaving.

**Comment by Soreepeong** [comment]
Try the latest version to fix the latter problem. EffectResult6/Basic can be ignored as they will not make difference in latency mitigation.

**Comment by boxingbunny** [comment]
> Try the latest version to fix the latter problem. EffectResult6/Basic can be ignored as they will not make difference in latency mitigation.

The latest version works better. Thanks!
