### ISSUE TITLE
Game stuck on black screen when trying to exit the game with XivAlexander installed

### ISSUE THREAD

**Issue by HPDeskJet2540** [Soreepeong/XivAlexander#301]
Hello, I think starting last, whenever I tried to exit the game with XivAlexander installed, the game will freeze and be stuck on black screen. I have gpose and XIV launcher, it happened after I installed XivAlexander, I also tried using it on anotehr PC, but still the same result.

**Comment by Soreepeong** [comment]
Try Configure > Quick Game Exit.
