### ISSUE TITLE
Getting error even after deleting xivalexander

### ISSUE THREAD

**Issue by conrage97** [Soreepeong/XivAlexander#303]
![image](https://user-images.githubusercontent.com/97439869/148747017-0ca5d2b0-65bb-4552-b3b3-3ae9e498b306.png)

Does anyone know why I still encounter this error despite deleting xivalexander? I have tried finding xivalexander from all over the place and deleting them already. Do I need to reinstall my game?

**Comment by Soreepeong** [comment]
If you do not have d3d9.dll, d3d11.dll, and dinput8.dll in your game directory, it is not about XivAlexander. If you use FFXIVQuickLauncher, you might want to try integrity check.

**Comment by conrage97** [comment]
From the uninstall manual, I tried to follow all the paths that xivalexander could be in and just deleted them. I may or may not have accidentally deleted something related to the actual game. Is there anyway to completely get rid of all the xivalexander on my computer?

**Comment by conrage97** [comment]
![image](https://user-images.githubusercontent.com/97439869/148748498-67be700c-5c16-4ac4-865a-804874d718c5.png)

Do I need to delete the config.xivalexinit.json file as well?

**Comment by conrage97** [comment]
![image](https://user-images.githubusercontent.com/97439869/148748878-3e39ff0f-4fdd-4a16-ad11-733acd72eecb.png)

Cuz I am still getting this error when trying to login the game, it seems that there are some residual xivalexander left somewhere? How do I completely get rid of it?
