### ISSUE TITLE
Getting this error when starting my game

### ISSUE THREAD

**Issue by conrage97** [Soreepeong/XivAlexander#304]
![image](https://user-images.githubusercontent.com/97439869/148769503-c6bf6dd2-ff54-4531-9b17-84b00db36acc.png)

I have followed the uninstallation manual and went ahead to delete every possible xivalexander file I could find, but am still getting this error message whenever I open my client. How do I delete or uninstall the remaining xivalexander so that this message wont appear anymore?

**Comment by Soreepeong** [comment]
Delete d3d11.dll, d3d9.dll, and dinput8.dll from your game directory. Though, if you just run the newest version and run the loader, it should offer an option to uninstall which should get rid of those files by itself. Did it not work?

**Comment by conrage97** [comment]
It only allows me to uninstall when my game is closed. But when my game is closed, the cog icon doesnt appear since my game is closed. I have to open my game in order for the cog icon to appear and uninstall?

**Comment by Soreepeong** [comment]
Turn off game, and then run the loader from the unzipped file, and then uninstall.

**Comment by conrage97** [comment]
Doing that will completely uninstall the xivalexander from everywhere? Can i run either the 32 or 64 loader? I encountered error with xivalexander after changing some items using item converter in textools, can that happen?

**Comment by Soreepeong** [comment]
Yes, you can use either one of them. Also that may happen if the mod you have installed is corrupt, or something went wrong while installing a mod. If you installed XivAlexander for high latency mitigation, you can turn off modding altogether, and then XivAlexander won't trip about anything about modding.

**Comment by conrage97** [comment]
When you say turn off modding, do you mean I shouldnt use textools to mod textures/armour? Is there any way to use xivalexander and still use textool modding without any issues? I am only using it for high latency mitigation.

**Comment by Soreepeong** [comment]
I mean, you can turn off modding from XivAlexander menu.

**Comment by conrage97** [comment]
Sorry but where is the xivalexander menu? Do I have to open the loader?

**Comment by Soreepeong** [comment]
You have to be running the game with XivAlexander loaded.

**Comment by conrage97** [comment]
When I first download xivalexander i just installed with d3d9 and d3d11 and just load it with the game file.

So how do I access the menu with xivalexander loaded? Is it from the cog icon?

**Comment by Soreepeong** [comment]
That is correct. Right clicking on the icon on the tray menu will let you show the menu. Where did you download the program anyway? XivAlexander modding should be disabled by default to begin with.

**Comment by conrage97** [comment]
I was using textools, and used the item converter to replace my current armor with another armor.

**Comment by Soreepeong** [comment]
Then the error is not about XivAlexander. It just tries to show more information about errors if any happens - not all XivAlexander error messages are caused by it.

**Comment by conrage97** [comment]
Do I need to get opcodes or anything? Cuz I just followed the installation menu where I install it with the d3d9 and d3d11 and load it, I did not make any further adjustments. It worked fine though so I didnt mess with it.

**Comment by Soreepeong** [comment]
Changing opcodes is only required when the opcode supplied with the download isn't updated for new game update. For now, you can just use it.

**Comment by conrage97** [comment]
Alright thanks.
