### ISSUE TITLE
Since the new update the Alex Launcher asks me to isntall every time my game starts?

### ISSUE THREAD

**Issue by illhatjr28** [Soreepeong/XivAlexander#306]
Apologizes if this is just how the current version works or if this has been answered before. 

So I reinstalled XIV Alex, put in the new op codes, and it seems to be working (I can triple weave barely on east coast).
However every time I launch the game (Dalamud launcher) a big pop up from XIVAlex shows up asking me how I would like to install or just run the game or uninstall etc, the screen that originally pops up. 

I have to X out of it every single time I run the game, the previous update the Alex would just go straight to my minimize tray on my PC and I didnt have to close anything. Is this supposed to happen? Its not the end of the world just a mild annoyance. Thank you for your time.

**Comment by Soreepeong** [comment]
Can you screencap FFXIVQuickLauncher's settings page on autostart stuff? `-a load` should still work.

**Comment by Soreepeong** [comment]
I think you're talking about FFXIVQuickLauncher by "dalamud launcher".

**Comment by CharonM72** [comment]
Probably this:
![image](https://user-images.githubusercontent.com/1299220/148799209-64743fb1-cd04-4c03-90ba-321bb5f73232.png)

If XIVAlexander is installed, then there is no need to have it launched via XIVLauncher. Otherwise you may get that window. (if I'm reading this correctly)

**Comment by illhatjr28** [comment]
OOOOOO yes i have XIVloader checked on my Dalamud launcher, so I just need to uncheck that?

**Comment by CharonM72** [comment]
Try it and see if it works. Those are my settings and it works fine, without manually loading it via the launcher.

**Comment by illhatjr28** [comment]
That fixed the issue, it opened straight into the tray of my PC without prompting me to install again. Thank you so much !! Really appreciate the fast response and your help.
