### ISSUE TITLE
Question on changing opcodes

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#309]
Hello, when changing the opcodes for the game's new patch release, do we also have to change the .json text file through notepad? Or is changing the values in the window (one that pops up upon clicking 'change opcode configuration') enough?

**Comment by Spanglish1337** [comment]
changing the values in the window (one that pops up upon clicking 'change opcode configuration') is enough. You just save that window to save the changes and close it. Don't have to restart game or XivAlexander.
