### ISSUE TITLE
Can't find Opcodes

### ISSUE THREAD

**Issue by stormraider1314** [Soreepeong/XivAlexander#31]
I have turned on the IPC Type Finder, High Latency Mitigation and Delay Detection, and opened the log window. However when I cure myself, placing a Earthly Star, and canceling cast; whatever I do, the log window stay the same as the pic shows below (it's been showing this since I load the XivAlexander after run the game.) Thanks in advance!

![//imgur.com/H4K1Ows](https://imgur.com/H4K1Ows.png)

**Comment by Soreepeong** [comment]
You'll have to edit configuration to add Chinese FFXIV game servers' IP address range to configuration. 

Try replacing 
```json
"GameServerIpRange": "124.150.157.0/24,195.82.50.0/24,204.2.229.0/24,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,",
```
with
```
"GameServerIpRange": "109.244.0.0/16,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,",
```
in the configuration.

Though, the whole `109.244.0.0/16` IP address range looks like overkill, as it belongs to Tencent Cloud. Please let me know if you figure out the exact address range of Chinese FFXIV servers.

**Comment by stormraider1314** [comment]
> ```json
> "GameServerIpRange": "109.244.0.0/16,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,",
> ```

It worked! Thanks so much. It poped a lot KeepAliveRequest and showed up the message when I tested curing myself; I added a pic of the log window below.
https://imgur.com/lisfeOl

I'm very happy to help you find the Chinese FFXIV server's address range, but I'm just not familiar with this stuff... Could you tell me where I can find the address?  And since I live in NA and I play on the Chinese server, I don't know if that matters?

**Comment by Soreepeong** [comment]
Not really - I was just asking if you know one by any chance. Anyway glad that you got it working!
