### ISSUE TITLE
getting constant error 90006,90001,90002 since downloading xivalexander. 

### ISSUE THREAD

**Issue by KinaraChoco** [Soreepeong/XivAlexander#317]
completely cleaned all files out, removed d3d9.dll and everything else from game but still getting d/c's constantly. should i know about something that might fix this? Is this related to my isp connection maybe? Am I better off just reinstalling the game and never touching this program again?

**Comment by Reidlos65** [comment]
I have been using it for a week or so and recently also getting wayyyy to many 90006 errors, not sure its related yet so going to uninstall and try for a little while.  If its working better ill reply in 2-3 days, ill float around and see if  any news develops

**Comment by ArmoredSavitar12** [comment]
Yeah same thing with me

**Comment by Soreepeong** [comment]
If you did delete `d3d9.dll`, `d3d11.dll`, and `dinput8.dll` from game installation directory (NOT any folder involving `C:\Windows`), then it has nothing to do with XivAlexander from that point on.

**Comment by KinaraChoco** [comment]
Im updating FFxiv on my back up pc, and ill test it to see if i have the same issues. If not, well ill just have to reset my main pc. If it does continue giving me the errors, well then i would have to assume its related to my connection. Real unfortunate because i was enjoying this program for a few hours or so before getting weird connection hiccups. Hoping my other pc also gives me the same errors since its never used xivalexander, ill be able to prove the program isnt causing it but then ill still just be stuck with my shoddy internet. Oh well.

**Comment by Reidlos65** [comment]
> I have been using it for a week or so and recently also getting wayyyy to many 90006 errors, not sure its related yet so going to uninstall and try for a little while. If its working better ill reply in 2-3 days, ill float around and see if any news develops

ok been 2 days or so, not a single lag spike or 90006 error after a full uninstall

**Comment by Soreepeong** [comment]
Try again with the latest version, after removing the folder `%APPDATA%\XivAlexander`. This version changes an option's default value to off, which could be causing problems for some people if kept on.

**Comment by KinaraChoco** [comment]
After resetting my pc, and also playing on my backup pc meanwhile, i continued having the same problems on both pc's. As i mentioned before, the backup pc has never downloaded or used xivalexander so ruling out that as a factor, i believe it was my isp/router which was giving me the constant connection errors/disconnects. May try xivalexander again. Thanks Soreepeong.
