### ISSUE TITLE
Using EXDF Rules breaks pet macros

### ISSUE THREAD

**Issue by gplafreniere** [Soreepeong/XivAlexander#319]
Hi,

Was using EXDF to display Japanese text (i.e. `EnglishWithJapanese_SayQuestJapanese.json`). I noticed that my SCH macro for Eos has broken as a result:

/pac Heel
/pac Place
/micon Place pet

suddenly starts throwing the error in chat that “Heel” is not a valid action name and “Place” is not a valid action name; changing the action names to their JP versions also did not fix the issue. I've isolated this issue to XIV Alexander as unloading the .json rule to remove JP text makes the macro work again.

![H7UHEiU 1](https://user-images.githubusercontent.com/16273924/149872454-7e478976-2430-4930-ab87-fbe64ba87672.png)

**Comment by Soreepeong** [comment]
Yes, use auto-translate feature to convert them to ((something)) format.

**Comment by gplafreniere** [comment]
Ah my bad... I should've checked closed issues. Saw you handled this twice already (third time's the charm?!) Got it working now, thanks!
