### ISSUE TITLE
Can't Find the XivAlexanderLoader.exe

### ISSUE THREAD

**Issue by Chimymc** [Soreepeong/XivAlexander#32]
I downloaded and unzipped the file and I have looked at every folder but I cant find the .exe file I just see a lot of other file types

**Comment by Soreepeong** [comment]
You need to download x64_Release.zip

**Comment by Chimymc** [comment]
Where do I get that?

**Comment by Soreepeong** [comment]
There's "Releases" menu on the right side of the page.  https://github.com/Soreepeong/XivAlexander/releases

**Comment by Chimymc** [comment]
Thank you sorry for the bother
