### ISSUE TITLE
Failed to unload

### ISSUE THREAD

**Issue by majesticuni** [Soreepeong/XivAlexander#322]
Whenever Im trying to unload xivalexander its giving me a error saying "another module has hooked window procedure over xivalexander, try unoading that module first" im not sure what this it is and i have to force exit the game as when i close the game normally theres a long black screen that doesnt go away and i have to go to task manager to close it. 

I use texttools and quicklauncher

![image](https://user-images.githubusercontent.com/51346424/150132718-d54cee8f-d09e-4dc2-b84c-36dec7d6ed06.png)

**Comment by GonySue** [comment]
I was able to unload xivalexander properly, but closing the game also resulted in a black screen, which had to be closed using task manager, unloading xivalexander worked fine

**Comment by Soreepeong** [comment]
If it failed to unload, restart the game. That's it.

**Comment by majesticuni** [comment]
> 

I have the game open already but when I want to unload xivalexander while my game is open, how does restarting my game fix this issue? I just want to close XIValexander while my game is still open, but this gives me an error

**Comment by Soreepeong** [comment]
Sometimes you just can't. You'll have to restart the game.

**Comment by majesticuni** [comment]
> Sometimes you just can't. You'll have to restart the game.

Does "force exit the game" option cause any issues with my game? ive been doing this to fully close the game to not worry about this error or the black screen. I just dont know if force closing it this way will mess anything up?

**Comment by Soreepeong** [comment]
No, it's safe to keep it on. In fact, in latest version, that option is gone, being permanently enabled.
