### ISSUE TITLE
Game hitch when changing jobs

### ISSUE THREAD

**Issue by puchev** [Soreepeong/XivAlexander#325]
The latest update seems to cause the game to hang for half a second when switching from DoH/DoL jobs to DoW/DoM jobs and back.
I reinstalled 1.14.8.47 to double check and the problem went away.
Is anyone else experiencing this?

**Comment by ShinjukuCurry** [comment]
no issues here

**Comment by Soreepeong** [comment]
I can't see XivAlexander affecting this at all. Does this *not* happen when XivAlexander is not loaded/uninstalled?

**Comment by puchev** [comment]
> I can't see XivAlexander affecting this at all. Does this _not_ happen when XivAlexander is not loaded/uninstalled?

No, it doesn't happen with XivAlexander not loaded, but I think I've figured it out.
The Modding option "Log All Path Plaintext Before Hash" was enabled for whatever reason. Disabling this option seems to fix it.
Oddly enough this doesn't happen with 1.14.8.47 or below with the same option ticked.
