### ISSUE TITLE
Anyone got 6.08 Opcodes?

### ISSUE THREAD

**Issue by denma-xiv** [Soreepeong/XivAlexander#328]

**Comment by denma-xiv** [comment]
{
    "C2S_ActionRequest": "0x008e",
    "C2S_ActionRequestGroundTargeted": "0x00f8",
    "S2C_ActionEffect01": "0x03c7",
    "S2C_ActionEffect08": "0x0149",
    "S2C_ActionEffect16": "0x00c1",
    "S2C_ActionEffect24": "0x0213",
    "S2C_ActionEffect32": "0x038b",
    "S2C_ActorCast": "0x0104",
    "S2C_ActorControl": "0x022f",
    "S2C_ActorControlSelf": "0x006b",
    "S2C_EffectResult6": "0x00de",
    "S2C_EffectResult6Basic": "0x034e",
    "Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24, 153.254.80.0/24",
    "Server_PortRange": "1025-65535"
}

Tested, looks like it work.

**Comment by valinise** [comment]
worked for me, thank you!
