### ISSUE TITLE
opcodes for 6.08

### ISSUE THREAD

**Issue by keerthan655** [Soreepeong/XivAlexander#331]
**Edited by repository owner to reflect correct S2C_ActorCast value.**

```json
{
	"C2S_ActionRequest": "0x008e",
	"C2S_ActionRequestGroundTargeted": "0x00f8",
	"S2C_ActionEffect01": "0x03c7",
	"S2C_ActionEffect08": "0x0149",
	"S2C_ActionEffect16": "0x00c1",
	"S2C_ActionEffect24": "0x0213",
	"S2C_ActionEffect32": "0x038b",
	"S2C_ActorCast": "0x0104",
	"S2C_ActorControl": "0x022f",
	"S2C_ActorControlSelf": "0x006b",
	"S2C_EffectResult6": "0x00de",
	"S2C_EffectResult6Basic": "0x034e",
	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24, 153.254.80.0/24",
	"Server_PortRange": "1025-65535"
}
```

I think these should work, could someone help verify? thanks!

**Comment by LittleLuxio** [comment]
working for me ^__^

**Comment by cyborgdead** [comment]
yup working thank you!

**Comment by owopeachy** [comment]
seems good but i think S2C_ActorCast should be 0x0104

**Comment by Kromtastic** [comment]
Working perfectly for me! Thanks a ton!

**Comment by Xypxlqy** [comment]
First time to use it. Can someone show how to use it?

**Comment by matthewvls** [comment]
> First time to use it. Can someone show how to use it?

Open XIValexander  go to configure on top right; edit opcode configuration then do as said above.

**Comment by jnyong89** [comment]
Does updating this opcode make the plugin workable again in 6.08?

**Comment by matthewvls** [comment]
> Does updating this opcode make the plugin workable again in 6.08?

Yes, that's the point of the post.

**Comment by NeRv-T3** [comment]
do these opcodes work for everyone? (issues withstanding) like, does it make a diff if i am from australia vs someone whose from elsewhere?

**Comment by salmondev** [comment]
> do these opcodes work for everyone? (issues withstanding) like, does it make a diff if i am from australia vs someone whose from elsewhere?

from SEA It still work 

```json
{
   "C2S_ActionRequest":"0x008e",
   "C2S_ActionRequestGroundTargeted":"0x00f8",
   "S2C_ActionEffect01":"0x03c7",
   "S2C_ActionEffect08":"0x0149",
   "S2C_ActionEffect16":"0x00c1",
   "S2C_ActionEffect24":"0x0213",
   "S2C_ActionEffect32":"0x038b",
   "S2C_ActorCast":"0x0104",
   "S2C_ActorControl":"0x022f",
   "S2C_ActorControlSelf":"0x006b",
   "S2C_EffectResult5":"0x93db",
   "S2C_EffectResult6":"0x00de",
   "S2C_EffectResult6Basic":"0x02d9",
   "Server_IpRange":"0.0.0.0/0",
   "Server_PortRange":"1-65535"
}
```

**Comment by TCWazzler** [comment]
Should I just be able to copy and paste this in to the opcode configuration and it should work, or do I have to do something else too? The plugin still isn't working for me.
