### ISSUE TITLE
Log not showing any detail after line 29 "Start tracking"

### ISSUE THREAD

**Issue by ArdentRoe** [Soreepeong/XivAlexander#334]
Typically, I'm getting details here...

![image](https://user-images.githubusercontent.com/98499698/151270600-0aef450c-7e07-49fe-ace6-0fa5e9475f7b.png)

**Comment by moamro123** [comment]
Same for me, I can't receive the benefit of this program anymore

**Comment by heyluna1217** [comment]
If you haven't updated your opcode config for 6.08 check out issue https://github.com/Soreepeong/XivAlexander/issues/331
