### ISSUE TITLE
Does not work on 6.08

### ISSUE THREAD

**Issue by procrastin8** [Soreepeong/XivAlexander#336]
Hi, don't see an issue highlighting this and have tried to uninstall and reinstall with admin rights and loading the process into the game once its running. I use XIV launcher if that makes any difference

**Comment by justin767** [comment]
You need to manually update the opcodes after new patches.

**Comment by procrastin8** [comment]
Hey, is there a guide I can refer to do this? so far my attempts have failed miserably

**Comment by procrastin8** [comment]
never mind saw the other opcode issue im blind

**Comment by CFRNN** [comment]
You can find 6.08 opcodes [here](https://github.com/Soreepeong/XivAlexander/issues/328), and how to update opcodes [here](https://github.com/Soreepeong/XivAlexander/wiki/XivAlexander-Help).
