### ISSUE TITLE
Still clipping when double weaving

### ISSUE THREAD

**Issue by Katsookay** [Soreepeong/XivAlexander#338]
So im a black mage and at some point in my opener i need to double weave during my ley line... now i used to not clip at all but since the 6 08 update ive been cliping... unsure why ? Does anyone else have this issue and how can i fix it ?

**Comment by CFRNN** [comment]
You need to update opcodes every time after FFXIV patch. Look into help page for how-to, and also there's always kind people who post new opcodes on Issues after patch.

**Comment by Soreepeong** [comment]
If you didn't get it fixed yet, just use the newest version.
