### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Mriria** [Soreepeong/XivAlexander#342]
Game crashed a couple of times after installing XIValex (been using the "load once" function all along until now). Might not be related to XIValex since I've had a few crashes ever since EW release, but I'm dropping you the log in case it's helpful idk. Cheers!
[XivAlexander_20220201_004457_321.log](https://github.com/Soreepeong/XivAlexander/files/7974948/XivAlexander_20220201_004457_321.log)

**Comment by Soreepeong** [comment]
11000002 error almost always means that some mod has gone wrong. Since you're using FFXIVQuickLauncher, try doing integrity check.

**Comment by Mriria** [comment]
Thanks for the heads up!
