### ISSUE TITLE
Caster tax is removed

### ISSUE THREAD

**Issue by rexatlanti** [Soreepeong/XivAlexander#343]
With current default settings the 0.1s between hard casts for eg BLM seems to be removed. Is this on purpose?
see https://www.fflogs.com/reports/a:4pg7BQ1Tzxtkv6LM#fight=last&type=casts&view=events

**Comment by Soreepeong** [comment]
Either grab the opcode file again from StaticData folder, or by downloading the newest release at [here](https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.8.49). If ActorCast opcode is incorrectly set, XivAlexander won't be able to tell whether it's a cast, resulting in effective removal of caster tax.

**Comment by rexatlanti** [comment]
Thank you very much for the reply and fix!
