### ISSUE TITLE
XivAlexander doesn't seem to work with a recent Windows 10 update

### ISSUE THREAD

**Issue by Nilhfaith** [Soreepeong/XivAlexander#35]
After letting Windows 10 install a new update called KB5000802 XivAlexander doesn't seem to work anymore. It crashes FFXIV and the error message says something about kernel and ntdll. Uninstalling the update and trying to use XivAlexander again works just fine however

**Comment by Soreepeong** [comment]
I believe I need more information to figure out what's going on, but then again I'm not sure what do I need to know. It also works on my PC...

**Comment by Nilhfaith** [comment]
Kind of a late reply to this but I solved the issue with a simple Windows 10 reinstall, it must have been an error on my PC specifically and not with XivAlexander which works perfectly
