### ISSUE TITLE
Endwalker OST is out

### ISSUE THREAD

**Issue by Sergster1** [Soreepeong/XivAlexander#357]
Opening this as an issue such that Upgrade Music Quality can be updated to reflect this

**Comment by Soreepeong** [comment]
Yeah, I'm still waiting for my delivery. Will be done once I receive it.

**Comment by Soreepeong** [comment]
Try this. https://github.com/Soreepeong/XivAlexander/blob/main/StaticData/MusicImportConfig/Endwalker.json

**Comment by TheNikomo** [comment]
Doesn't work. I tried it out with both ffmpeg from 2022-03-21 and stable 5.0 just in case, but I got the same errors.
Tried importing both decrypted m2ts files (used MakeMKV) and also the MP3 files from the disc, error logs from both are attached below. Source files work in media players just fine.
[mp3_import.txt](https://github.com/Soreepeong/XivAlexander/files/8325027/mp3_import.txt)
[m2ts_import.txt](https://github.com/Soreepeong/XivAlexander/files/8325028/m2ts_import.txt)
