### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by Soreepeong** [Soreepeong/XivAlexander#36]
Use API: https://api.github.com/repos/Soreepeong/XivAlexander/releases

TODO: When to check update, user consent

**Comment by jjolano** [comment]
Use https://api.github.com/repos/Soreepeong/XivAlexander/releases/latest for less information to download.

Maybe this system can be implemented on regular startup of the exe with prompt if there's an update available. Shouldn't add much startup time.

(maybe also opcode auto update whenever https://xivapi.com/patchlist changes?)

**Comment by ayyaruq** [comment]
Best not to rely on xivapi's patch list, it's manually maintained and we (xivapi) don't always update it regularly or on time. Would likely be better to poll the gateway URL for version updates, or just do on startup.

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.6.0

Update checking feature has been implemented. Add option to check for updates automatically, and then feature to download and unzip too.
