### ISSUE TITLE
Opcodes for 6.08 hotfix

### ISSUE THREAD

**Issue by gimmedeath** [Soreepeong/XivAlexander#361]

**Comment by tyhindmarsh** [comment]
first time configuring this myself so let me know if anything is incorrect but this is what i got:
{
	"C2S_ActionRequest": "0x03e0",
	"C2S_ActionRequestGroundTargeted": "0x02e0",
	"S2C_ActionEffect01": "0x035e",
	"S2C_ActionEffect08": "0x02ba",
	"S2C_ActionEffect16": "0x010d",
	"S2C_ActionEffect24": "0x00f7",
	"S2C_ActionEffect32": "0x01ca",
	"S2C_ActorCast": "0x01f4",
	"S2C_ActorControl": "0x0202",
	"S2C_ActorControlSelf": "0x0301",
	"S2C_EffectResult5": "0xd498",
	"S2C_EffectResult6": "0xd498",
	"S2C_EffectResult6Basic": "0x0202",
	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24, 153.254.80.0/24",
	"Server_PortRange": "1025-65535"
}

**Comment by Jessidhia** [comment]
They seem to match what I found locally as well (also doing it for the first time); though I'm not sure how you get `S2C_EffectResult6` to be logged. All my attempts with tank buffs only logged `S2C_EffectResult6Basic`.

**Comment by Yurihaia** [comment]
This patch might have changed EffectResult stuff because the HP display was all messed up

**Comment by tyhindmarsh** [comment]
yeah, i couldn't get ```S2C_EffectResult6``` to display either

**Comment by gomesdsa** [comment]
could someone do a step by step on what to do with the opcode please? 
my opcode is like this:
{
	"C2S_ActionRequest": "0x93db",
	"C2S_ActionRequestGroundTargeted": "0x93db",
	"S2C_ActionEffect01": "0x93db",
	"S2C_ActionEffect08": "0x93db",
	"S2C_ActionEffect16": "0x93db",
	"S2C_ActionEffect24": "0x93db",
	"S2C_ActionEffect32": "0x93db",
	"S2C_ActorCast": "0x93db",
	"S2C_ActorControl": "0x93db",
	"S2C_ActorControlSelf": "0x93db",
	"S2C_EffectResult5": "0x93db",
	"S2C_EffectResult6": "0x93db",
	"S2C_EffectResult6Basic": "0x93db",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

**Comment by TicTacTris** [comment]
Hi, curious but does changing contents of the JP.json file with that code act as a fix? After the MT, I found out that it wasn't working anymore :(

**Comment by robyn0751** [comment]
> Hi, curious but does changing contents of the JP.json file with that code act as a fix? After the MT, I found out that it wasn't working anymore :(

Yes, I have the same question; I'm not very technically apt so I'd just like to know if copying the attempted config onto somewhere will fix things (or would sitting tight for the creator be the best idea)

**Comment by Soreepeong** [comment]
You can disregard EffectResult for latency mitigation purposes. While this will be fixed sometime later, not having EffectResult6/Basic only affects "Log Effect Application Delay".

**Comment by NationFive** [comment]
After the patch I do feel that my gcds aren't weaving as fast before patch day. I'm not quite a tech savvy guy but I imagine it's cause of the hotfix today. Is there a way I should set my settings in a particular way or is the optcode the issue?

Trying to figure it out, apologies in advance for my ignorance.
