### ISSUE TITLE
Opcode for 6.00 Chinese server

### ISSUE THREAD

**Issue by RavenYDY** [Soreepeong/XivAlexander#368]

**Comment by sAmyAox** [comment]
{
	"C2S_ActionRequest": "0x03c7",
	"C2S_ActionRequestGroundTargeted": "0x015e",
	"S2C_ActionEffect01": "0x018f",
	"S2C_ActionEffect08": "0x0175",
	"S2C_ActionEffect16": "0x01e8",
	"S2C_ActionEffect24": "0x008d",
	"S2C_ActionEffect32": "0x0392",
	"S2C_ActorCast": "0x010a",
	"S2C_ActorControl": "0x00f6",
	"S2C_ActorControlSelf": "0x0325",
	"S2C_EffectResult5": "0x010a",
	"S2C_EffectResult6": "0x010a",
	"S2C_EffectResult6Basic": "0x00f6",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

This works for me but not sure how to change ipRange and PortRange; besides, 
	"S2C_EffectResult5": "0x010a",
	"S2C_EffectResult6": "0x010a", 
are automatically generated, only S2C_EffectResult6Basic can be found in log files

**Comment by RavenYDY** [comment]
> { "C2S_ActionRequest": "0x03c7", "C2S_ActionRequestGroundTargeted": "0x015e", "S2C_ActionEffect01": "0x018f", "S2C_ActionEffect08": "0x0175", "S2C_ActionEffect16": "0x01e8", "S2C_ActionEffect24": "0x008d", "S2C_ActionEffect32": "0x0392", "S2C_ActorCast": "0x010a", "S2C_ActorControl": "0x00f6", "S2C_ActorControlSelf": "0x0325", "S2C_EffectResult5": "0x010a", "S2C_EffectResult6": "0x010a", "S2C_EffectResult6Basic": "0x00f6", "Server_IpRange": "0.0.0.0/0", "Server_PortRange": "1-65535" }
> 
> This works for me but not sure how to change ipRange and PortRange; besides, "S2C_EffectResult5": "0x010a", "S2C_EffectResult6": "0x010a", are automatically generated, only S2C_EffectResult6Basic can be found in log files

It works! thx!
