### ISSUE TITLE
Alexander and VPNs

### ISSUE THREAD

**Issue by ThonaUmbra** [Soreepeong/XivAlexander#370]
Not really an issue, bit more a question. I play with high ping and thought of giving alexander a try.
Does this work as intended when using it together with a VPN that is connected (ex. Nordvpn)?
I checked the help document and couldn't find information on this, but I might have not checked correctly.
Cheers!

**Comment by Soreepeong** [comment]
If the VPN reported false ping, then Mode 1 and Mode 3 of high latency mitigation will not work correctly. If something doesn't work well, then try out Mode 2, and try ticking everything in Troubleshooting menu.

**Comment by ThonaUmbra** [comment]
Thanks! I will give it a shot later.
