### ISSUE TITLE
Trying to add Korean to the English language of the game, but Japanese showing up instead

### ISSUE THREAD

**Issue by kirinelf** [Soreepeong/XivAlexander#388]
Hi, just wondering if you might be able to solve this. I have installed both the font config and the EXDF files, which kind of work, but for some reason the additional text is in Japanese instead of Korean. Would you happen to know if I've made any mistakes? Thank you!

![ffxiv_dx11_2022-04-02_21-49-48](https://user-images.githubusercontent.com/30263373/161379925-ebf10550-b188-46f2-a53a-025cf866c789.png)
![2022-04-02_21-52-08](https://user-images.githubusercontent.com/30263373/161379950-2bd35313-2607-4abc-8046-ebe3e4d03c69.png)

**Comment by Soreepeong** [comment]
You will have to add Korean installation to "Additional Game Root Directories". Otherwise, it'll fall back to Japanese text based on `Fallback Language Priority`.

**Comment by kirinelf** [comment]
Oh, so I need the Korean version of the game installed for it to work? I'm trying to get a friend of mine to play the game, but he's Korean and not very good at English, so I wanted to get this working so he can play with me. 

Do I need to buy the Korean installation separately?

**Comment by Soreepeong** [comment]
Trial version should do, I think.

**Comment by kirinelf** [comment]
Okay, thanks for replying! I'll give it a try and see if it works.
