### ISSUE TITLE
Xivalexander Performance Fluctuation

### ISSUE THREAD

**Issue by Rossier** [Soreepeong/XivAlexander#39]
I downloaded the latest version of xivalexander and when I turn it on the performance fluctuates. I hit a dummy for 12 minutes and sometimes I can double weave sometimes I can't. At least when I press two ogcds in quick succession on my screen it looks like I didn't double weave it. But when I track it I am apparently able to double weave properly, but my screen shows that my skill didnt go off and I have to press my skills twice sometimes. 

Edit: I just tested it again with a MCH and when I used to be able to weave a ricochette/gauss round between heat blast, now I can't

**Comment by Harxen** [comment]
Can confirm, after the new update (v1.14.0.0), noticed inconsistencies.

Without the tool I'm able to double weave inconsistently as is, so it feels as if with the tool, it's not working at all anymore, despite logs showing things are happening. I can also confirm with another person that the current version (v1.14.0.0) is worse than the previous version (v1.13a).

**Comment by Soreepeong** [comment]
I'll check if system TCP table and TCP_INFO_v0 yield different results later.

**Comment by Soreepeong** [comment]
[v1.13a - Copy.zip](https://github.com/Soreepeong/XivAlexander/files/6256029/v1.13a.-.Copy.zip)

Meanwhile, you can try this instead, if you need to download the previous version.

**Comment by Harxen** [comment]
Thanks!

I can confirm with v1.13a things are better and weaves are consistently smooth again.

**Comment by Rossier** [comment]
I can also confirm that 1.13a works better ^^b

**Comment by Soreepeong** [comment]
So, the reason 1.13a worked better is that reading systemwide TCP connection statistics tables required FFXIV to be ran as Administrator (because it appears that turning latency observation for a connection requires admin permissions), and when it failed, it defaulted to using hardcoded 75ms ExtraDelay. Since I keep getting cursed round trip time values(>600ms) on EU servers on 300±10ms ping, maybe trying to calculate ExtraDelay from server response time and latency isn't such a good idea.

**Comment by Harxen** [comment]
Thanks for the input. I'm not sure about the technical detail here as network stuff is out of me league. However, it sounds like an interim solution is just to make ffxiv_dx11.exe run as administrator? Not sure if that would cause any other issues though

**Comment by Soreepeong** [comment]
Nope, v1.14.0.0 "works as intended" in terms of fetching latency information from server without Administrator permissions, while v1.13a will only do that if the game is ran as Administrator. Both v1.14.0.0 and v1.13a does NOT work as intended in terms of reducing latency as I would expect. I'm not sure about what to do at the moment, but the stopgap fix would be just turning off "Use Delay Detection" feature.

**Comment by Harxen** [comment]
Interesting. For me the delay detection doesn't hurt my performance, but I have to run XIVAlexander as an admin for it to actually open without Windows throwing a fit.

**Comment by Harxen** [comment]
@Soreepeong Seems like v1.14.1.0 doesn't work?

I kept clipping and I tried turning all the options on and off to no success. Things were working fine in v1.14.0.0 after your latest fix to it.

Currently I'm using v1.13a that you linked here before with the updated OP codes in the meanwhile and that works perfectly fine.

**Comment by Harxen** [comment]
From asking a few people yesterday, seems like folks who continue using v1.14.0.0 and just update the OP codes have better performance and don't clip, compared to upgrading to v.1.14.1.0.
