### ISSUE TITLE
does anyone have the opcode for CN server 6.01

### ISSUE THREAD

**Issue by magicalcat133** [Soreepeong/XivAlexander#393]

**Comment by RavenYDY** [comment]
{
	"C2S_ActionRequest": "0x02fb",
	"C2S_ActionRequestGroundTargeted": "0x012f",
	"S2C_ActionEffect01": "0x0258",
	"S2C_ActionEffect08": "0x01a6",
	"S2C_ActionEffect16": "0x0103",
	"S2C_ActionEffect24": "0x0238",
	"S2C_ActionEffect32": "0x0231",
	"S2C_ActorCast": "0x0329",
	"S2C_ActorControl": "0x0282",
	"S2C_ActorControlSelf": "0x0205",
	"S2C_EffectResult5": "0x0329",
	"S2C_EffectResult6": "0x0329",
	"S2C_EffectResult6Basic": "0x0282",
	"Server_IpRange": "109.244.0.0/16, 27.221.0.0/16, 119.97.0.0/16, 162.14.0.0/16",
	"Server_PortRange": "1-65535"
}

**Comment by Cyk971327** [comment]
I tried it and it worked.

**Comment by sAmyAox** [comment]
it works，TY

**Comment by Sookie520** [comment]
Not working, what should we do?

**Comment by sAmyAox** [comment]
1. make sure to enable the plugin Network/Latency and Timing Helper/enable
2. if not working, see the logging window and report the error to the author, if the message is about no address found or portrange, try
Network/troubleshooting take over all ports or manually set 
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"

this might work, at least, this works for me last time.
