### ISSUE TITLE
Does anyone have the opcode for 6.1?

### ISSUE THREAD

**Issue by denma-xiv** [Soreepeong/XivAlexander#397]

**Comment by MrDarkRainBow** [comment]
> {
    "C2S_ActionRequest": "0x00b8",
    "C2S_ActionRequestGroundTargeted": "0x00b8",
    "S2C_ActionEffect01": "0x021b",
    "S2C_ActionEffect08": "0x030e",
    "S2C_ActionEffect16": "0x0153",
    "S2C_ActionEffect24": "0x00e1",
    "S2C_ActionEffect32": "0x0356",
    "S2C_ActorCast": "0x006f",
    "S2C_ActorControl": "0x02e7",
    "S2C_ActorControlSelf": "0x028f",
    "S2C_EffectResult5": "0x02e7",
    "S2C_EffectResult6": "0x02e7",
    "S2C_EffectResult6Basic": "0x02e7",
    "Server_IpRange": "0.0.0.0/0",
    "Server_PortRange": "1-65535"
}

These are the ones I found that seem to be working for me

**Comment by denma-xiv** [comment]
Working for me, thx!
