### ISSUE TITLE
Font replacement - How to keep some of the original game fonts?

### ISSUE THREAD

**Issue by endervad** [Soreepeong/XivAlexander#403]
Hello, I'm having trouble configuring JSON file correctly. My goal is to add Unicode Cyrillic range (U+0400..U+04FF) on top of existing game fonts. For now I'm trying to work only with one of them - Trump Gothic. I've got the font installed and it shows up when I set it up in JSON like this:
```
      "TrumpGothic_34_lobby.fdt": {
        "height": 34,
        "ascent": "game:TrumpGothic_34",
        "lineHeight": "game:TrumpGothic_34",
        "sources": [
          {
            "name": "game:TrumpGothic_34"
          },
          {
            "name": "dwrite:TrumpGothicPro:34",
            "extendRange": false,
            "replace": true
          }
        ]
      },
```
However I wasn't able to figure out how to preserve other fonts. If I delete them from JSON, then there're no fonts in the game besides the one I've configured. If I leave the original fonts like this:
```
      "MiedingerMid_14_lobby.fdt": {
        "height": 14,
        "ascent": "game:MiedingerMid_14",
        "lineHeight": "game:MiedingerMid_14",
        "sources": [
          {
            "name": "game:MiedingerMid_14"
          }
        ]
      },
```
then all of the original fonts become garbled. Same happens if I insert `"replace": true` as their `sources` property. So, what's the correct way to configure preserving original fonts? I couldn't really find an example in existing JSONs.
I'm also not sure how to partially preserve original font. I've configured it in my JSON `replace` only with certain `range` that I specified in another section but I couldn't really check because of the other issue.

Below is the archive with my JSON (GitHub doesn't like pure JSON)
[TrumpGothicPro.zip](https://github.com/Soreepeong/XivAlexander/files/8503644/TrumpGothicPro.zip)

**Comment by Soreepeong** [comment]
What do you mean exactly by "original fonts become garbled"? In any case, if you just want to add glyphs to select existing fonts, then you just have to specify all the original fonts with corresponding original items, and for those select fonts, you just have to specify the extended items.

For example, you wrote:
```json
	"TrumpGothic_184.fdt": {
		"height": 18.4,
		"ascent": "game:TrumpGothic_184",
		"lineHeight": "game:TrumpGothic_184",
		"sources": [
			{
				"name": "game:TrumpGothic_184"
			},
			{
				"name": "dwrite:TrumpGothicPro:18.4",
				"extendRange": false,
				"ranges": [
					"Trump Gothic Pro Cyrillic"
				],
				"replace": true
			}
		]
	}
```

I think you would have meant this:
```json
	"TrumpGothic_184.fdt": {
		"height": 18.4,
		"ascent": "game:TrumpGothic_184",
		"lineHeight": "game:TrumpGothic_184",
		"sources": [
			{
				"name": "game:TrumpGothic_184"
			},
			{
				"name": "dwrite:TrumpGothicPro:18.4",
				"ranges": [
					"Trump Gothic Pro Cyrillic"
				]
			}
		]
	}
```

By default, additional items will only fill the missing glyphs, and only for the specified range of `ranges` is given.

**Comment by endervad** [comment]
I was able to achieve what I wanted by adding `"replace": false` for the fonts that I wanted to stay original. So such fonts looked like this:
```
"MiedingerMid_18_lobby.fdt": {
  "height": 18,
  "ascent": "game:MiedingerMid_18",
  "lineHeight": "game:MiedingerMid_18",
  "sources": [
    {
      "name": "game:MiedingerMid_18",
      "replace": false
    }
  ]
},
```
For some reason though, after first success I wasn't able to reproduce garbled text again even after removing `replace` value, not even after deleting `cache` folder.
