### ISSUE TITLE
Font replacement - Dashes instead of actual characters

### ISSUE THREAD

**Issue by endervad** [Soreepeong/XivAlexander#404]
My team develops a Russian translation mod for FFXIV, and we wanted to add Cyrillic characters to game fonts, as I described in another issue. Our mod is basically a direct edit of EXD files, that we then import via TexTools. And then if an in-game font doesn't support certain characters (in our case all of them except AXIS) then it produces dashes instead.
When doing a test run with default JSONs I noticed that this behavior is still the same on Comic Sans even though it has the whole Unicode available. You can see it on screenshots, I've changed two lines: START to СТАРТ (5 dashes) and "Character Selection" to "Выбор персонажа" (a bunch of dashes at the top). The rest of the lines that were originally AXIS are displayed just fine.
Do you know if there's something that can be done about it?

![20220418081313_1](https://user-images.githubusercontent.com/10913278/163760507-a2710c3d-834f-47c4-8f76-7b361ea48e8f.jpg)
![20220418081328_1](https://user-images.githubusercontent.com/10913278/163760542-265f7461-60a8-4089-a565-1eb0bee2b723.jpg)

**Comment by Soreepeong** [comment]
Don't forget your name also gets displayed on the bottom of character select screen.

Are the glyphs in "CTAPT" not in ASCII range? "-" will be displayed if said glyph is available from the game font files.

**Comment by endervad** [comment]
> Are the glyphs in "CTAPT" not in ASCII range?

No, those are Cyrillic characters (even though look like Latin).

> "-" will be displayed if said glyph is not available from the game font files.

So basically even if a replaced font has the required glyphs, the game's font files determine in the end whether the character is displayed or not?

**Comment by Soreepeong** [comment]
If replaced font files indeed have the glyphs, then it will display the right glyphs. But judging from the other issue, you only replaced Trump Gothic, whereas title menu font is MiedingerMid, so you'll have to replace that.

**Comment by endervad** [comment]
On these screenshots I used [your JSON](https://github.com/Soreepeong/XivAlexander/blob/main/StaticData/FontConfig/ComicSans.json) so they should've changed everything, if I understand correctly.
I will try editing my config in a bit but I figured that it should normally work with you config first.

**Comment by Soreepeong** [comment]
Yes, that is correct. Begin by removing all mentions of comic sans from that json, and nothing should be missing there.

**Comment by Soreepeong** [comment]
Just saying: since you must be fiddling with exh/exd files often, you can use ReplacementFileEntries folder for the ease of testing, in case you weren't doing so already!

**Comment by Soreepeong** [comment]
Check out SourceHanSansK/SC for actual examples of extending glyph ranges for all fonts, since they will correctly extend all fonts to be able to display Korean/Chinese characters.

**Comment by endervad** [comment]
I've found out about your program and its fonts capabilities only 2 hours ago so yeah, I'm not that familiar for now :D I'll keep that in mind, thanks :)
And also I think there's a bit of misunderstanding. For now I want just to see if the game will display Russian text in places where it  prevously didn't work because of the game's fonts. You said that as long as _replaced_ fonts have the required glyphs, they will display. Which is not the case for me on the screenshots - Comic Sans has those Russian glyphs but it still doesn't display them on strings that initially had fonts w/o Russian glyphs. You can tell that the font was correctly applied e.g. by nearby strings on the main menu.

**Comment by Soreepeong** [comment]
Take a look at ComicSans.json:
```json
        "sources": [
          {
            "name": "game:Meidinger_20"
          },
          {
            "name": "dwrite:ComicSans:20",
            "extendRange": false,
            "replace": true
          }
        ]
```

* `"extendRange": false` will **prevent** adding glyphs existing in Comic Sans but did not exist originally in the game.
* `"replace": true` will make glyphs from Comic Sans overwrite even if said glyph was already there.

You want to turn set `extendRange` to `true` (default if omitted), and setting `replace` is optional.

**Comment by Soreepeong** [comment]
Now for `SourceHanSansK.json`:
```json
        "sources": [
          {
            "name": "game:AXIS_12"
          },
          {
            "name": "dwrite:SourceHanSansK:12",
            "ranges": [
              "HangulMinimum"
            ],
            "offsetYModifier": 1
          }
        ]
```

This is simply adding glyphs in "HangulMinimum" range into AXIS, if they didn't already exist in AXIS yet.

**Comment by endervad** [comment]
Okay, it clicked for me, thanks for clarifying, I understand now :D I'll be back after testing real quick.

**Comment by endervad** [comment]
I was able to successfully extend the range, thanks again for explaining :)
