### ISSUE TITLE
Latency reducer not working despite updated Opcodes

### ISSUE THREAD

**Issue by Aevanathema** [Soreepeong/XivAlexander#406]
Despite the fact that I've updated my Opcodes, the Latency Mitigation mode doesn't seem to be working- I'm still clipping oGCD's that would've gone through fine in previous versions of XIVAlexander.
My current options are default save for `Synchronize Processing to Cooldowns and Animation Locks` being turned on (though it behaved the same while turned off) and my Opcodes are, for sake of double checking, as follows:

{
	"C2S_ActionRequest": "0x00b8",
	"C2S_ActionRequestGroundTargeted": "0x0328",
	"S2C_ActionEffect01": "0x021b",
	"S2C_ActionEffect08": "0x030e",
	"S2C_ActionEffect16": "0x0153",
	"S2C_ActionEffect24": "0x00e1",
	"S2C_ActionEffect32": "0x0356",
	"S2C_ActorCast": "0x006f",
	"S2C_ActorControl": "0x02e7",
	"S2C_ActorControlSelf": "0x028f",
	"S2C_EffectResult5": "0x93db",
	"S2C_EffectResult6": "0x93db",
	"S2C_EffectResult6Basic": "0x02e7",
	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24, 153.254.80.0/24",
	"Server_PortRange": "1025-65535"
}

**Comment by rhirama** [comment]
It's happening the same for me, and I tried really hard to not clip them. Before the 6.1 update was fine though D:

**Comment by reiazevedo** [comment]
Same here. If it helps, one of the particularly troublesome skills from what I've seen is GNB's Sonic Break. It clips very often now.

**Comment by retaker** [comment]
Please download the latest release and try again.
