### ISSUE TITLE
CN 6.05 Opcode?

### ISSUE THREAD

**Issue by RavenYDY** [Soreepeong/XivAlexander#409]
Has anyone found CN 6.05 Opcode?

**Comment by RavenYDY** [comment]
{
	"C2S_ActionRequest": "0x02a0",
	"C2S_ActionRequestGroundTargeted": "0x019e",
	"S2C_ActionEffect01": "0x0100",
	"S2C_ActionEffect08": "0x0314",
	"S2C_ActionEffect16": "0x0242",
	"S2C_ActionEffect24": "0x0103",
	"S2C_ActionEffect32": "0x0076",
	"S2C_ActorCast": "0x0155",
	"S2C_ActorControl": "0x00ff",
	"S2C_ActorControlSelf": "0x03b7",
	"S2C_EffectResult5": "0x0155",
	"S2C_EffectResult6": "0x0155",
	"S2C_EffectResult6Basic": "0x00ff",
	"Server_IpRange": "0.0.0.0",
	"Server_PortRange": "1-65535"
}

**Comment by RavenYDY** [comment]
{	
	"C2S_ActionRequest": "0x02a0",
	"C2S_ActionRequestGroundTargeted": "0x019e",
	"S2C_ActionEffect01": "0x0100",
	"S2C_ActionEffect08": "0x0314",
	"S2C_ActionEffect16": "0x0242",
	"S2C_ActionEffect24": "0x0103",
	"S2C_ActionEffect32": "0x0076",
	"S2C_ActorCast": "0x0155",
	"S2C_ActorControl": "0x00ff",
	"S2C_ActorControlSelf": "0x03b7",
	"S2C_EffectResult5": "0x0155",
	"S2C_EffectResult6": "0x0155",
	"S2C_EffectResult6Basic": "0x00ff",
	"Server_IpRange": "109.244.0.0/16, 27.221.0.0/16, 119.97.0.0/16, 162.14.0.0/16",
	"Server_PortRange": "1-65535"
}

**Comment by MnFeN** [comment]
你已经学会自问自答了.jpg

**Comment by ggzyy** [comment]
非常感谢

**Comment by RavenYDY** [comment]
> 

属于求人不如求己了 :)

**Comment by pegasus32** [comment]
请问这个opcode在26号更新之后还能用吗？纽约教育网发现用不了。。。
PS， 很想自己测opcode但是开vpn之后logs接收不到任何操作信息，不开vpn就登不上游戏。。。

**Comment by Notht** [comment]
> 

请问手动设置后两行后opcode直接重置了是怎么回事？

**Comment by SansanDouble** [comment]
大佬们，请问我这里game release一直显示的是JP咋办呀

**Comment by Furygee** [comment]
请问Socket Latency后一直是failed to reslove是怎么回事

**Comment by Circur** [comment]
请问Opcode update check faild:Could not resolve host:raw.githubusercontent.com是怎么回事 按照上面的全部照做了实在看不懂

**Comment by yamato618** [comment]
请问有大佬知道这怎么安装吗，实在搞不明白
