### ISSUE TITLE
Folders that start with "S" try to escape the game folder location string

### ISSUE THREAD

**Issue by anyoneminion** [Soreepeong/XivAlexander#41]
https://i.imgur.com/z0QJpQs.png

https://i.imgur.com/45K7LKU.png

edit: someone posted that this may be related since it's a library you're using https://github.com/nlohmann/json/issues/2652

**Comment by Soreepeong** [comment]
Can you upload the configuration JSON file? That issue is about missing a `\` in JSON so it was a user error, so I think it might be possible that you need to make sure that you did save the configuration file before loading XivAlex.

**Comment by anyoneminion** [comment]
https://pastebin.com/g1e9CjNc

**Comment by Soreepeong** [comment]
Your configuration file works for me, and I can't really think of a reason why it won't work for you. Can you try editing the configuration after running xivalex and using "Edit Configuration" window instead?
