### ISSUE TITLE
Default generated json file not entirely working

### ISSUE THREAD

**Issue by anyoneminion** [Soreepeong/XivAlexander#42]
Honestly not entirely sure what's causing this but have had to do this change for a few of my friends, including myself, to even get the program working.

In order to get it working again, I had to remove every table array that wasn't for the actual path of the game, and then copy the table located on the github's readme over the table that's in the json file.

After that, it begun working for myself and at least 5 other people that I've been instructing to install this program.

**Comment by Soreepeong** [comment]
You need to upload the configuration file you're using, as it just worked for everyone that I know who tried using this. It might be possible that some practically invisible unicode character went in while copy & pasting.

**Comment by anyoneminion** [comment]
The file I posted in issue #41 should double in this regard, since after I had him rename the folder name to /FFXIV/FFXIV/ instead of /SquareEnix/Final Fantasy XIV - A Realm Reborn/, it still wasn't working until I did the fix I mentioned in the OP.
