### ISSUE TITLE
Can't apply EXDF Transformation

### ISSUE THREAD

**Issue by vloslain** [Soreepeong/XivAlexander#427]
![image](https://user-images.githubusercontent.com/68831657/167635579-f8f049e0-c2a3-4b85-96c3-88a9d51c223d.png)
I wanted to use alexander cause today is day of 6.0 on KR server.
But I couldn't install xivalexander with error message. So I re installed the gloval server but it happened again.
I saw issues tab and i think many people struggle with same error. hope you check this. Thanks.

**Comment by vloslain** [comment]
![image](https://user-images.githubusercontent.com/68831657/167655739-483b5db9-5e11-466f-8b77-48fa2b8f9909.png)
[XivAlexander_20220510_234153_620.log](https://github.com/Soreepeong/XivAlexander/files/8662556/XivAlexander_20220510_234153_620.log)

**Comment by vloslain** [comment]
hello, I tried to apply jp to kr server, and it worked. i found the log and adding. hope this help. thanks
[log.zip](https://github.com/Soreepeong/XivAlexander/files/8666913/log.zip)
.

**Comment by Soreepeong** [comment]
This should be worked around in next release. Try out the new version tomorrow or so.

**Comment by Soreepeong** [comment]
Try out the newest release.

**Comment by vloslain** [comment]
works very well! i was about to sleep but i got your reponse mail. and i couldn't wait to apply it. so i'm in front of pc. i found little problem that does not matter lot. when i click navigation buttons it shows descriptions. not the menu name. 
now i can enjoy second 6.0. thank you lot!
![2022-05-12_01-47-12-097_Alive 4 0 1 Performance](https://user-images.githubusercontent.com/68831657/167904601-11315d18-4032-4cf6-9d1d-345856d0203d.png)

**Comment by vloslain** [comment]
hello again. I fixed error upside and playing well thank you. but I got another problem... I tried use unending journey at inn, but error message came out with 'You are not authorized to use the unending journey.' in korean. can i get any idea for this? feel sorry to ask you every time... 
![Inked2022-05-12_05-43-52-258_Alive 4 0 1 Performance_LI](https://user-images.githubusercontent.com/68831657/167945404-ceb56e6b-f625-4842-9dba-287d3a374199.jpg)

**Comment by Soreepeong** [comment]
As a workaround, you can launch the game in any of original languages, and then change Force Display Language before interacting with the Unending Journey. It should show all quests and cutscenes in the language you have selected.

**Comment by Soreepeong** [comment]
Try the newest version. It should fix the unending journey.

**Comment by vloslain** [comment]
works perfectly! I could use it without any problems. thanks many time!
