### ISSUE TITLE
Opcode for Chinese patch 5.4 release

### ISSUE THREAD

**Issue by ClarenceShalave** [Soreepeong/XivAlexander#43]
"ActorCast": "0x0302",
"ActorControl": "0x0038",
"ActorControlSelf": "0x00f2",
"RequestUseAction": "0x0274",
"RequestUseAction2": "0x00bc",
"SkillResultResponse01": "0x0259",
"SkillResultResponse08": "0x012a",
"SkillResultResponse16": "0x0251",
"SkillResultResponse24": "0x01e4",
"SkillResultResponse32": "0x0364",

**Comment by ClarenceShalave** [comment]
This opcode works for me

**Comment by Soreepeong** [comment]
Thank you for sharing!

**Comment by yuanqu2579** [comment]
> "ActorCast": "0x0302",
> "ActorControl": "0x0038",
> "ActorControlSelf": "0x00f2",
> "RequestUseAction": "0x0274",
> "RequestUseAction2": "0x00bc",
> "SkillResultResponse01": "0x0259",
> "SkillResultResponse08": "0x012a",
> "SkillResultResponse16": "0x0251",
> "SkillResultResponse24": "0x01e4",
> "SkillResultResponse32": "0x0364",



> "ActorCast": "0x0302",
> "ActorControl": "0x0038",
> "ActorControlSelf": "0x00f2",
> "RequestUseAction": "0x0274",
> "RequestUseAction2": "0x00bc",
> "SkillResultResponse01": "0x0259",
> "SkillResultResponse08": "0x012a",
> "SkillResultResponse16": "0x0251",
> "SkillResultResponse24": "0x01e4",
> "SkillResultResponse32": "0x0364",

想问问这个5,4版本的代码是贴在哪呀

**Comment by LittleNightmare** [comment]
注意json格式，比方说逗号啥的
ip地址包含猪区，猫区的，CN v5.4 XivAlexander v1.14.1.0

莫古力MoGuLi: `109.244.0.0/16`
猫小胖MaoXiaoPang: `119.97.161.0/16`

```json
	"d:\\ffxiv\\最终幻想xiv\\game\\ffxiv_dx11.exe": {
		"ActorCast": "0x0302",
		"ActorControl": "0x02bb",
		"ActorControlSelf": "0x030c",
		"AddStatusEffect": "0x03b7",
		"AlwaysOnTop": false,
		"BaseLatencyPenalty": 1,
		"GameServerIpRange": "109.244.0.0/16,119.97.161.0/16,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,",
		"GameServerPortRange": "10000,10001-65535",
		"MedianRttCalculationCount": 1,
		"ReducePacketDelay": true,
		"RequestUseAction": "0x0274",
		"RequestUseAction2": "0x00bc",
		"ShowControlWindow": true,
		"ShowLoggingWindow": true,
		"SkillResultResponse01": "0x0259",
		"SkillResultResponse08": "0x012a",
		"SkillResultResponse16": "0x0251",
		"SkillResultResponse24": "0x01e4",
		"SkillResultResponse32": "0x0364",
		"UseAllIpcMessageLogger": false,
		"UseAutoAdjustingExtraDelay": true,
		"UseEffectApplicationDelayLogger": false,
		"UseHighLatencyMitigation": true,
		"UseHighLatencyMitigationLogging": true,
		"UseOpcodeFinder": false
	}
```
add ip addresses of MaoXiaoPang and MoGuLi

**Comment by PrincipleL** [comment]
> 
> 
> 注意json格式，比方说逗号啥的
> ip地址包含猪区，猫区的，CN v5.4 XivAlexander v1.14.1.0
> 
> 莫古力MoGuLi: `109.244.0.0/16`
> 猫小胖MaoXiaoPang: `119.97.161.0/16`
> 
> ```json
> 	"d:\\ffxiv\\最终幻想xiv\\game\\ffxiv_dx11.exe": {
> 		"ActorCast": "0x0302",
> 		"ActorControl": "0x02bb",
> 		"ActorControlSelf": "0x030c",
> 		"AddStatusEffect": "0x03b7",
> 		"AlwaysOnTop": false,
> 		"BaseLatencyPenalty": 1,
> 		"GameServerIpRange": "109.244.0.0/16,119.97.161.0/16,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,",
> 		"GameServerPortRange": "10000,10001-65535",
> 		"MedianRttCalculationCount": 1,
> 		"ReducePacketDelay": true,
> 		"RequestUseAction": "0x0274",
> 		"RequestUseAction2": "0x00bc",
> 		"ShowControlWindow": true,
> 		"ShowLoggingWindow": true,
> 		"SkillResultResponse01": "0x0259",
> 		"SkillResultResponse08": "0x012a",
> 		"SkillResultResponse16": "0x0251",
> 		"SkillResultResponse24": "0x01e4",
> 		"SkillResultResponse32": "0x0364",
> 		"UseAllIpcMessageLogger": false,
> 		"UseAutoAdjustingExtraDelay": true,
> 		"UseEffectApplicationDelayLogger": false,
> 		"UseHighLatencyMitigation": true,
> 		"UseHighLatencyMitigationLogging": true,
> 		"UseOpcodeFinder": false
> 	}
> ```
> 
> add ip addresses of MaoXiaoPang and MoGuLi

What's the IP range of LuXingNiao?
