### ISSUE TITLE
6.11a opcodes?

### ISSUE THREAD

**Issue by Kousuke-kun** [Soreepeong/XivAlexander#435]
Asking if anyone got them ^^

**Comment by kindabusy** [comment]
{
    "C2S_ActionRequest": "0x00b9",
    "C2S_ActionRequestGroundTargeted": "0x00b9",
    "S2C_ActionEffect01": "0x00b5",
    "S2C_ActionEffect08": "0x014f",
    "S2C_ActionEffect16": "0x01b4",
    "S2C_ActionEffect24": "0x03a0",
    "S2C_ActionEffect32": "0x0168",
    "S2C_ActorCast": "0x03df",
    "S2C_ActorControl": "0x024b",
    "S2C_ActorControlSelf": "0x0334",
    "Server_IpRange": "0.0.0.0/0",
    "Server_PortRange": "1-65535"
}
found these but i can't find the status effect ones for whatever reason

**Comment by as200210** [comment]
{
	"C2S_ActionRequest": "0x00b9",
	"C2S_ActionRequestGroundTargeted": "0x00b9",
	"S2C_ActionEffect01": "0x00b5",
	"S2C_ActionEffect08": "0x014f",
	"S2C_ActionEffect16": "0x01b4",
	"S2C_ActionEffect24": "0x03a0",
	"S2C_ActionEffect32": "0x0168",
	"S2C_ActorCast": "0x03df",
	"S2C_ActorControl": "0x024b",
	"S2C_ActorControlSelf": "0x0334",
	"S2C_EffectResult5": "0x93db",
	"S2C_EffectResult6": "0x93db",
	"S2C_EffectResult6Basic": "0x93db",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

**Comment by Soreepeong** [comment]
```json
{
	"C2S_ActionRequest": "0x00b9",
	"C2S_ActionRequestGroundTargeted": "0x01ac",
	"S2C_ActionEffect01": "0x00b5",
	"S2C_ActionEffect08": "0x014f",
	"S2C_ActionEffect16": "0x01b4",
	"S2C_ActionEffect24": "0x03a0",
	"S2C_ActionEffect32": "0x0168",
	"S2C_ActorCast": "0x03df",
	"S2C_ActorControl": "0x024b",
	"S2C_ActorControlSelf": "0x0334",
	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24, 153.254.80.0/24",
	"Server_PortRange": "1025-65535"
}
```

Or, update xivalex to receive latest opcodes automatically (when I upload the files, that is.)
