### ISSUE TITLE
High FPS drop issue

### ISSUE THREAD

**Issue by Arischid** [Soreepeong/XivAlexander#44]
I am using the latest version on Windows10. My FPS dropped from 90 to 30 after I loaded it. When I unloaded it, FPS returned to normal. Is there anyway to fix this issue?

**Comment by Soreepeong** [comment]
This shouldn't be happening. Does the program persist even when you turn off "Use Delay Detection"?

**Comment by Arischid** [comment]
Yes, it still persists

**Comment by Soreepeong** [comment]
Are you using other addons (reshade, etc)? When I use this program, I can't feel any performance difference. Just in case - are you using HDD or SSD?

**Comment by Soreepeong** [comment]
Probably something to do with using locks in hooked socket functions, but can't really verify it myself.

@retaker Which VPN software are you using? Does it install TAP-Windows adapter and does the normal VPN stuff, or does something wack?

**Comment by retaker** [comment]
@Soreepeong https://www.htjsq.com/ This is the one I use. They are updating their service frequently and became not compatible with XivAlexander in about January. I've requested a refund and switched to another VPN which solves the problem.

**Comment by Soreepeong** [comment]
Judging purely from site design, it looks like it's not actually a vpn but more of a proxy software, and definitely a good choice getting a refund. Regardless, I guess I can try implementing socket hooks without locks.

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.6.0

This will not place locks when dealing with socket hooks. Bear in mind though that I have never been able to reproduce slowdown when XivAlexander is active, so this might not have any effect on your side.
