### ISSUE TITLE
opcode for 6.15?

### ISSUE THREAD

**Issue by denma-xiv** [Soreepeong/XivAlexander#447]

**Comment by quaesop** [comment]
Might not be available for a while until the issue in ticket 446 is resolved

**Comment by luizog100** [comment]
> 

what error is that ?

**Comment by reiazevedo** [comment]
It's the error in this issue: #446

**Comment by denma-xiv** [comment]
Updated on commit 00f8f63df06a7b40d93050b48dacf5083fe1db69 closing

**Comment by denma-xiv** [comment]
[v1.14.8.53](https://github.com/Soreepeong/XivAlexander/releases/latest)
