### ISSUE TITLE
When will XivAlex be updated to 6.15?

### ISSUE THREAD

**Issue by TahmeedWolf** [Soreepeong/XivAlexander#448]
Is XivAlex down due to new patch? If so, when will it be updated?
Thanks :)

**Comment by zMigueel** [comment]
#446

**Comment by Ustymk** [comment]
If you opened up your log window in game you would see error messages so no real point to post this question especially since the patch just came out. Just be patient and wait, the dev has a life too outside of ffxiv.

**Comment by TahmeedWolf** [comment]
How do you access the log window? I'm new to plugins and stuff so I don't know the commands. Also I don't know how long it usually takes for plugins to get updates whether its xivalex or other quick launcher plugins. How long does it usually take? Also if you took offence from the my question, don't. It was just a genuine question. 

> If you opened up your log window in game you would see error messages so no real point to post this question especially since the patch just came out. Just be patient and wait, the dev has a life too outside of ffxiv.



> If you opened up your log window in game you would see error messages so no real point to post this question especially since the patch just came out. Just be patient and wait, the dev has a life too outside of ffxiv.

I've XivAlex in the Boot folder along with Quicklauncher so I don't get any logs, it goes straight into the game so I couldn't see the logs. How do you access the log window? I'm new to plugins and stuff so I don't know the commands. Also I don't know how long it usually takes for plugins to get updates whether its xivalex or other quick launcher plugins. How long does it usually take? Also if you took offence from the my question, don't. It was just a genuine question.

**Comment by arcsolace** [comment]
@TahmeedWolf https://github.com/Soreepeong/XivAlexander/wiki/How-to-find-opcodes

**Comment by Osmone** [comment]
> How long does it usually take?

As long as the devs take. XivAlexander and Dalamud (XivLauncher) are both updated every patch, but it takes time especially when the patch changes the way packets are sent/received. Sometimes it takes 1 day, sometimes 3 days, sometimes a week. Depends on the patch.
