### ISSUE TITLE
I can't find XivAlexanderLoader.exe , XivAlexander.dll , or XivAlexander.dll.json

### ISSUE THREAD

**Issue by Toothpick** [Soreepeong/XivAlexander#45]
I downloaded the zip file XivAlexander-main and its contents don't include any of the above files.
I don't know if i need another program to run XivAlexander.
Any insight would be appreciated.

**Comment by Soreepeong** [comment]
Try using the [Releases](https://github.com/Soreepeong/XivAlexander/releases) page. Also, readme file has been updated, to prevent people from downloading the source code instead of the program.
