### ISSUE TITLE
Are there opcodes for 6.15?

### ISSUE THREAD

**Issue by IzumiKyouka** [Soreepeong/XivAlexander#459]
Just updated XivAlexander to 1.14.8.53 but still is getting data errors like

[1969-12-31 20:00:00.000] Length=64 ConnType=2 Count=1 Gzip=2
2022-06-16 01:16:02.007	SocketHook	Error: Data error

Does anyone know what's going wrong?

**Comment by retaker** [comment]
Not sure what's going, you can download and try again with the latest opcodes.
