### ISSUE TITLE
XivAlexander isn't working, and I'm not sure why.

### ISSUE THREAD

**Issue by Desolance** [Soreepeong/XivAlexander#46]
So the program straight up isn't working for me and I'm not sure why. It's finding the game path just fine and the logging window is recording activity, but my clipping is the exact same with and without the program (0.7~). Nothing is being recorded on the log window unless I enable either IPC Message Logger or Effect Application Delay Logger, for what that's worth.
![ffxiv_dx11_x6ZUEuVRGt](https://user-images.githubusercontent.com/82320976/114305293-92511200-9aa5-11eb-8f4e-aff815abbeef.png)

**Comment by Soreepeong** [comment]
Just to make sure, do you have this option on?
![image](https://user-images.githubusercontent.com/3614868/114305520-5fddfe00-9b13-11eb-9a4e-9670aea7a8d4.png)

**Comment by Desolance** [comment]
Sorry for the delayed response, I do have high latency mit enabled, yes

**Comment by Desolance** [comment]
![chrome_8MVx8iRq7N](https://user-images.githubusercontent.com/82320976/114313137-444b0700-9ac3-11eb-8a11-bc7086294416.png)
![ffxiv_dx11_PN5MPi89h1](https://user-images.githubusercontent.com/82320976/114313146-4dd46f00-9ac3-11eb-8e1b-dbdba9a6f1b6.png)
Here's my log. I hit a striking dummy for about 20 seconds and nothing was logged.

**Comment by Desolance** [comment]
I have the default opcodes from the newest release

**Comment by Harxen** [comment]
Is this related to #39 maybe? The OP there and I had to revert to the previous version to get it working again

**Comment by Desolance** [comment]
Nah, that's not the issue either. I've used all iterations of the program, it's just never worked for me.

**Comment by Desolance** [comment]
I think it might be opcode related? But when I look at the log, it all looks like gibberish and I'm having trouble deciphering where the opcodes are among the mess of code.
![Uploading ffxiv_dx11_o9tSENTnU6.png…]()

**Comment by Desolance** [comment]
At least, opcodes being the issue are the only logical conclusion I can arrive to.

**Comment by Desolance** [comment]
any help would be greatly appreciated. i really want to get this to work.

**Comment by Soreepeong** [comment]
![image](https://user-images.githubusercontent.com/3614868/114480622-dd059200-9c3d-11eb-83a8-1244536c6f39.png)

You probably missed that you added `Games\` into game installation path. Open up `XivAlexander.dll.json` with notepad or a text editor, and change game installation path to include `Games` in it. Make sure you write `\` as `\\`.
