### ISSUE TITLE
Opcode?

### ISSUE THREAD

**Issue by zeroxetc** [Soreepeong/XivAlexander#468]
Hi, does any kind soul have the new opcodes?

**Comment by RaphaGrey** [comment]
try this one idk if it's 100% correct but it's working for me

{
    "C2S_ActionRequest": "0x0344",
    "C2S_ActionRequestGroundTargeted": "0x018d",
    "S2C_ActionEffect01": "0x00ee",
    "S2C_ActionEffect08": "0x03aa",
    "S2C_ActionEffect16": "0x02ba",
    "S2C_ActionEffect24": "0x0211",
    "S2C_ActionEffect32": "0x02d5",
    "S2C_ActorCast": "0x03c2",
    "S2C_ActorControl": "0x036e",
    "S2C_ActorControlSelf": "0x02f0",
    "Server_IpRange": "124.150.157.0/24, 153.254.80.0/24, 202.67.52.0/24, 204.2.229.0/24, 80.239.145.0/24",
    "Server_PortRange": "1025-65535"
}

**Comment by RedSoyuz** [comment]
Just update your app. The current version updates the opcodes automatically.
