### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by a42020** [Soreepeong/XivAlexander#470]
hi my game is crashing since the update whenever i try to weave in mug and bunshin, as soon as i click on bunshin the game crashes. updated the opcodes and have the latest version installed. not sure whats causing this, any help would be appreciated!

**Comment by a42020** [comment]
crashes only on XIVlauncher, official launcher works fine. Could this have something to do with the recent dalamud update?

**Comment by a42020** [comment]
just pressing battle litany crashes my game as well.

**Comment by hammypants** [comment]
Launch both Dalamud *and* XIVAlexander with administrative rights.

**Comment by a42020** [comment]
apparently if i disable material UI installed through penumbra, it fixes the issue
