### ISSUE TITLE
Update Errror

### ISSUE THREAD

**Issue by ArynBlack** [Soreepeong/XivAlexander#478]
Hello, I'm noticing that when I try to update through XivAlex itself that an error pops up where while it does download to an __UPDATE___ folder the process fails because it tries to pull the update content from the wrong path, from the look of it. 

![Screenshot 2022-07-14 13 00 03](https://user-images.githubusercontent.com/3959736/179051421-fc4bc09f-0ea5-4bd2-b9b5-61b8ae39d14a.png)

 It definitely has downloaded properly but instead of checking for it there it doesn't check for it in the subfolder it creates, in this case, 'XivAlexander_1_14_8_54_df4e86a'

**Comment by Korovia** [comment]
The self updater didnt work for me either. You'll have to manually uninstall the old version and reapply the new one through the files it had downloaded.

**Comment by retaker** [comment]
https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.8.54
The problem should have been fixed, please download the latest relase from the link above.
