### ISSUE TITLE
will not start 

### ISSUE THREAD

**Issue by kurumiiichan** [Soreepeong/XivAlexander#48]
when i click on the loader to run it will not start up how to fix?

**Comment by Soreepeong** [comment]
* Check if your antivirus software is getting in the way. You might have to add exceptions.
* The game in DirectX11 mode must be running already.
* If it doesn't work, try running as Administrator.

**Comment by kurumiiichan** [comment]
it was working fine befor i updated the game today i always ran it in admin i just thout i would ask to see why it happend

**Comment by kurumiiichan** [comment]
oh its working now my pc reset all settings ty for help
