### ISSUE TITLE
CN 6.1 opcode?

### ISSUE THREAD

**Issue by sAmyAox** [Soreepeong/XivAlexander#486]
有了踹我一脚.jpg
Someone plz

**Comment by ZiqiSongTony** [comment]
有了也踹我一脚 plz

**Comment by MnFeN** [comment]
{
	"C2S_ActionRequest": "0x010c",
	"C2S_ActionRequestGroundTargeted": "0x015d",
	"S2C_ActionEffect01": "0x00c0",
	"S2C_ActionEffect08": "0x02c2",
	"S2C_ActionEffect16": "0x02b9",
	"S2C_ActionEffect24": "0x0114",
	"S2C_ActionEffect32": "0x93db",
	"S2C_ActorCast": "0x0154",
	"S2C_ActorControl": "0x022c",
	"S2C_ActorControlSelf": "0x010c",
	"S2C_AddStatusEffect": "0x93db",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

ActionEffect32 和 AddStatusEffect 是错的，临时先用着吧，后面那个忘了怎么查了

**Comment by sAmyAox** [comment]
ok， 那我去改改再po上来

**Comment by sAmyAox** [comment]
{
	"C2S_ActionRequest": "0x010c",
	"C2S_ActionRequestGroundTargeted": "0x015d",
	"S2C_ActionEffect01": "0x00c0",
	"S2C_ActionEffect08": "0x02c2",
	"S2C_ActionEffect16": "0x02b9",
	"S2C_ActionEffect24": "0x0114",
	"S2C_ActionEffect32": "0x0218",
	"S2C_ActorCast": "0x0154",
	"S2C_ActorControl": "0x022c",
	"S2C_ActorControlSelf": "0x010c",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

AddStatusEffect 好像被删了来着？

**Comment by RavenYDY** [comment]
前两个不太对，
{
	"C2S_ActionRequest": "0x015d",
	"C2S_ActionRequestGroundTargeted": "0x0133",
	"S2C_ActionEffect01": "0x00c0",
	"S2C_ActionEffect08": "0x02c2",
	"S2C_ActionEffect16": "0x02b9",
	"S2C_ActionEffect24": "0x0114",
	"S2C_ActionEffect32": "0x0218",
	"S2C_ActorCast": "0x0154",
	"S2C_ActorControl": "0x022c",
	"S2C_ActorControlSelf": "0x010c",
	"Server_IpRange": "109.244.0.0/16, 27.221.0.0/16, 119.97.0.0/16, 162.14.0.0/16",
	"Server_PortRange": "1-65535"
}

**Comment by ychen0894** [comment]
Has anyone tested the 

> 前两个不太对， { "C2S_ActionRequest": "0x015d", "C2S_ActionRequestGroundTargeted": "0x0133", "S2C_ActionEffect01": "0x00c0", "S2C_ActionEffect08": "0x02c2", "S2C_ActionEffect16": "0x02b9", "S2C_ActionEffect24": "0x0114", "S2C_ActionEffect32": "0x0218", "S2C_ActorCast": "0x0154", "S2C_ActorControl": "0x022c", "S2C_ActorControlSelf": "0x010c", "Server_IpRange": "109.244.0.0/16, 27.221.0.0/16, 119.97.0.0/16, 162.14.0.0/16", "Server_PortRange": "1-65535

Anyone else confirmed? Why it didn't seem to work on mine?

**Comment by ychen0894** [comment]
Anyone else confirmed? Why it doesn't seem to work on mine?

**Comment by sAmyAox** [comment]
完全没找到0x0133在哪里，你是用什么技能找到的？

**Comment by RavenYDY** [comment]
按他的提示，缩地，庇护所，地星这样的地面放置类技能

**Comment by sAmyAox** [comment]
确实，我的问题，改了之后应该就ok了，忘记腐秽大地改了（x

**Comment by sAmyAox** [comment]
{
	"C2S_ActionRequest": "0x015d",
	"C2S_ActionRequestGroundTargeted": "0x0133",
	"S2C_ActionEffect01": "0x00c0",
	"S2C_ActionEffect08": "0x02c2",
	"S2C_ActionEffect16": "0x02b9",
	"S2C_ActionEffect24": "0x0114",
	"S2C_ActionEffect32": "0x0218",
	"S2C_ActorCast": "0x0154",
	"S2C_ActorControl": "0x022c",
	"S2C_ActorControlSelf": "0x010c",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}
这个应该是最终版本了，有问题的话可以再踢我一脚.jpg

**Comment by Lot-teR** [comment]
还是不太行，需要把亚历山大更新至最新版吗？

**Comment by RavenYDY** [comment]
需要更新到最新版

**Comment by sAmyAox** [comment]
能更新最好更新一下，同时可以开启 network - troubleshooting - takeover all ports 和 takeover all address

**Comment by ayaseprprpr** [comment]
> { "C2S_ActionRequest": "0x015d", "C2S_ActionRequestGroundTargeted": "0x0133", "S2C_ActionEffect01": "0x00c0", "S2C_ActionEffect08": "0x02c2", "S2C_ActionEffect16": "0x02b9", "S2C_ActionEffect24": "0x0114", "S2C_ActionEffect32": "0x0218", "S2C_ActorCast": "0x0154", "S2C_ActorControl": "0x022c", "S2C_ActorControlSelf": "0x010c", "Server_IpRange": "0.0.0.0/0", "Server_PortRange": "1-65535" } 这个应该是最终版本了，有问题的话可以再踢我一脚.jpg

感谢代码，但是我目前使用好像也是无效的_(:з)∠)_

**Comment by EricaNoir** [comment]
> { "C2S_ActionRequest": "0x015d", "C2S_ActionRequestGroundTargeted": "0x0133", "S2C_ActionEffect01": "0x00c0", "S2C_ActionEffect08": "0x02c2", "S2C_ActionEffect16": "0x02b9", "S2C_ActionEffect24": "0x0114", "S2C_ActionEffect32": "0x0218", "S2C_ActorCast": "0x0154", "S2C_ActorControl": "0x022c", "S2C_ActorControlSelf": "0x010c", "Server_IpRange": "0.0.0.0/0", "Server_PortRange": "1-65535" } 这个应该是最终版本了，有问题的话可以再踢我一脚.jpg

试了一下还是不行的样子

**Comment by sAmyAox** [comment]
> 更新一下alexander

**Comment by EricaNoir** [comment]
> > { "C2S_ActionRequest": "0x015d", "C2S_ActionRequestGroundTargeted": "0x0133", "S2C_ActionEffect01": "0x00c0", "S2C_ActionEffect08": "0x02c2", "S2C_ActionEffect16": "0x02b9", "S2C_ActionEffect24": "0x0114", "S2C_ActionEffect32": "0x0218", "S2C_ActorCast": "0x0154", "S2C_ActorControl": "0x022c", "S2C_ActorControlSelf": "0x010c", "Server_IpRange": "0.0.0.0/0", "Server_PortRange": "1-65535" } 这个应该是最终版本了，有问题的话可以再踢我一脚.jpg
> 
> 试了一下还是不行的样子

明白了 是我改错地方了

**Comment by ayaseprprpr** [comment]
我的XIVAlexander版本是1_14_8_54_df4e86a_2 应该是最新的


> > > { "C2S_ActionRequest": "0x015d", "C2S_ActionRequestGroundTargeted": "0x0133", "S2C_ActionEffect01": "0x00c0", "S2C_ActionEffect08": "0x02c2", "S2C_ActionEffect16": "0x02b9", "S2C_ActionEffect24": "0x0114", "S2C_ActionEffect32": "0x0218", "S2C_ActorCast": "0x0154", "S2C_ActorControl": "0x022c", "S2C_ActorControlSelf": "0x010c", "Server_IpRange": "0.0.0.0/0", "Server_PortRange": "1-65535" } 这个应该是最终版本了，有问题的话可以再踢我一脚.jpg
> > 
> > 
> > 试了一下还是不行的样子
> 
> 明白了 是我改错地方了

请问你的修改后可以用了吗？roaming和插件里的opcode我都修改了，但是测试起来还是没有效果。我的插件版本是XivAlexander_1_14_8_54_df4e86a_2，应该是最新的

**Comment by sAmyAox** [comment]
> 

有没有启用插件呢，更新后要重新注入一次的最好

**Comment by ayaseprprpr** [comment]
> > 
> 
> 有没有启用插件呢，更新后要重新注入一次的最好

有的，重新卸载又注入了一次，上次使用6.05的code可以正常使用的（上次好像是你的贴子）

**Comment by kiyimato** [comment]
> > 
> 
> 有没有启用插件呢，更新后要重新注入一次的最好

试过了我也不太行

**Comment by kiyimato** [comment]
> > > 
> > 
> > 
> > 有没有启用插件呢，更新后要重新注入一次的最好
> 
> 试过了我也不太行

好像又可以了

**Comment by MnFeN** [comment]
> 确实，我的问题，改了之后应该就ok了，忘记腐秽大地改了（x

对哦，腐秽大地改了，我说怎么查的时候不太对劲

**Comment by geoduckxbbqzw** [comment]
现在这个可以用吗，我用UU加速器好像还是会卡GCD

**Comment by sAmyAox** [comment]
还有问题请发新的issue出来，并附上opcode错误的地方

**Comment by WiJoWill** [comment]
感觉机工的过热连还是有问题。晚点试试看贴上来

**Comment by sAmyAox** [comment]
> 感觉机工的过热连还是有问题。晚点试试看贴上来

更新了815热补丁的opcode
