### ISSUE TITLE
CN 6.1 opcode， post-August 15 hotfix

### ISSUE THREAD

**Issue by sAmyAox** [Soreepeong/XivAlexander#487]
{
"C2S_ActionRequest": "0x01b7",
"C2S_ActionRequestGroundTargeted": "0x006a",
"S2C_ActionEffect01": "0x0251",
"S2C_ActionEffect08": "0x0184",
"S2C_ActionEffect16": "0x026f",
"S2C_ActionEffect24": "0x00f2",
"S2C_ActionEffect32": "0x00ec",
"S2C_ActorCast": "0x01d4",
"S2C_ActorControl": "0x0375",
"S2C_ActorControlSelf": "0x02d8",
"Server_IpRange": "0.0.0.0/0",
"Server_PortRange": "1-65535"
}
 [@815hotfix后的code，来自https://github.com/Soreepeong/XivAlexander/issues/490
有问题请区看wiki里的troubleshoot， code错了请评论code错误的地方和正确的内存地址。

**Comment by geoduckxbbqzw** [comment]
Opcode update check failed: schannel: failed to receive handshake, SSL/TLS connection failed 
请问这句是什么意思

**Comment by geoduckxbbqzw** [comment]
是我操作码哪里错了吗

**Comment by sAmyAox** [comment]
有没有可能，你把opcode复制进去，把检查opcode更新关掉，就能用了

**Comment by geoduckxbbqzw** [comment]
好的大哥对不起我比较小白我去试试quq

**Comment by geoduckxbbqzw** [comment]
感谢大哥弄好了应该（

**Comment by sAmyAox** [comment]
好了就行 （黑猫点头.jpg

**Comment by KemSeet** [comment]
牛逼哥，你是这个👍

**Comment by ayaseprprpr** [comment]
搞定了！！感谢提供opcode！之前是我操作有误导致的

**Comment by MnFeN** [comment]
顺便问一下，`S2C_AddStatusEffect` 这个现在不用了吗？我看查找 opcode 的页面里这个被换成了 `S2C_EffectResult5` ` S2C_EffectResult6` `S2C_EffectResult6Basic` 这三个，但是 Log 里面这四个全都没有

**Comment by weekendbig** [comment]
> 有没有可能，你把opcode复制进去，把检查opcode更新关掉，就能用了

大佬，请问怎么操作，我改了opcode后进游戏后没有效果

**Comment by sAmyAox** [comment]
> 顺便问一下，`S2C_AddStatusEffect` 这个现在不用了吗？我看查找 opcode 的页面里这个被换成了 `S2C_EffectResult5` ` S2C_EffectResult6` `S2C_EffectResult6Basic` 这三个，但是 Log 里面这四个全都没有

https://github.com/Soreepeong/XivAlexander/issues/361#issuecomment-1061854314，原作者在这里写了EffectResult6/basic 只影响你记录buff的时间，并不会影响双插和判定

**Comment by sAmyAox** [comment]
> > 有没有可能，你把opcode复制进去，把检查opcode更新关掉，就能用了
> 
> 关掉了检查更新还是没用

troubleshooting里勾选 take over all ports 和 all address，一般来说是因为开了加速器导致的，勾选上就可以用了（大概
