### ISSUE TITLE
6.2 Opcodes NA

### ISSUE THREAD

**Issue by Shambambulish** [Soreepeong/XivAlexander#491]
{
	"C2S_ActionRequest": "0x02b0",
	"C2S_ActionRequestGroundTargeted": "0x03c6",
	"S2C_ActionEffect01": "0x0350",
	"S2C_ActionEffect08": "0x0230",
	"S2C_ActionEffect16": "0x0385",
	"S2C_ActionEffect24": "0x03e2",
	"S2C_ActionEffect32": "0x01ec",
	"S2C_ActorCast": "0x03cc",
	"S2C_ActorControl": "0x02b4",
	"S2C_ActorControlSelf": "0x01ae",
	"Server_IpRange": "124.150.157.0/24, 153.254.80.0/24, 202.67.52.0/24, 204.2.229.0/24, 80.239.145.0/24",
	"Server_PortRange": "1025-65535"
}

first time finding them myself, hope this is is correct as it works for me and a buddy
not sure if codes are global, client specific, region specific or what but I'm EU & friend is SEA, we both play on NA & this works

**Comment by theabhishek2511** [comment]
are these unchanged this time? i was unsubbed for a month and mine are the same.

**Comment by venomin30** [comment]
@Soreepeong already commited this 15 hours ago: https://github.com/Soreepeong/XivAlexander/commit/b24d72c7259551b6370b2b520a7d43092202f187

**Comment by Korovia** [comment]
Should we wait a main version update or is opcodes update sufficient to use Alexander?

**Comment by Korovia** [comment]
> Should we wait a main version update or is opcodes update sufficient to use Alexander?

Just went yolo and tried it myself. It worked. No crashes.

**Comment by ZeteCx** [comment]
HI, so for dummies, how do i apply it?
