### ISSUE TITLE
6.2 Persistent Crashes

### ISSUE THREAD

**Issue by lunardour** [Soreepeong/XivAlexander#492]
Hi, been experiencing nearly insta-crashes (after entering the game worldspace) since updating to patch, all crash logs present the same error under the thread section as this one. Crashes persisted after PC restart, as well as with admin mode on/off for the game executable.
GShade is also (correctly) applied onto the installation, in case that's relevant. I'm just posting this issue because I'm not certain if my case is an isolated one or if it's a wider issue due to the game patch. Latest log attached below.
[XivAlexander_20220823_173546_100.log](https://github.com/Soreepeong/XivAlexander/files/9403891/XivAlexander_20220823_173546_100.log)

**Comment by alsiniz** [comment]
6.2 is not supported. If you're new to 3rd party tools with FFXIV, almost every patch breaks third party tools, especially big content patches. Wait for a newer release.

**Comment by lunardour** [comment]
After extensive troubleshooting it turned out that the problem was not tied to XivAlex and that it works perfectly fine as of right now. I'll close this issue, sorry for any possible confusion caused.
