### ISSUE TITLE
[Help] Are My Configurations Correct?

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#50]
Hello, thank you so much for the previous reply.
I've just changed the **XivAlexander.dll** configuration like the image below. **(Korean 5.35)**
![2](https://user-images.githubusercontent.com/82459386/114582930-06fd9980-9cbc-11eb-9770-11bca0ff124e.JPG)

**Have I done this right?**

The following is the **"Show Logging Window" results that I was getting.**
![1](https://user-images.githubusercontent.com/82459386/114582951-0d8c1100-9cbc-11eb-8718-4f19f5cd6500.JPG)

Sorry for the repetitive questions, and thanks again for the great software !! :)
I was so worried and frustrated about missing weaving and experiencing delayed latency.. U saved my life !!

**Comment by Soreepeong** [comment]
Yes, this looks right, but since you're playing this on a very low ping, turning on "Use Delay Detection" will help you.

**Comment by justin767** [comment]
> Yes, this looks right, but since you're playing this on a very low ping, turning on "Use Delay Detection" will help you this time!

Should I turn off "Use Delay Detection" when I play in a higher ping? I'll soon be playing Korean server in US.

**Comment by Soreepeong** [comment]
Yes, you'll want to turn that off when you're playing above 40ms-ish ping.

**Comment by justin767** [comment]
> Yes, you'll want to turn that off when you're playing above 40ms-ish ping.

Thanks so much for the reply. Just a quick last question:

I have 3 directories in my .dll file like below. Are the configurations correct? (I play on 5.35 Korean server).
![1](https://user-images.githubusercontent.com/82459386/114637358-199bc100-9d04-11eb-8acb-9be97e012256.JPG)

sorry for keep bothering you.

**Comment by Soreepeong** [comment]
Yeah, this should work.
