### ISSUE TITLE
Alexander not working(JP)?

### ISSUE THREAD

**Issue by 4Head420** [Soreepeong/XivAlexander#500]
I have used Alexander for months, and it's always felt amazing, but recently, maybe the past month or so, i's felt like it's not working at all. When trying to double weave I'll mash the button I want multiple times, I'll see being pressed on the hotbar, but nothing happens, this never happened before.

I tried a clean uninstall/reinstall, but it didn't help.

What changed so that this happens? What can I do to fix it.
Really hard to play the game without Alex, so the help is appreciated!

**Comment by sagono** [comment]
It is not working for JP servers  since 6.2 patch :(

**Comment by 4Head420** [comment]
Has this been confirmed? I play on JP so that would make sense, but where is this coming from?

**Comment by sagono** [comment]
I am not sure, but I am on JP servers, it is not working for me.

**Comment by Cort69** [comment]
It's not working for me on NA servers

**Comment by 4Head420** [comment]
Is anything ever done to fix this sort of issues?

**Comment by retaker** [comment]
Please try to download the latest release and do "check for opcodes updates" after installation or "load once" in XivAlex's control window.
