### ISSUE TITLE
CN 6.11 9/6 Hotfix Opcode

### ISSUE THREAD

**Issue by ZiqiSongTony** [Soreepeong/XivAlexander#501]

**Comment by ZiqiSongTony** [comment]
{
	"C2S_ActionRequest": "0x0212",
	"C2S_ActionRequestGroundTargeted": "0x03d3",
	"S2C_ActionEffect01": "0x006d",
	"S2C_ActionEffect08": "0x01ab",
	"S2C_ActionEffect16": "0x01b6",
	"S2C_ActionEffect24": "0x024e",
	"S2C_ActionEffect32": "0x00c7",
	"S2C_ActorCast": "0x00ff",
	"S2C_ActorControl": "0x012d",
	"S2C_ActorControlSelf": "0x02b4",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}
我这边不好用我自己也找了一下也是第一次，我这里好像有用，只有前两行不一样

**Comment by sagono** [comment]
想问一下怎么自己找代码？

**Comment by ZiqiSongTony** [comment]
> 
作者有写方法，照着做就行
https://github.com/Soreepeong/XivAlexander/issues/501#issuecomment-1258273618
