### ISSUE TITLE
XIVAlexander Opens Install XIVAlexander with XIVLauncher

### ISSUE THREAD

**Issue by Sharess123** [Soreepeong/XivAlexander#502]
Hey, so I've Installed XIVAlexander as d3d9 and D3d11, and set XIVLauncher to load the XivAlexanderLoader64.exe on startup, but when I start the game via XIVLauncher, I get the Install XIVAlexander window. 

I can get it to load via Load Once and proceed that way but I thought there was a better way to load it.
What am I missing?

![image](https://user-images.githubusercontent.com/89360723/189175641-3cfe066f-74ca-4e4a-b583-24261dbac0c7.png)
![image](https://user-images.githubusercontent.com/89360723/189175889-c6b76ac2-7eed-434d-bf73-b3754d150eae.png)
![image](https://user-images.githubusercontent.com/89360723/189176109-8381fde7-6a99-4332-a4c5-792afe28edf3.png)
![image](https://user-images.githubusercontent.com/89360723/189176256-e336b18d-9cbb-4c0e-ae5c-2aafca77608d.png)

**Comment by J-Dawe** [comment]
If you choose to install XivAlexqander, you don't have to run the executable; it will automatically load when you start the game, even if you start it through XIVLauncher.

**Comment by Sharess123** [comment]
> If you choose to install XivAlexqander, you don't have to run the executable; it will automatically load when you start the game, even if you start it through XIVLauncher.

Odd, when i start the game nothing loads via the XIV Launcher...
Should I uninstall the launcher, then restart the program, and install all 3 of the top utterances and try that?

**Comment by Sharess123** [comment]
Turns out when I uninstalled fully, deleted all old files, removed all old versions in all appdata local/roaming and reinstalled, everything works now lol.
