### ISSUE TITLE
6.21 09/13 Global Opcodes

### ISSUE THREAD

**Issue by reiazevedo** [Soreepeong/XivAlexander#506]
Can anyone be a bro and post them?

**Comment by retaker** [comment]
{
  "C2S_ActionRequest": "0x024e",
  "C2S_ActionRequestGroundTargeted": "0x0292",
  "S2C_ActionEffect01": "0x01cd",
  "S2C_ActionEffect08": "0x035c",
  "S2C_ActionEffect16": "0x00b0",
  "S2C_ActionEffect24": "0x0276",
  "S2C_ActionEffect32": "0x01f5",
  "S2C_ActorCast": "0x02e8",
  "S2C_ActorControl": "0x0335",
  "S2C_ActorControlSelf": "0x02ed",
  "Server_IpRange": "124.150.157.0/24, 153.254.80.0/24, 202.67.52.0/24, 204.2.229.0/24, 80.239.145.0/24",
  "Server_PortRange": "1025-65535"
}
