### ISSUE TITLE
International SkillResultResponse32 incorrect in README?

### ISSUE THREAD

**Issue by SimonPilkington** [Soreepeong/XivAlexander#51]
Posting because it seems like this comment wasn't noticed.

@Soreepeong Are we sure SkillResultResponse32 is 0x0d20? I'm getting 0x02c5 like owopeachy after two runs.

_Originally posted by @SimonPilkington in https://github.com/Soreepeong/XivAlexander/issues/47#issuecomment-818776325_

**Comment by Soreepeong** [comment]
Ah, sorry about missing out on that. I didn't exactly check the opcodes myself, so if that's the case, I'll change it.

**Comment by SimonPilkington** [comment]
No problem; the rest seem to be correct.
