### ISSUE TITLE
CN 6.15 OpCodes

### ISSUE THREAD

**Issue by NukoOoOoOoO** [Soreepeong/XivAlexander#513]
```
{
	"C2S_ActionRequest": "0x69",
	"C2S_ActionRequestGroundTargeted": "0x25B",
	"S2C_ActionEffect01": "0x228",
	"S2C_ActionEffect08": "0xEF",
	"S2C_ActionEffect16": "0xC3",
	"S2C_ActionEffect24": "0x3BF",
	"S2C_ActionEffect32": "0x2B2",
	"S2C_ActorCast": "0x2E5",
	"S2C_ActorControl": "0x1D4",
	"S2C_ActorControlSelf": "0x12C",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}
```

**Comment by Carbonll** [comment]
HERO!

**Comment by Mythr4** [comment]
Cheers!

**Comment by RavenYDY** [comment]
{
	"C2S_ActionRequest": "0x02e0",
	"C2S_ActionRequestGroundTargeted": "0x025b",
	"S2C_ActionEffect01": "0x02ad",
	"S2C_ActionEffect08": "0x01c6",
	"S2C_ActionEffect16": "0x0195",
	"S2C_ActionEffect24": "0x0104",
	"S2C_ActionEffect32": "0x02fd",
	"S2C_ActorCast": "0x0166",
	"S2C_ActorControl": "0x00e4",
	"S2C_ActorControlSelf": "0x0125",
	"Server_IpRange": "109.244.0.0/16, 27.221.0.0/16, 119.97.0.0/16, 162.14.0.0/16",
	"Server_PortRange": "1-65535"
}

I think the ActorCast and ActorControl should be like these?

**Comment by NukoOoOoOoO** [comment]
> I think the ActorCast and ActorControl should be like these?

@RavenYDY No, I got these two opcodes from the game binary, and both assembly look the same like 6.15

**Comment by jaquearon** [comment]
opcode not working :/

**Comment by parasolW** [comment]
CN 6.2 opcode not working for me too..

**Comment by NukoOoOoOoO** [comment]
should be fixed ig

**Comment by Yoruichiii** [comment]
{
	"C2S_ActionRequest": "0x0363",
	"C2S_ActionRequestGroundTargeted": "0x0363",
	"S2C_ActionEffect01": "0x030f",
	"S2C_ActionEffect08": "0x0199",
	"S2C_ActionEffect16": "0x01e2",
	"S2C_ActionEffect24": "0x03b6",
	"S2C_ActionEffect32": "0x037e",
	"S2C_ActorCast": "0x0186",
	"S2C_ActorControl": "0x0365",
	"S2C_ActorControlSelf": "0x0245",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

maybe it‘s right ？

**Comment by NukoOoOoOoO** [comment]
> maybe it's right?

@Yoruichiii No, your ``C2S_ActionRequestGroundTargeted`` is wrong, it is used in actions like White Mage's Asylum or Ninja's 　Shukuchi

**Comment by RavenYDY** [comment]
game.CN.2023.01.25.0000.0000
{
	"C2S_ActionRequest": "0x0212",
	"C2S_ActionRequestGroundTargeted": "0x0353",
	"S2C_ActionEffect01": "0x02e7",
	"S2C_ActionEffect08": "0x00ef",
	"S2C_ActionEffect16": "0x036f",
	"S2C_ActionEffect24": "0x03c4",
	"S2C_ActionEffect32": "0x02e6",
	"S2C_ActorCast": "0x033b",
	"S2C_ActorControl": "0x0249",
	"S2C_ActorControlSelf": "0x0397",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

**Comment by BIGNIII** [comment]
Could someone tell me how to use opcode？
