### ISSUE TITLE
Anyone knows CN 6.20 OPCode?

### ISSUE THREAD

**Issue by parasolW** [Soreepeong/XivAlexander#537]

**Comment by Gffate** [comment]
{
	"C2S_ActionRequest": "0x363",
	"C2S_ActionRequestGroundTargeted": "0x3E1",
	"S2C_ActionEffect01": "0x2AD",
	"S2C_ActionEffect08": "0x199",
	"S2C_ActionEffect16": "0x1E2",
	"S2C_ActionEffect24": "0x3B6",
	"S2C_ActionEffect32": "0x37E",
	"S2C_ActorCast": "0x186",
	"S2C_ActorControl": "0x365",
	"S2C_ActorControlSelf": "0x245",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}
