### ISSUE TITLE
Optimal settings?

### ISSUE THREAD

**Issue by defineonly** [Soreepeong/XivAlexander#54]
A few questions about being able to use this more optimally.

1) I play around 73ms on average when pinging the server directly without a VPN. Do you normally disable "Use Delay Detection" when you have a certain amount of ping? Would it benefit me more to disable this option at the current 73ms I play at? 
2) Would this tool work better combined with a VPN solution? If I use a VPN, I normally get anywhere from 60-65ms. Would I still need to turn off the "Use Delay Detection" option when having a VPN enabled?

Thank you

**Comment by Soreepeong** [comment]
1. You'll have to check for yourself, as people are getting different results. It's usually better on if your ping is low, and better off if your ping is high.
2. If you use VPN that will fake ping (try pinging neolobby01.ffxiv.com, and see if you get 1ms or <1ms), then you will have to turn off "Use Delay Detection".

**Comment by Harxen** [comment]
@Soreepeong What is considered high? 100ms? 200 ms? 300+ ms?

**Comment by Soreepeong** [comment]
Well it didn't work well enough for me when I was trying 280ms, but on 140ms it looks like it's fine.
