### ISSUE TITLE
xivAlex and Gshade can no longer run together

### ISSUE THREAD

**Issue by acex401** [Soreepeong/XivAlexander#542]
After the latest major update for GShade I believe it broke the hook allowing GShade and XIV Alex to run together. 
![Gshade_Alex_Error](https://user-images.githubusercontent.com/121890316/210408881-fb937d14-9305-4379-85e3-1d9ae74e47fe.PNG)

**Comment by Oglaf** [comment]
Uninstall everything, clear any residual folders and files, **that's important**!. Install FFXIV, install Gshade, then install XivAlexander selecting "**Install XivAlenxander as dinput8.dll for DirectX 11 version**"

**Comment by acex401** [comment]
That worked thank you so much!
