### ISSUE TITLE
Getting this error message when I press load once.

### ISSUE THREAD

**Issue by Baconbrotherhood** [Soreepeong/XivAlexander#546]
![image](https://user-images.githubusercontent.com/30527120/211592460-9b4080a0-f7f8-4c9b-88bb-f89945c5180c.png)

I don't know what 6.3 changed, but before when I tried to do load once it would work. Now it gives this error, not sure what any of it means but if you need any info about things I'll give it. I am really clueless when it comes to this though so just give me the list of what you need and I'll get it to you one way or another.

**Comment by rhirama** [comment]
yeah, we'll pretty much have to wait for an update. #544 had the same issue

**Comment by Baconbrotherhood** [comment]
dang that sucks :c hopefully it isnt too long. once you go xivalexander you can never go back, especially if you cant double weave without T_T

**Comment by ShiniXXIV** [comment]
Oh thank god. I thought it was just me having this issue T.T I just decided to log in after my holiday and got this error. Never had issues with xivAlexander before so I was so confused lol
