### ISSUE TITLE
No longer working after patch 5.5

### ISSUE THREAD

**Issue by voetre** [Soreepeong/XivAlexander#55]
Hey There,

This is probably expected with the new patch but I thought I'd post anyway, XIVAlexander is no longer working after the patch! I'm assuming you are still working on updating?

If its supposed to be working already, could you let me know what I should troubleshoot? 

Thanks!

**Comment by Soreepeong** [comment]
Try downloading it again (contains updated configuration), or follow the instructions written on readme.

**Comment by voetre** [comment]
Oh, apologies, I did not see that section of the readme had been updated with the new opcodes!

Thank you for you work on this!
