### ISSUE TITLE
[6.3] Possible Memory Leak

### ISSUE THREAD

**Issue by Stateford** [Soreepeong/XivAlexander#553]
I was getting memory leaks on 6.3 constantly. I uninstalled XIVAlex and deleted the DLL from the directory and it's stopped. Can someone investigate?

**Comment by thiamaster** [comment]
According to Square Enix, memory leak is an issue since 6.3. So its not related to third party tools.

**Comment by Pox4ever** [comment]
> I was getting memory leaks on 6.3 constantly. I uninstalled XIVAlex and deleted the DLL from the directory and it's stopped. Can someone investigate?

Unrelated to XIVAlexander. Check latest FFXIV patch.
