### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#56]
![1](https://user-images.githubusercontent.com/82459386/115011924-28dc6380-9eea-11eb-95b0-a2b65dfcf35f.JPG)

Just use the default settings and the given configurations?

For instance,
    "ActorCast": "0x012c",
     "ActorControl": "0x017a",
     "ActorControlSelf": "0x007c",
     "AddStatusEffect": "0x0204",
     "RequestUseAction": "0x02b3",
     "RequestUseAction2": "0x0250",
     "SkillResultResponse01": "0x02d0",
     "SkillResultResponse08": "0x0199",
     "SkillResultResponse16": "0x02d1",
     "SkillResultResponse24": "0x01a4",
     "SkillResultResponse32": "0x016e"

for Korean server.

**Comment by justin767** [comment]
please help :(

**Comment by Harxen** [comment]
Yes as long as you use the default settings you are fine

**Comment by Soreepeong** [comment]
Yes, as long as you didn't change game installation path, you can just use the defaults.
