### ISSUE TITLE
Game Fix menu unpopulated

### ISSUE THREAD

**Issue by pulsemod** [Soreepeong/XivAlexander#565]
thank you for porting the game fix to XivAlexander.
when running the game client 2023.01.17 JP with XivAlexander 1.14.8.56, the Game Fix menu remains unpopulated with (None available). the same happens whether XivAlexander is loaded once manually, or loaded via d3d proxy.
of course, the menu should be populated with the game fix so it can be applied.

thanks for your work on XivAlexander!

**Comment by Soreepeong** [comment]
Can you run "Check for opcode updates", and if it doesn't change anything, then can you see if you do see non-empty "PatchCode" section in opcode editor window?

**Comment by retaker** [comment]
![UL1E_6GCOKZ44PA)81X8{21](https://user-images.githubusercontent.com/3334662/215428420-399da00b-615a-4225-b299-e9a534e745f6.png)
Latest opcodes in .56 version is like this

**Comment by retaker** [comment]
![JGT_POZUL2VF(@`2@EH3SKE](https://user-images.githubusercontent.com/3334662/215429057-336d043d-261f-4f51-891e-9271258be12c.png)
Here's the screen shot of the gamefix option in configure menu.

**Comment by Soreepeong** [comment]
Is there anything printed about it on startup in log? I can't think of any reason why wouldn't this be working at the moment.

**Comment by Azalea224** [comment]
[XivAlexander_20230130_194443_808.log](https://github.com/Soreepeong/XivAlexander/files/10537997/XivAlexander_20230130_194443_808.log)


> Is there anything printed about it on startup in log? I can't think of any reason why wouldn't this be working at the moment.
no idea where it would be in this log but here's a startup log, have the same issue as above people.

**Comment by detectiveMaru** [comment]
Same issue, also on JP. Might've something to do with client/server region?

**Comment by javix91** [comment]
I have the same problem with the gamefix option . Aparently the log says that the opcode can not be updated cause it was emited by an untrusted entity.

Thanks for your job !!


![312312](https://user-images.githubusercontent.com/124056367/215771243-60471da0-5228-4cfe-9d29-a6f20b86dc33.PNG)

**Comment by Soreepeong** [comment]
It should be fixed in this release. https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.8.57
