### ISSUE TITLE
error missing dll

### ISSUE THREAD

**Issue by ajerul** [Soreepeong/XivAlexander#57]
i tried running the program and an error message popped out
api-ms-win-shcore-scaling-l1-1-1.dll missing

**Comment by Soreepeong** [comment]
What operating system are you using? This program is only tested in latest version of Windows 10, so if it doesn't work on previous version, then I will have to make sone changes.

**Comment by ajerul** [comment]
im using win 7

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivAlexander/blob/0b0d5b6880a3c2a3451891d64bc975582ca7f87a/XivAlexander/App_Window_Base.cpp#L82

Use `GetDeviceCaps(..., LOGPIXELSX or LOGPIXELSY)` instead if [`GetDpiForMonitor` (Windows 8.1+)](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getdpiformonitor) is unavailable.

**Comment by Soreepeong** [comment]
Try again with the latest release.

**Comment by vrangou** [comment]
Hi,
The previous error was solved, but a new one immediately fires:

The procedure entry point GetSystemTimePreciseAsFileTime could not be located in the dynamic link library KERNEL32.dll.
![error](https://user-images.githubusercontent.com/85325978/120737081-d0761b00-c4c3-11eb-8281-989c265c7ce5.png)

Thanks for trying to support older systems, good luck!
