### ISSUE TITLE
CN 6.2 (01/30 update) Opcodes

### ISSUE THREAD

**Issue by EaladSkaan** [Soreepeong/XivAlexander#570]
{
	"C2S_ActionRequest": "0x0212",
	"C2S_ActionRequestGroundTargeted": "0x0353",
	"S2C_ActionEffect01": "0x02e7",
	"S2C_ActionEffect08": "0x00ef",
	"S2C_ActionEffect16": "0x036f",
	"S2C_ActionEffect24": "0x03c4",
	"S2C_ActionEffect32": "0x02e6",
	"S2C_ActorCast": "0x033b",
	"S2C_ActorControl": "0x0249",
	"S2C_ActorControlSelf": "0x0397",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

**Comment by Friela** [comment]
Thank you so much!!!!

**Comment by sAmyAox** [comment]
英雄！

**Comment by yLk0** [comment]
Im using the NA version, how do i know if is updated?

**Comment by EaladSkaan** [comment]
> Im using the NA version, how do i know if is updated?

if your game updated then XivAlex must update too

**Comment by JhyukiSena** [comment]
Thank you!

**Comment by BIGNIII** [comment]
Could someone tell me how to use opcode？

**Comment by Sunset-Rl** [comment]
After I change the opcode, it still does not seem to work for CN.
But when I play on the Japanese server, it works...

**Comment by Nonouaa** [comment]
Thanks a lot

**Comment by retaker** [comment]
> After I change the opcode, it still does not seem to work for CN. But when I play on the Japanese server, it works...

The latest xivalex version may not compatiable with CN server now. Please use .54 version and try again.

**Comment by Nonouaa** [comment]
Does any else plugin like alexander can work for CN XIV?
Noclippy has been updated 7days ago and it seems not suitable for 6.2 Version.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Sunset-Rl** [comment]
> > After I change the opcode, it still does not seem to work for CN. But when I play on the Japanese server, it works...
> 
> The latest xivalex version may not compatiable with CN server now. Please use .54 version and try again.

I have tried it, but it still did not work.

> > After I change the opcode, it still does not seem to work for CN. But when I play on the Japanese server, it works...
> 
> The latest xivalex version may not compatiable with CN server now. Please use .54 version and try again.

I tried it, but it still did not work...

**Comment by Sunset-Rl** [comment]
> > After I change the opcode, it still does not seem to work for CN. But when I play on the Japanese server, it works...
> 
> The latest xivalex version may not compatiable with CN server now. Please use .54 version and try again.

I tried it, but it sitll did not work...

**Comment by Nonouaa** [comment]
Nocliply is useful

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
