### ISSUE TITLE
Is possible to low the ping that is emulated?

### ISSUE THREAD

**Issue by yLk0** [Soreepeong/XivAlexander#571]
Im playing ninja and saw a comment saying that a good ping would be at least 40 and the tool emulated 75. So is possbible to get lower? If so, how do i do?

Sry for any english mistake.

**Comment by retaker** [comment]
You may try different modes provided in the Network menu as picture below
![image](https://user-images.githubusercontent.com/3334662/216759575-af20c440-8de7-46c2-998d-88b8270d4579.png)

You can choose the one which makes you feel best, just try mode 1 and mode 3.
All versions of xivalex you are able to get from the release of this repo will not emulate the ping lower than 75, but all 3 modes provided now can offer a clean double weave for all jobs.

You may re-open this issue if you have any further questions and it will be closed by now. 
If you are a Chinese speaker, you may write email to i@retaker.me to get some limited Chinese support.
