### ISSUE TITLE
Global 6.31 Hotfix (02/09 update) Opcodes

### ISSUE THREAD

**Issue by Questia-Ch** [Soreepeong/XivAlexander#578]
{
	"C2S_ActionRequest": "0x0133",
	"C2S_ActionRequestGroundTargeted": "0x0252",
	"S2C_ActionEffect01": "0x0100",
	"S2C_ActionEffect08": "0x02b9",
	"S2C_ActionEffect16": "0x0390",
	"S2C_ActionEffect24": "0x022a",
	"S2C_ActionEffect32": "0x0120",
	"S2C_ActorCast": "0x0185",
	"S2C_ActorControl": "0x01a4",
	"S2C_ActorControlSelf": "0x0203",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

**Comment by salmondev** [comment]
Tested and working 👍 Thank you very much! ❤

**Comment by Jacksonchuchu2001** [comment]
Hi how do i apply opcode?
I am really new to this please give me detail steps!
Thank you!!!!!!

**Comment by Questia-Ch** [comment]
> Hi how do i apply opcode? I am really new to this please give me detail steps! Thank you!!!!!! And when i reinstall xivalexander will the opcode apply automatically?

You don't really need to worry about this as a regular user, as XIVAlexander updates opcodes automatically if they're available. If you're unsure, you can always do a manual update (see image), but if the option below that is ticked that shouldn't be a problem.
![image](https://user-images.githubusercontent.com/124882235/218248668-6679bba4-ff10-404e-b357-a0a502e9fd6f.png)

If you see "Your current opcode file is up to date", then there's no further action required.

Every FFXIV update (patch or hotfix) may make the opcodes invalid; new opcodes usually are made available within the day.
If you want to help out as I did here, [use this guide.](https://github.com/Soreepeong/XivAlexander/wiki/How-to-find-opcodes)

Issue closed; opcodes work and are part of the February 2, 2023 opcode update.
