### ISSUE TITLE
OodleNetwork error

### ISSUE THREAD

**Issue by Diasmorten** [Soreepeong/XivAlexander#596]
![Untitled](https://user-images.githubusercontent.com/127700645/224581336-57473757-431f-43a3-abd6-7a317e5edc33.png)
This release appears to have stopped Alexander functioning with my game and it appears to me that the addition of 
`"Common_UseOodleTcp": true` and whatever may be connected to this command is the problem. Changing the command to `false` does not change the outcome and neither does deleting the line.

I'm currently using the JP version of the game.

I don't use Oodle and don't have access to it, so what do I do?

**Comment by amasover** [comment]
Possible dupe of #586? Make sure you update/reinstall XivAlexander. If you are playing on JP servers, I would imagine that you would want `"Common_UseOodleTcp": true`

More details:
FFXIV uses Oodle for packet compression. It's not something that you would install, it is a library that ships with the game (and is used by the game servers). In the last patch, SE once again changed the compression scheme from stateless to stateful compression (the poorly named OodleTCP) possibly with the goal of achieving a higher compression ratio at the cost of increased CPU/memory usage probably on both server/client.

**Comment by Diasmorten** [comment]
> Possible dupe of #586? Make sure you update/reinstall XivAlexander. If you are playing on JP servers, I would imagine that you would want `"Common_UseOodleTcp": true`
> 
> More details: FFXIV uses Oodle for packet compression. It's not something that you would install, it is a library that ships with the game (and is used by the game servers). In the last patch, SE once again changed the compression scheme from stateless to stateful compression (the poorly named OodleTCP) possibly with the goal of achieving a higher compression ratio at the cost of increased CPU/memory usage probably on both server/client.

Install and re-install worked fine so I suppose I jumped the gun and got lazy, which also explains how I missed #586 since I simply typed "Oodle" into the search bar, and of course the search won't search for just parts of words.

Big thanks for the work and apologies for the inconvenience.

**Comment by amasover** [comment]
Thanks to Soreepeong I'm just a random user :)
