### ISSUE TITLE
Program does not work with XIVLauncher

### ISSUE THREAD

**Issue by Poyokorin** [Soreepeong/XivAlexander#6]
XIVLauncher interferes with the program. The prompt initially comes up on the first run to allow the program to inject the dll to the game, but nothing happens after the prompt. The program doesn't appear in the system tray whatsoever. Running the program again after this fact blurts out that the game's exe cannot be found. It works just fine using the official game launcher.

If it helps, the only plugins I have on XIVLauncher are MOAction, Simple Tweaks and XIVCombo.

**Comment by Soreepeong** [comment]
It works for me with XivLauncher+Dalamud, so I'm not sure what's going on, but I just updated to show a control window in case tray icon doesn't show up, and loader will now show up an error with an error code if it failed to load for whatever reason. Can you see if it shows up any window or error message now?

**Comment by randompersom** [comment]
Using the latest release (v 1.06), the exact same problem outlined above still happens to me with XIVLauncher. The plugin does not launch, and nothing appears in the system tray. The plugin works fine with the official launcher. Additionally, after I try using XIVAlexander while in game using XIVLauncher, my game crashes and I get this error from XIVAlexander:

![image](https://user-images.githubusercontent.com/78991050/107838132-6d287780-6d72-11eb-98a1-09125a58d934.png)

I noticed this is the same error I get when I try to run XIVAlexander not as administrator with the official launcher.

The plugins I use for XIVLauncher are:
Accurate Countdown, Browser Host, Chat Bubbles, Damage Info Plugin, Market Board, NoSoliciting, Orchestrion, Peeping Tom, Penny Pincher, Pixel Perfect, SlideCast, and Waymark Preset.

**Comment by Soreepeong** [comment]
Try the following:
1. Run FFXIV via official launcher.
2. Run `%APPDATA%\XIVLauncher\addon\Hooks\<something>\Dalamud.Injector.exe` as Administrator.
3. Run XivAlexander as Administrator.

And try again but in the order of 1, 3, and then 2.

I'll check out plugin compatibility later on today.

**Comment by randompersom** [comment]
First doing steps 1 to 3 everything went fine.
Then trying again doing steps 1, then 3, then 2, after step 2 (the last step in this order) I got this error:

![image](https://user-images.githubusercontent.com/78991050/107839105-a44d5780-6d77-11eb-9189-bcfa5bd35af5.png)

Afterwards I tried launching the game through XIVLauncher, then tried loading XIVAlexander (as admin), and the same problem occured (although this time i did notice XIVAlexander flash for a moment on my system tray then disappear, this may have happened the previous times as well but i just didnt catch it, not sure). Shortly after running Alexander as admin my game crashed and I got this error:

![image](https://user-images.githubusercontent.com/78991050/107839166-0017e080-6d78-11eb-9fe1-d675cd600796.png)

**Comment by LittleNightmare** [comment]
@randompersom I haven't met this inject problem yet. But I am not using Accurate Countdown, Browser Host, Orchestrion, and Peeping Tom

@Soreepeong my game just crash when I use alexander with dalamud together.  I think I find the problem - [PingPlugin](https://github.com/karashiiro/PingPlugin). The crash happened when I switch the window to another program, so I disable PingPlugin on my first try. Now, it working fun.

**Comment by Soreepeong** [comment]
I've tried installing all plugins aforementioned, unloading and loading XivAlexander multiple times after loading Dalamud, and tried different orders of executing stuff, and I can't get it to cause problems, except when the execution order is:

> XIV -> XivAlexander -> Dalamud.Injector -> Unload XivAlexander

which will effectively disable all inputs to Dalamud plugins. Maybe something else running on your PC globally hooking programs is incompatible with this? It would help finding out errors if you can tell me the list of running processes on your PC, and whether you're running other addons than Dalamud too (like Reshade).

For some reason I don't know, tray icon would randomly disappear, so I made that the program will re-register tray icon every 5 seconds. XivAlexanderLoader would display ffxiv_dx11 isn't found when the loader detects that DLL is already loaded.
See if you have `"ShowControlWindow": true` in your configuration JSON file, which should display a window when XivAlexander is loaded, which should help when tray icon doesn't stay.

Also, try this release: https://github.com/Soreepeong/XivAlexander/releases/tag/v1.07
This will show a message like the following, which might help you when tray icon randomly disappears.
![image](https://user-images.githubusercontent.com/3614868/107849775-db3b7000-6e40-11eb-93ce-cb12ea1d630f.png)

**Comment by randompersom** [comment]
Just tested the most recent release (v 1.07), and whatever was changed in this version seemed to have fixed my problem. I will keep you posted if I run into any additional errors in the future. Thanks for your work!
