### ISSUE TITLE
How to find iglnoredCells info for ExcelTransformConfig files?

### ISSUE THREAD

**Issue by godhandMidu** [Soreepeong/XivAlexander#621]
Hi, I'm playing Endwalker.

I find that [say] quests in Endwalker are doesn't working when using language mod.

I guess that [say] quests before Endwalker are handled as exception in 'ignoredCells' section in 'ExcelTransformConfig' json files.

![image](https://github.com/Soreepeong/XivAlexander/assets/120312362/adba3cc5-f3bc-47dd-8969-a63331b17dd3)

Is there way to find the information in red box above picture?

If my guess is wrong, please let me know how to proceed [say] quests in Endwalker with language mod.

**Comment by vivelaviet** [comment]
I have the same issue, and thought I was going crazy.
It's really inconvenient but I unloaded and relaunched :/

**Comment by LightSeaGreen** [comment]
You can use a file explorer tool like FFXIV Explorer to find the quest.

![image](https://github.com/Soreepeong/XivAlexander/assets/39581622/bd7bc435-2ae6-47ea-ba25-7cd521a9be7d)

Would be very helpful if anyone can make a list of quests that require you to say something.

**Comment by godhandMidu** [comment]
> You can use a file explorer tool like FFXIV Explorer to find the quest.
> 
> ![image](https://user-images.githubusercontent.com/39581622/244812295-bd7bc435-2ae6-47ea-ba25-7cd521a9be7d.png)
> 
> From a bit of looking around, adding
> 
> ```
> {"name":` "quest/046/banomi102_04608", "id": 68, "column": 1, "forceLanguage": "English"}
> ```
> 
> Allows me to do the quest [Coffee Talk](https://ffxiv.consolegameswiki.com/wiki/Coffee_Talk) with the key phrase in English.
> 
> Would be very helpful if someone can make a list of quests that require you to say something.

Thank you!!
I'll test it later to see if it's applicable to language mod.

**Comment by seni-pie** [comment]
hi! is there still no workaround for this? i find that i can't do certain quests in dawntrail because of this :(

**Comment by godhandMidu** [comment]
> hi! is there still no workaround for this? i find that i can't do certain quests in dawntrail because of this :(

Hi!

To resolve this, you need to use 'FFXIV Data Explorer' program above.

And follow the steps below.

1. Open '\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\sqpack\ffxiv\0a0000.win32.index' in the program.

2. Find .exh file which has the 'say quest' you encountered. It's helpful to search using the dialogue of that quest.

3. Check column 0 and column 1. If column 0 contains 'SAYTODO' and column 1 is the correct line you need to type in the game, you found it right.

4. Make exception info.
name = file path (ex. quest/044/aktkme107_04425)
id = index
column = column number
forceLanguage = Language to type in the game
![adfasdf](https://github.com/user-attachments/assets/6d70da0f-586c-4515-b677-85541d478834)
![adfadsf](https://github.com/user-attachments/assets/788ece2a-7522-4ac6-8373-799585c0e4c2)

5. Add this info in 'ignoredCells' in the .json file which you use.

Thats all. When new version of XivAlexander comes out, you should add exception info again.

If you have problem, please comment. I hope it would be helpful.
