### ISSUE TITLE
4/27 Update causing a break?

### ISSUE THREAD

**Issue by Evangel0201** [Soreepeong/XivAlexander#63]
Hello, today (4/27/2021) FFXIV had extended maintenance and a small update for hotfixes. I launched Alexander having it worked the previous evening and instantly noticed it wasn't working correctly. I did a quick reinstall of the application to see if it was that and it still stopped working. Checking in with one of my friends who also uses it, they reported 0 issues after the update. I am wondering if it's common for such a small hotfix to break the program, if it's on my side, or it's a more general issue? Nothing had to be changed for them including OPCODES so I'm opening this to report this issue incase anyone else has had this problem. Also looking for answers so I can try to fix this, thanks again.

**Comment by Soreepeong** [comment]
Well, they did change opcodes. If ``ffxiv_dx11.exe`` gets changed, you may assume that ACT FFXIV plugin and this to break. It's updated now! https://github.com/Soreepeong/XivAlexander/releases
