### ISSUE TITLE
xivalexander not working after hotfix

### ISSUE THREAD

**Issue by BahamutBlast** [Soreepeong/XivAlexander#64]
I booted up the game after the patch today and I tried running XIVAlexander, but it wasn't doing anything like it did before the patch. It opened up just fine but it just isn't doing anything, so I wanted to ask if anyone else has been having this issue/knows how to fix this issue.

**Comment by VXLSS** [comment]
Follow the first time setup instructions on the main github page.

Basically change the opcode values in XivAlexander.dll.json with a text editor.


{
    "ActorCast": "0x02ad",
    "ActorControl": "0x02db",
    "ActorControlSelf": "0x023e",
    "AddStatusEffect": "0x0334",
    "RequestUseAction": "0x00d0",
    "RequestUseAction2": "0x0094",
    "SkillResultResponse01": "0x03e7",
    "SkillResultResponse08": "0x020a",
    "SkillResultResponse16": "0x01f9",
    "SkillResultResponse24": "0x01eb",
    "SkillResultResponse32": "0x013e"
}

**Comment by Soreepeong** [comment]
It's applied now. https://github.com/Soreepeong/XivAlexander/releases

**Comment by BahamutBlast** [comment]
Ty!
