### ISSUE TITLE
6.5 Opcodes

### ISSUE THREAD

**Issue by F1reman2** [Soreepeong/XivAlexander#656]
Anyone got the 6.5 Opcodes?

**Comment by TermT26** [comment]
90% Sure that it's this

{
	"C2S_ActionRequest": "0x03b6",
	"C2S_ActionRequestGroundTargeted": "0x032d",
	"Common_UseOodleTcp": true,
	"PatchCode": [],
	"S2C_ActionEffect01": "0x0222",
	"S2C_ActionEffect08": "0x0316",
	"S2C_ActionEffect16": "0x0192",
	"S2C_ActionEffect24": "0x023b",
	"S2C_ActionEffect32": "0x03d2",
	"S2C_ActorCast": "0x0396",
	"S2C_ActorControl": "0x0243",
	"S2C_ActorControlSelf": "0x0196",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

**Comment by F1reman2** [comment]
Ty!

**Comment by juntuck** [comment]
This works for me!
