### ISSUE TITLE
SC2_Raw Error Patch 6.5

### ISSUE THREAD

**Issue by Juandibp** [Soreepeong/XivAlexander#659]
Hi there, I have been trying to debug this issue a friend is having. I have failed so far, had them check for opcodes, its up to date and redownloading the newest version of Alexander.

```
2023-10-04 10:04:22.284	SocketHook	C2S_Raw: Error: Could not parse game message (sum(message.length for each message) > total message length)
[2023-10-04 10:04:22.283] Length=75 ConnType=0 Count=2 CompressionType=2
```

Any help would be highly appreciated

**Comment by Juandibp** [comment]
Doing a full reinstall of alex worked

**Comment by Squall-Leonhart** [comment]
A full reinstall is not what fixed your problem,  logging out of the game and back in while XIV Alexander is running is - its the same issue that FFXIV Plugin for ACT has when *not* using Deucalion injection
