### ISSUE TITLE
XIVAlex not opening with FFXIV. Anyone having the same issue?

### ISSUE THREAD

**Issue by Spanglish1337** [Soreepeong/XivAlexander#660]
Whenever I open FFXIV, XIVAlex won't open either. It is currently installed. I already uninstalled and installed again but still no workaround. 

Anyone else with the same issue? Or if anyone knows how to fix it, please let me know here, I can't figure it out. Thank you.

**Comment by RF4416** [comment]
I'm having the same issue as well - XIVAlexander loading at all with my game.

**Comment by Jacksonchuchu2001** [comment]
same here

**Comment by shimakazevr** [comment]
also having the same issue launching the game with xivquicklauncher. xivalexander seems to not load with the game but can be injected post game launch using the run once

**Comment by Spanglish1337** [comment]
Okay guys after a lot of testing it turned out that XIV was opening but not showing in taskbar, I mentioned it in #663, closing this for now.
