### ISSUE TITLE
6.51 Opcodes

### ISSUE THREAD

**Issue by zeroxetc** [Soreepeong/XivAlexander#666]
Anyone got the 6.51 opcodes? Thank you!

**Comment by zeroxetc** [comment]
I tried it but it didnt work. I should learn how to configure it manually anyways haha

**Comment by phanlongtran** [comment]
1. Open the main interface
![image](https://github.com/Soreepeong/XivAlexander/assets/44751829/4d9a3bf0-3c4b-41c2-954a-3a3ae9d399ac)

2. Post in and save
![image](https://github.com/Soreepeong/XivAlexander/assets/44751829/5c39e727-4761-4c87-b40b-aa15da5f4265)

Note: Remember to turn this on
![image](https://github.com/Soreepeong/XivAlexander/assets/44751829/69c3f102-3d48-4245-a654-77372631f177)

**Comment by juntuck** [comment]
> I will stop being lazy this time, get it guys. Tested on Sam pretty good so far, idk about the iprange for china or korea so you might have to add it yourself if it's none of the below.
> 
> > {
> > "C2S_ActionRequest": "0x0260",
> > "C2S_ActionRequestGroundTargeted": "0x0260",
> > "Common_UseOodleTcp": true,
> > "PatchCode": [],
> > "S2C_ActionEffect01": "0x00c0",
> > "S2C_ActionEffect08": "0x01d6",
> > "S2C_ActionEffect16": "0x025d",
> > "S2C_ActionEffect24": "0x00d9",
> > "S2C_ActionEffect32": "0x01a3",
> > "S2C_ActorCast": "0x02d2",
> > "S2C_ActorControl": "0x0342",
> > "S2C_ActorControlSelf": "0x00e4",
> > "Server_IpRange": "124.150.157.0/24, 153.254.80.0/24, 202.67.52.0/24, 204.2.29.0/24, 80.239.145.0/24",
> > "Server_PortRange": "1-65535"
> > }

This works for me, thank you so much!

**Comment by Sumimason** [comment]
I have "C2S_ActionRequestGroundTargeted": "0x014f" but the rest are the same

**Comment by phanlongtran** [comment]
@Sumimason Can you post the log you get this from?

**Comment by Sumimason** [comment]
[XivAlexander_20231101_032952_783.log](https://github.com/Soreepeong/XivAlexander/files/13219222/XivAlexander_20231101_032952_783.log)
i only saved this scuffed one but it should have the log for shukuchi

**Comment by ultraobama** [comment]
Dumb question. How do I open Alexander main interface?

**Comment by phanlongtran** [comment]
@ultraobama
You might have it hidden, go do this and restart the game.
[Link](https://github.com/Soreepeong/XivAlexander/issues/663)
