### ISSUE TITLE
6.51 hotfix (11/14 update) opcode

### ISSUE THREAD

**Issue by Flaaaan** [Soreepeong/XivAlexander#670]
{
	"C2S_ActionRequest": "0x03ab",
	"C2S_ActionRequestGroundTargeted": "0x02a2",
	"Common_UseOodleTcp": true,
	"PatchCode": [],
	"S2C_ActionEffect01": "0x019f",
	"S2C_ActionEffect08": "0x03a2",
	"S2C_ActionEffect16": "0x0126",
	"S2C_ActionEffect24": "0x0087",
	"S2C_ActionEffect32": "0x0248",
	"S2C_ActorCast": "0x0107",
	"S2C_ActorControl": "0x03b6",
	"S2C_ActorControlSelf": "0x00e2",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}

**Comment by phanlongtran** [comment]
Legit can vouch for

**Comment by xefe** [comment]
I can confirm it too.

**Comment by gladosone** [comment]
It's impressive how quickly ppl can provide the opcode after new patch comes in. TY so much <3

**Comment by Spanglish1337** [comment]
Thanks! And here I thought that for some reason XIV did it automatically haha
