### ISSUE TITLE
Detectability

### ISSUE THREAD

**Issue by Candixe** [Soreepeong/XivAlexander#69]
Is it possible for the plugin to be detected by the game client, even if I follow the instructions presented at the end of the "how it works" tab?

**Comment by Soreepeong** [comment]
The game client makes no effort whatsoever to "detect" anything is going on. It can be detected from server side though, as it's possible to measure ping between the server and you, and judge whether you should be able to double weave from ping. But that's pretty much an asshole move, so it should be just fine.

**Comment by Candixe** [comment]
Thank you!
