### ISSUE TITLE
Please fix this

### ISSUE THREAD

**Issue by emmyie** [Soreepeong/XivAlexander#693]
Please do not code in C++ if you lack the capabilities of writing C++ the way any normal human being does, you are clearly way more comfortable with C# and Java because your code looks that way and nothing makes sense

**Comment by retaker** [comment]
If you feel like you can do better, you are welcomed to fork the project and make your own version. Or you can make your refactor and submit a pull request.
This is how the open source works, wish you are intelligent enough to understand.

**Comment by emmyie** [comment]
if only you had setup the project properly so i could actually build it i would love to rework the entire thing in like 1 billion less lines of code but unfortunately you suffer from pasting and your project is not set up in a way that makes it buildable
