### ISSUE TITLE
Icon missing in system tray on taskbar in WINDOWS 11

### ISSUE THREAD

**Issue by GreatGBL** [Soreepeong/XivAlexander#695]
Icon missing in system tray on taskbar in WINDOWS 11
need the icon to update opcode and log funciton

**Comment by retaker** [comment]
Hi GBL,
Please check your settings page as this picture shows and enable it for xivalex
![image](https://github.com/Soreepeong/XivAlexander/assets/3334662/db79c955-bf1f-42a1-897c-d8494b0ee1c1)
It is also possilbe that XIVAlex is currently not working for CN client. The other solution to show the window is editing this file:
`%APPDATA%\XivAlexander\config.runtime.json`
and make this chage:
`"ShowControlWindow": true`

**Comment by tuongminh465** [comment]
I have the same issue. I have tried looking at Taskbar settings but I do not see XIVAlex icon there.

I have also tried to edit the `config.runtime.json` file as @retaker suggested but it doesnt work either.

**Comment by tuongminh465** [comment]
Nvm it works now I just have to uninstall then reinstall it. Thanks all

**Comment by retaker** [comment]
efb88c2f8caeb9e639fd89ad992d77dbf4d84883 fixed this issue
