### ISSUE TITLE
7.0 Opcodes

### ISSUE THREAD

**Issue by F1reman2** [Soreepeong/XivAlexander#715]
Dawntrail time!
Anyone got?

**Comment by Choojermelon** [comment]
Did you get them, since you closed the issue?

**Comment by F1reman2** [comment]
{
	"C2S_ActionRequest": "0x0345",
	"C2S_ActionRequestGroundTargeted": "0x01d5",
	"Common_UseOodleTcp": true,
	"PatchCode": [
		{
			"HmacKey": "2beVpoUaxEOiqvWxsnSYfq5PkDkTLLo2qjXLqg7E6Gg=",
			"Name": "anti odin cape physics disabling",
			"x64": [
				[
					"find",
					"code",
					"0",
					"66 83 bb ?? ?? ?? ?? 64 75 ?? 80 bb ?? ?? ?? ?? 02 75 ?? 48"
				],
				[
					"offset",
					"10"
				],
				[
					"write",
					"0xc6 0x83"
				],
				[
					"offset",
					"4"
				],
				[
					"write",
					"0x01 0x74"
				],
				[
					"find",
					"code",
					"0",
					"66 83 bb ?? ?? ?? ?? 64 75 ?? 80 bb ?? ?? ?? ?? 02 75 ?? 48"
				],
				[
					"offset",
					"10"
				],
				[
					"write",
					"0xc6 0x83"
				],
				[
					"offset",
					"4"
				],
				[
					"write",
					"0x01 0x74"
				]
			],
			"x86": []
		}
	],
	"S2C_ActionEffect01": "0x0369",
	"S2C_ActionEffect08": "0x01a4",
	"S2C_ActionEffect16": "0x01fd",
	"S2C_ActionEffect24": "0x02f9",
	"S2C_ActionEffect32": "0x0383",
	"S2C_ActorCast": "0x00f1",
	"S2C_ActorControl": "0x0187",
	"S2C_ActorControlSelf": "0x0141",
	"Server_IpRange": "119.252.36.0/24, 119.252.37.0/24, 153.254.80.0/24, 204.2.29.0/24, 80.239.145.0/24",
	"Server_PortRange": "1025-65535"
}

**Comment by IzumiKyouka** [comment]
Are they working for you? Which server are you

**Comment by juntuck** [comment]
They work for me on Viper! Thank you!
