### ISSUE TITLE
C2S_Raw: Error: Could not parse game message (sum(message.length for each message) > total message length)

### ISSUE THREAD

**Issue by PauloCamposFilho** [Soreepeong/XivAlexander#719]
Been getting this error (multiple lines repeating) in my logs. I have the latest (Apr 14?) release. Is this related to dawntrail? I see people with 7.0 opcodes already so I assume their version is working fine?

I'm using xivalexander through the "load once" method.

**Comment by Heinzen** [comment]
You get this when you open Alexander _after_ having logged in a character. Relog into your character and it should fix itself. Remember to open Alex before being ingame with your character to make sure it works

**Comment by PauloCamposFilho** [comment]
> You get this when you open Alexander _after_ having logged in a character. Relog into your character and it should fix itself. Remember to open Alex before being ingame with your character to make sure it works

Thank you. Okay, I wasn't aware of that. I'll close this since there's nothing to fix/be done.
