### ISSUE TITLE
Not an issue but a question since I haven't a found an answer on anywhere

### ISSUE THREAD

**Issue by arennf57** [Soreepeong/XivAlexander#74]
I gave this tool a shot and works impressively well, but I'm afraid of getting banned. So how likely is it to SE to ban people for using this tool? Or it fits in that ''gray area'', like gshade or act, where everyone's going to tell you that is not permitted and you can get banned but if you never talk about it, not is going to happen? Thanks in advance

**Comment by Soreepeong** [comment]
I believe it's pretty unlikely you'd get banned for using this tool, unless you modify the program to do stuff that isn't possible even in zero ping, or you figure out a way to harass people using this program (`you're throwing if you're not using this program`). Just use common sense and you should be all right, as this program is currently undetectable (the game does not have code to detect dll injections or mods, and this program does not do something you still can't do with <1ms ping.)

**Comment by justin767** [comment]
> I believe it's pretty unlikely you'd get banned for using this tool, unless you modify the program to do stuff that isn't possible even in zero ping, or you figure out a way to harass people using this program (`you're throwing if you're not using this program`). Just use common sense and you should be all right, as this program is currently undetectable (the game does not have code to detect dll injections or mods, and this program does not do something you still can't do with <1ms ping.)

Hello, do you have any updates on KR server?
