### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by VitalKiller** [Soreepeong/XivAlexander#756]
I have recently been getting this crash when alt tabbing out and into the game or sometimes just at launch 

[XivAlexander_20241210_201144_925.log](https://github.com/user-attachments/files/18085424/XivAlexander_20241210_201144_925.log)

I have tried updating to the most recent Alexander build and the issue persists, I am wondering if it might be related to a recent windows update (KB5046633) as I have just installed it recently, I'm still on 23H2 though any help would be much appreciated.

Oh also I am using the dinput8.dll install version if that matters.

**Comment by VitalKiller** [comment]
Okay so update, it seems this happens even when alexander is set to not run so at this point I'm not sure whether or not this is actuallly an alex problem or not, either way if anyone can tell me what the log says It would be much appreciated

**Comment by RaphaelDDL** [comment]
Not sure if exact same issue but I also started getting crashes when alt tabbing, but even without too after trying to get out of that idle camera when I was afk for a bit.

![image](https://github.com/user-attachments/assets/225b889e-3e00-4e1b-be2c-176d181fa1d2)

My windows 10 is still on 22h2

**Comment by VitalKiller** [comment]
Update: so after a botched system restore that resulted in a blue screen in my attempts to fix this I ultimately ended up having to reinstall windows and so far I haven't recieved another crash so maybe my system was just screwed, will report back if it happens again after a little more testing later, RN I'm poofed.

**Comment by VitalKiller** [comment]
Okay, so after testing for a while it does indeed seem like the issue was on my end and after my reinstall the issue is gone, thanks Raph for chiming in on this but I think I can close this particular issue now.

**Comment by RaphaelDDL** [comment]
What I noticed is taht if you try alt tab while game is still booting (before it takes over fullscreen) and/or before you get to the main menu, it tends to crash on the next alt-tab, and trying the option to "restart" with dalamud/alex just becomes a crash loop.

I could only stop from crashing on start after a windows restart. That is not the first time it happens.
