### ISSUE TITLE
5.55 opcodes

### ISSUE THREAD

**Issue by owopeachy** [Soreepeong/XivAlexander#76]
Hi, while we wait for dear soreepeong to update the readme, here are the opcodes i found, seems to be working on my end 

```
	"ActorCast": "0x0228",
	"ActorControl": "0x030f",
	"ActorControlSelf": "0x0200",
	"AddStatusEffect": "0x0143",
	"RequestUseAction": "0x02cc",
	"RequestUseAction2": "0x0205",
	"SkillResultResponse01": "0x0128",
	"SkillResultResponse08": "0x0295",
	"SkillResultResponse16": "0x025e",
	"SkillResultResponse24": "0x0299",
	"SkillResultResponse32": "0x00a7",

```	

Edit: RequestUseAction was incorrect, it should be  ``` "RequestUseAction": "0x0396", ```

**Comment by Soreepeong** [comment]
I've verified and it's correct; you can download the new version too at [https://github.com/Soreepeong/XivAlexander/releases/tag/v1.14.2.0](here).

**Comment by owopeachy** [comment]
thank you !
