### ISSUE TITLE
Didn't working for me, steam game

### ISSUE THREAD

**Issue by Vermelion** [Soreepeong/XivAlexander#77]
The program doesn't works for me, I can't feel any difference, my game is on steam version, Idk if theres any problem
Everytime I open the program appears an Error
![Screenshot_15](https://user-images.githubusercontent.com/59608866/119602828-68884c00-bdc2-11eb-9ded-269d240d3754.png)
![Screenshot_17](https://user-images.githubusercontent.com/59608866/119605596-72607e00-bdc7-11eb-9195-51165dc0d98b.png)

**Comment by Soreepeong** [comment]
Did you save the JSON file before starting the program? Image before edit indicates that you wrote `\` instead of `\\`, and now it looks correct.

**Comment by Vermelion** [comment]
Yes I did, I saw the error later, I fixed it, but even so it still doesn't work

**Comment by Soreepeong** [comment]
Usually, starting all over is a good option. Make sure that there isn't any control unicode characters.

**Comment by Soreepeong** [comment]
Try downloading the newest release, as it'll attempt to autodetect the version of the program.
