### ISSUE TITLE
Is there a way I can support the devs?

### ISSUE THREAD

**Issue by jinsim95** [Soreepeong/XivAlexander#79]
I'm a Korean user playing in a NA data center, because I started playing the game while my stay in the US during my studies there. 
For over a year and a half, I had been playing at around 140~160 ping, which really wasn't too bad but still made double weaving impossible and certain jobs (e.g. MCH) simply unplayable. 
For weeks I have been considering transferring to a JP data center because of these issues, until I encountered XivAlexander just a few days ago. 
I now see no reason to transfer out of a world that I have made so many friends in and treasure it for its community, thanks to the amazing work of the devs, mainly @Soreepeong.
I wish to further express this gratitude by making a donation to the team, perhaps through a platform like Patreon. 
I'm sure that I cannot be the only one who feels this way and so I urge the devs to consider this suggestion and provide a way the users of this program can support this noble effort.

**Comment by justin767** [comment]
Same here! this team literally saved my life!

**Comment by Soreepeong** [comment]
Thank you for your kind words, but that won't be necessary.
