### ISSUE TITLE
Reduce Packet Delay Settings

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#80]
Hello, what are the optimal settings for the options in the image below?
I've been using them as default so far, but was wondering if there is an option for further improving latency mitigation.
![1](https://user-images.githubusercontent.com/82459386/120246083-2bccc100-c2aa-11eb-8cd5-8484ce333f05.png)

Also, my logging window shows as below, Does this show that the program is running ok and effectively?
![2](https://user-images.githubusercontent.com/82459386/120246490-5703e000-c2ab-11eb-8f22-7fd0457bdb26.JPG)

**Comment by Soreepeong** [comment]
If you see pairs of `ActionRequest` and `ActionEffect` (ignoring `ActionEffect` with single digit `actionId`), then it means that the program works. You can see the reduced latency by checking out `wait=600ms->561ms`, and by comparing it with `latency=42ms` in the same line, the latency decrement is working fine.

Keep those options turned on, and you're good. Uncheck `Use Delay Detection` and `Use Latency Correction` if your VPN software does strange stuff, like reporting that the ping is 0ms. Also, uncheck those, if your ping is pretty high (200+?) to begin with.
