### ISSUE TITLE
International 5.55 Hotfix opcodes

### ISSUE THREAD

**Issue by SimonPilkington** [Soreepeong/XivAlexander#81]
```
"ActorCast": "0x00a9",
"ActorControl": "0x01c8",
"ActorControlSelf": "0x035a",
"AddStatusEffect": "0x01e9",
"RequestUseAction": "0x02a2",
"RequestUseAction2": "0x02f6",
"SkillResultResponse01": "0x0283",
"SkillResultResponse08": "0x025b",
"SkillResultResponse16": "0x015d",
"SkillResultResponse24": "0x0091",
"SkillResultResponse32": "0x0169",
```
Confirmations appreciated.

**Comment by LuthienNengelion** [comment]
Can confirm that these are what I was able to find also (minus AddStatusEffect as it wasn't part of my search)

**Comment by deadproprietary** [comment]
Confirmed working

**Comment by jinsim95** [comment]
Working perfectly! Thanks for the post.

**Comment by owopeachy** [comment]
no issues here, thanks man

**Comment by Evangel0201** [comment]
Feels like any buffs on self still weave poorly.

**Comment by BlueDevice** [comment]
working :D

**Comment by voetre** [comment]
works for me, could you provide and further instructions for finding these additional to what's in the post? I'll be honest and say once I turn on use IPC type finder I have no idea what I'm looking for in the log... Would be great to understand this further so I can search for these on my own if need be. 😊

**Comment by Cresoboi** [comment]
Works great for me

**Comment by Soreepeong** [comment]
Thank you for the contribution!
