### ISSUE TITLE
New opcodes after emergency maint?

### ISSUE THREAD

**Issue by Cresoboi** [Soreepeong/XivAlexander#82]
Wanted to ask if the  NA server opcodes changed after emergency maint because it felt like I was double weaving fine with xivalexander pre maint but now i have trouble, was doing a test on myself with second wind to find an opcode but wasn't sure which ActorCast im supposed to pick 
![image](https://user-images.githubusercontent.com/47761433/120625435-b12dae00-c42f-11eb-87c0-68fc7c0deb0f.png)

Am I just crazy? I average about 130-140ms and was able to double weave certain stuff that I cant double weave now pre maint just fine. Would like to also ask if you could point out how I could identify the opcodes from this SS if its even correct. Tysm for creating this it's a lifesaver and I prolly wouldnt be able to play the game without it.

**Comment by BlueDevice** [comment]
the codes are in a post/issue before yours...

"ActorCast": "0x00a9",
"ActorControl": "0x01c8",
"ActorControlSelf": "0x035a",
"AddStatusEffect": "0x01e9",
"RequestUseAction": "0x02a2",
"RequestUseAction2": "0x02f6",
"SkillResultResponse01": "0x0283",
"SkillResultResponse08": "0x025b",
"SkillResultResponse16": "0x015d",
"SkillResultResponse24": "0x0091",
"SkillResultResponse32": "0x0169",

**Comment by Cresoboi** [comment]
> 
> 
> the codes are in a post/issue before yours...
> 
> "ActorCast": "0x00a9",
> "ActorControl": "0x01c8",
> "ActorControlSelf": "0x035a",
> "AddStatusEffect": "0x01e9",
> "RequestUseAction": "0x02a2",
> "RequestUseAction2": "0x02f6",
> "SkillResultResponse01": "0x0283",
> "SkillResultResponse08": "0x025b",
> "SkillResultResponse16": "0x015d",
> "SkillResultResponse24": "0x0091",
> "SkillResultResponse32": "0x0169",

Yeah thanks managed to found em right after making this post lol

**Comment by Soreepeong** [comment]
This should help. https://github.com/Soreepeong/XivAlexander/issues/28
