### ISSUE TITLE
"Turn both Use Delay Detection and Use Latency Correction off if your ping is above 200ms."

### ISSUE THREAD

**Issue by arennf57** [Soreepeong/XivAlexander#83]
I'd like some clarification about this so I can understand the reason behind it if possible. Thanks in advance!

**Comment by Soreepeong** [comment]
Honestly, I didn't bother to find out why, but it's just something I saw happening when I was fooling around trying out VPN nodes all over the globe. For some reason, it looked like the server will take more processing time when latency is higher.
