### ISSUE TITLE
There is no "SkillResultResponse" of any kind..

### ISSUE THREAD

**Issue by suntude99** [Soreepeong/XivAlexander#84]
I am following the setup guide to get opcodes for the NA version, and does not seem to be working. 

I entered sastasha as a WHm, unsynced. I pulled more than 9 adds, around 12 in total because that was as much as I could do before going over 14.

I used an aoe, first I tried holy, then assize, nope. no SkillResultResponse anywhere in the log 

so I exited, went in as WAR instead, tried the same thing but with mythril tempest, nope. then decimate, also nope..

the ipc logger is not finding anything called SkillResultResponse. Is the tool simply out of date or is it not named that? the closest thing I see is "S2C_AttackResponse"

**Comment by suntude99** [comment]
For the record I have enabled the IPC loggers as instructed.

**Comment by suntude99** [comment]
There is this, which is similarly named. 
2021-06-04 07:45:41.804	AllIpcMessageLogger	source=106159bb current=106159bb subtype=0091 length=71c (S2C: Possibly AttackResponse24)

But its not called the thing your telling me tolook for.

**Comment by suntude99** [comment]
I am doing a grep on the log files it generates, I tried ctrl + f in various notepad-esque programs too.

**Comment by Soreepeong** [comment]
I'll write a detailed wiki article on how to do this. Also I have to update the readme too - I forgot to do that, to be honest.

**Comment by Soreepeong** [comment]
Will this help enough? https://github.com/Soreepeong/XivAlexander/wiki/How-to-find-opcodes
