### ISSUE TITLE
1.14.4.2 Release

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#85]
Do Korean-server players no longer have to change the opcodes by themselves with this release?
The new download looks like the following and everything seems to be working fine when checking the 'show logging window', when using the software without any opcode changes.

Plus, I get a weird result when trying to open XivAlexander.dll file with notepad like below? Is this something that I need to be changing manually? or just leave it as it is.

Thanks
![1](https://user-images.githubusercontent.com/82459386/120937772-4c977b00-c6dd-11eb-90d3-1c5b10bcc635.JPG)
![2](https://user-images.githubusercontent.com/82459386/120937775-4ef9d500-c6dd-11eb-8764-4cb24edd64fe.JPG)

**Comment by InitialDet** [comment]
You're not supposed to open a DLL file with notepad.

The opcodes are located on the JSON files.

**Comment by Soreepeong** [comment]
The program will create a new file named `game.KR.<version>.json` when the game updates. You'll have to edit the file after.

**Comment by justin767** [comment]
D

> You're not supposed to open a DLL file with notepad.
> 
> The opcodes are located on the JSON files.

So only change the opcodes.json files only when therr is an update right
