### ISSUE TITLE
1.4442 version has this problem

### ISSUE THREAD

**Issue by lovedzzcdf** [Soreepeong/XivAlexander#86]
![Capture](https://user-images.githubusercontent.com/85505740/121041831-660af680-c7b3-11eb-933e-ee3845a8b942.PNG)

1.4430 version still can use..

**Comment by Soreepeong** [comment]
Are you sure your antivirus isn't deleting a file or blocking the program?

**Comment by lovedzzcdf** [comment]
Yes I'm sure because i never had same problem before,even now i can open old version but code not match anymore

**Comment by Soreepeong** [comment]
Can you try this? This will show better error messages.

[XivAlexander_1_14_4_2_TESTING.zip](https://github.com/Soreepeong/XivAlexander/files/6610727/XivAlexander_1_14_4_2_TESTING.zip)

**Comment by lovedzzcdf** [comment]
Yes ffxivgame.ver is exist in my game path as F:\WeGameApps\WeGameApps\ffxiv(2000340)\game\ffxivgame.ver
please see this error from the TESTING.zip
![111](https://user-images.githubusercontent.com/85505740/121067570-8050ce80-c7cb-11eb-9f09-5e4a12a0dcee.PNG)

**Comment by Soreepeong** [comment]
Please try again with this one. I've forced all error messages to show in English, just in case I've messed up with encodings.

[XivAlexander_1_14_4_2_TESTING_2.zip](https://github.com/Soreepeong/XivAlexander/files/6613437/XivAlexander_1_14_4_2_TESTING_2.zip)

**Comment by lovedzzcdf** [comment]
Hi please check this error,thanks
![Capture](https://user-images.githubusercontent.com/85505740/121160892-c601ab80-c84c-11eb-8fd8-ef3c7cb027c0.PNG)

**Comment by Soreepeong** [comment]
Can you take a screencap of root game installation folder? The loadet looks for any file named `ffxiv<anything>.exe` in "boot" directory if directory exists, and othetwise in game installation path. Let me know in what folder does "ffxivboot.exe" exists, too.

**Comment by lovedzzcdf** [comment]
![Capture2](https://user-images.githubusercontent.com/85505740/121170948-2c3efc00-c856-11eb-9a11-c53557555550.PNG)
![Capture](https://user-images.githubusercontent.com/85505740/121170960-2e08bf80-c856-11eb-89b7-f082cc7b4303.PNG)
Can't find fxivboot.exe

**Comment by lovedzzcdf** [comment]
Yes I downloaded it from Wegame platform,it’s different to the official client program,let me try to download this one and get back to you later,thank you!

**Comment by MeisseN1337** [comment]
> 
> 
> Can you also take a screencap of whatever's on the parent directory? The file did exist in my installation from https://ff.web.sdo.com/web8/index.html#/home , but I guess there exists other ways to install the game?

![image](https://user-images.githubusercontent.com/84473230/121192026-6e6f3a00-c864-11eb-89b3-bae6cf2a0456.png)
![image](https://user-images.githubusercontent.com/84473230/121192083-79c26580-c864-11eb-9e5f-ac2ce5710ff9.png)
yes there are 2 ways of installing the game, one is from the link you provided and another one from the Wegame platform (much like SE launcher / steam for international servers) the core game files are the same (i'm running both clients with a hyperlinked folder to the actual game files) but the Wegame package does not include Ffxivboot.exe as this is the launcher for the Sdo client

**Comment by Soreepeong** [comment]
@MeisseN1337 @lovedzzcdf Can you check whether `sdo\sdologinentry.dll` exists for both versions and is signed by `盛趣信息技术（上海）有限公司`?

![image](https://user-images.githubusercontent.com/3614868/121202228-16f6bb80-c8b0-11eb-9d67-6f29d7a705d5.png)

**Comment by lovedzzcdf** [comment]
![Capture](https://user-images.githubusercontent.com/85505740/121206238-98325c00-c878-11eb-8282-4b2b10da1d04.PNG)
There is

**Comment by Soreepeong** [comment]
[XivAlexander_1_14_4_2_TESTING_4.zip](https://github.com/Soreepeong/XivAlexander/files/6617551/XivAlexander_1_14_4_2_TESTING_4.zip)

This one should work. It checks the following files:
* `<game path>/boot/ffxiv*.exe` for International and Korean clients
* `<game path>/sdo/sdologinentry.dll` for Chinese clients.

Let me know whether this works!

**Comment by lovedzzcdf** [comment]
Great it works 100% now thanks man,really appreciate it!
