### ISSUE TITLE
Question with opcodes

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#87]
We dont have to edit any opcodes currently with this version right?, since its default are set for 5.55 hotfix? Only change the opcodes on .json file when there is a new path or update?

**Comment by justin767** [comment]
> Yes. Is something not working?

No no i was just asking because the new version had a seperate kr and jp server json files.

**Comment by Soreepeong** [comment]
People were being confused about which section of previous configuration file, and there were *issues* with JSON string escapes, so I've made them into separate files.

**Comment by justin767** [comment]
> People were being confused about which section of previous configuration file, and there were _issues_ with JSON string escapes, so I've made them into separate files.

Thanks alot. So only change the opcodes in my server's json file when there is an ingame patch or update right? If so, are you no longer providing new releases in accordance with new patches? If we manually have to change the opcodes? Thank you

**Comment by justin767** [comment]
> I will update the files when patches come out, but it might be not asap, and finding opcodes is for people who don't want to wait for me. This way, people can share opcode definition file easier - they can just upload, and for users, they can download and just paste it into the addon directory.

Thank you !!
