### ISSUE TITLE
Anyone knows the opcodes for chinese client 5.45?

### ISSUE THREAD

**Issue by lilitham** [Soreepeong/XivAlexander#88]
chinese version is patch 5.45 now.Anyone knows the opcodes for it?

**Comment by lovedzzcdf** [comment]
{
	"C2S_ActionRequest": "0x034c",
	"C2S_ActionRequestGroundTargeted": "0x00eb",
	"S2C_ActionEffect01": "0x0240",
	"S2C_ActionEffect08": "0x0376",
	"S2C_ActionEffect16": "0x035b",
	"S2C_ActionEffect24": "0x020b",
	"S2C_ActionEffect32": "0x0353",
	"S2C_ActorCast": "0x0392",
	"S2C_ActorControl": "0x03c3",
	"S2C_ActorControlSelf": "0x0077",
	"S2C_AddStatusEffect": "0x0212"
}


I just got it

**Comment by MnFeN** [comment]
> {
> "C2S_ActionRequest": "0x034c",
> "C2S_ActionRequestGroundTargeted": "0x00eb",
> "S2C_ActionEffect01": "0x0240",
> "S2C_ActionEffect08": "0x0376",
> "S2C_ActionEffect16": "0x035b",
> "S2C_ActionEffect24": "0x020b",
> "S2C_ActionEffect32": "0x0353",
> "S2C_ActorCast": "0x0392",
> "S2C_ActorControl": "0x03c3",
> "S2C_ActorControlSelf": "0x0077",
> "S2C_AddStatusEffect": "0x0212"
> }
> 
> I just got it

Hi, may I ask what's the difference of "C2S_ActionRequest" and "RequestUseAction"? The config file of patch 5.41 I downloaded before only contains the later one.

**Comment by lovedzzcdf** [comment]
Upgrade to latest version you will know,leave old version

**Comment by moonlitglare** [comment]
Hasn't this been resolved?

**Comment by MnFeN** [comment]
> Hasn't this been resolved?

https://github.com/Soreepeong/XivAlexander/issues/91 Try this
