### ISSUE TITLE
Why is my animation lock 600ms?

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#90]
![1](https://user-images.githubusercontent.com/82459386/121557419-bc11b100-c9e2-11eb-9f49-d52a4a412ba2.JPG)
I thought it should be 500ms, but my animation lock seems to be set as 600ms instead.

Also, by looking at my logging status, do you think I should turn off delay detection and latency correction?

Thankyou

**Comment by Soreepeong** [comment]
600ms is default for most of actions, and just from reading the logs, since, in `wait=[A]ms->[B]ms rtt=[C]ms`, B+C-A is pretty low, which is the supposed server processing time.

**Comment by jjolano** [comment]
@Soreepeong Looks like latency correction kicked in here, judging by the very large discrepancy between rtt and actual latency value. This is usually seen when the connection is saturated or congestion (like downloading in the background). See latency parenthesis value in the logs. This is calculated based on the fastest rtt with fluctuation in consideration (and is also why it helps fake ping VPN users without giving advantage).

Without latency correction in this case, all the delay values will be 150ms.

**Comment by justin767** [comment]
> 600ms is default for most of actions, and just from reading the logs, since, in `wait=[A]ms->[B]ms rtt=[C]ms`, B+C-A is pretty low, which is the supposed server processing time.

Should I turn off delay detection and latency correction for better connection?

**Comment by justin767** [comment]
> @Soreepeong Looks like latency correction kicked in here, judging by the very large discrepancy between rtt and actual latency value. This is usually seen when the connection is saturated or congestion (like downloading in the background). See latency parenthesis value in the logs. This is calculated based on the fastest rtt with fluctuation in consideration (and is also why it helps fake ping VPN users without giving advantage).
> 
> Without latency correction in this case, all the delay values will be 150ms.

What should I do to have better connection? Shouls I turn off delay detection and latency correction? Thank you

**Comment by justin767** [comment]
> @Soreepeong Looks like latency correction kicked in here, judging by the very large discrepancy between rtt and actual latency value. This is usually seen when the connection is saturated or congestion (like downloading in the background). See latency parenthesis value in the logs. This is calculated based on the fastest rtt with fluctuation in consideration (and is also why it helps fake ping VPN users without giving advantage).
> 
> Without latency correction in this case, all the delay values will be 150ms.

Dd

**Comment by Soreepeong** [comment]
Just try out different configuration? There's not much possibilities of different set of options - "Use Delay Detection" and "Use Latency Correction" are the only two options you have that directly affects the situation. Find the configuration that you think the best. Other than this, the only other thing you can do is trying out other VPNs and/or ISPs.

**Comment by justin767** [comment]
> Just try out different configuration? There's not much possibilities of different set of options - "Use Delay Detection" and "Use Latency Correction" are the only two options you have that directly affects the situation. Find the configuration that you think the best. Other than this, the only other thing you can do is trying out other VPNs and/or ISPs.

Yeah, I just wanna ask by looking at my current ping in the logging window, whether you think I shouls turn those off or on. Also, how do I check which configuration is better apart from how I feel?
