### ISSUE TITLE
china client can't find opcode

### ISSUE THREAD

**Issue by Cherryhy** [Soreepeong/XivAlexander#91]
China client is 5.45 now
another issues already have new opcode for china client but doesn't work for me so i try to find opcode by myself
I follow every step on wiki but IPC TYPE FINDER was no response at all
I also play jp client, when i use jp client to try to use IPC TYPE FINDER is work well.
Can anyone help me plz...

**Comment by Soreepeong** [comment]
Try changing "GameServerIpRange" in Configuration (runtime) to "0.0.0.0/0" for now.

I'll move this config to region-specific config later.

**Comment by Cherryhy** [comment]
I try to change to "0.0.0.0/0" but still not working. The log have nothing show up...

**Comment by Soreepeong** [comment]
Not even `Mark ignored`?

![image](https://user-images.githubusercontent.com/3614868/121642081-01111280-cacb-11eb-90eb-03fecdaebc78.png)

**Comment by Cherryhy** [comment]
![image](https://user-images.githubusercontent.com/59221769/121644315-3707c400-cad6-11eb-85ff-c58d3b1b2ea5.png)
ahh Yes, there are

**Comment by Soreepeong** [comment]
Ah, I found a bug with that config. Try `0.0.0.0/1, 128.0.0.0/1` instead for now.

**Comment by Cherryhy** [comment]
IT's all work well now very nice. so its not opcode problem. when i change to 0.0.0.0/1, 128.0.0.0/1 its all work well
