### ISSUE TITLE
DLL issue on windows 7 

### ISSUE THREAD

**Issue by jyuza** [Soreepeong/XivAlexander#93]
Hello there, i just tried to start the loader and im getting this error (on windows 7) :
The procedure entry point GetSystemTimePreciseAsFileTime could not be located in the dynamic link library KERNEL32.dll

I saw you did some changes in the code when you tried to help someone else having the same kind of issues.

**Comment by Soreepeong** [comment]
[XivAlexander_1_14_5_0_TESTING_1.zip](https://github.com/Soreepeong/XivAlexander/files/6646109/XivAlexander_1_14_5_0_TESTING_1.zip)

Can you try this one?

**Comment by jyuza** [comment]
> [XivAlexander_1_14_5_0_TESTING_1.zip](https://github.com/Soreepeong/XivAlexander/files/6646109/XivAlexander_1_14_5_0_TESTING_1.zip)
> 
> Can you try this one?

I just tried it and I got another dll error, since its in french it may be an incorrect translation but basically : Impossible to start the program because api-ms-win-core-path-l1-1-0.dll is not found on your computer. Try de reinstall the program to correct the issue.

**Comment by Soreepeong** [comment]
[XivAlexander_1_14_5_0_TESTING_2.zip](https://github.com/Soreepeong/XivAlexander/files/6646412/XivAlexander_1_14_5_0_TESTING_2.zip)

That file won't be needed anymore, but we'll have to see if I have to remove another dependency file. Try this one.

**Comment by jyuza** [comment]
> [XivAlexander_1_14_5_0_TESTING_2.zip](https://github.com/Soreepeong/XivAlexander/files/6646412/XivAlexander_1_14_5_0_TESTING_2.zip)
> 
> That file won't be needed anymore, but we'll have to see if I have to remove another dependency file. Try this one.

Another error for this one but not a dll one : 
ffxiv_dx11.exe not found. Run the game first, and then try again.

I ran it in admin mode, my game is running and the exception is set in my antivirus.

**Comment by Soreepeong** [comment]
Just to be sure: are you using DirectX 11 version?
![image](https://user-images.githubusercontent.com/3614868/121859321-85b19a00-cd32-11eb-857c-12aa7d3537e9.png)

**Comment by jyuza** [comment]
> Just to be sure: are you using DirectX 11 version?
> ![image](https://user-images.githubusercontent.com/3614868/121859321-85b19a00-cd32-11eb-857c-12aa7d3537e9.png)

Oh...thanks for the reminder (i disabled it few weeks ago), its working now ! Thanks a lot for the fast reply ! 

P.S : Really nice job with this addon, im playing another game right now thanks to you guys !
