### ISSUE TITLE
The download link for the new version doesn't work

### ISSUE THREAD

**Issue by justin767** [Soreepeong/XivAlexander#95]
Clicking the .zip download link opens up a page saying 'Not found'.
![Screenshot_20210617-164323_Samsung Internet](https://user-images.githubusercontent.com/82459386/122469702-416d0680-cf8b-11eb-91b4-cc13136aed8d.jpg)

**Comment by Heinzen** [comment]
The URL on top is redirecting to an incorrect tag name (XivAlexander_1_14_1_0.zip). Use the ZIP download link on the bottom instead as that one is working.

**Comment by justin767** [comment]
> The URL on top is redirecting to an incorrect tag name (XivAlexander_1_14_1_0.zip). Use the ZIP download link on the bottom instead as that one is working.

Thank you!!

**Comment by Soreepeong** [comment]
Yeah, that's fixed now. Thanks for letting me know!
