### ISSUE TITLE
Patch 5.57 Opcodes

### ISSUE THREAD

**Issue by BahamutBlast** [Soreepeong/XivAlexander#96]
Patch 5.57 just rolled out today so the old opcodes don't work anymore.

**Comment by gnomerock** [comment]
please confirm
```
{
	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24, 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16",
	"Server_PortRange": "1025-65535",
	"C2S_ActionRequest": "0x03a0",
	"C2S_ActionRequestGroundTargeted": "0x036b",
	"S2C_ActionEffect01": "0x008f",
	"S2C_ActionEffect08": "0x0247",
	"S2C_ActionEffect16": "0x02c1",
	"S2C_ActionEffect24": "0x0295",
	"S2C_ActionEffect32": "0x034c",
	"S2C_ActorCast": "0x02cc",
	"S2C_ActorControl": "0x0164",
	"S2C_ActorControlSelf": "0x0356",
	"S2C_AddStatusEffect": "0x03cf"
}
```

**Comment by VXLSS** [comment]
> please confirm
> 
> ```
> {
> 	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24, 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16",
> 	"Server_PortRange": "1025-65535",
> 	"C2S_ActionRequest": "0x03a0",
> 	"C2S_ActionRequestGroundTargeted": "0x036b",
> 	"S2C_ActionEffect01": "0x008f",
> 	"S2C_ActionEffect08": "0x0247",
> 	"S2C_ActionEffect16": "0x02c1",
> 	"S2C_ActionEffect24": "0x0295",
> 	"S2C_ActionEffect32": "0x034c",
> 	"S2C_ActorCast": "0x02cc",
> 	"S2C_ActorControl": "0x0164",
> 	"S2C_ActorControlSelf": "0x0356",
> 	"S2C_AddStatusEffect": "0x03cf"
> }
> ```


How do you find them ;-; The log window thing is very confusing and overwhelming

**Comment by gnomerock** [comment]
sry repost 
please confirm again
```
{
	"C2S_ActionRequest": "0x03a0",
	"C2S_ActionRequestGroundTargeted": "0x036b",
	"S2C_ActionEffect01": "0x008f",
	"S2C_ActionEffect08": "0x0247",
	"S2C_ActionEffect16": "0x02c1",
	"S2C_ActionEffect24": "0x0295",
	"S2C_ActionEffect32": "0x034c",
	"S2C_ActorCast": "0x02cc",
	"S2C_ActorControl": "0x0164",
	"S2C_ActorControlSelf": "0x0356",
	"S2C_AddStatusEffect": "0x03cf",
	"Server_IpRange": "0.0.0.0/0",
	"Server_PortRange": "1-65535"
}
```

**Comment by gnomerock** [comment]
> > please confirm
> > ```
> > {
> > 	"Server_IpRange": "124.150.157.0/24, 195.82.50.0/24, 204.2.229.0/24, 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16",
> > 	"Server_PortRange": "1025-65535",
> > 	"C2S_ActionRequest": "0x03a0",
> > 	"C2S_ActionRequestGroundTargeted": "0x036b",
> > 	"S2C_ActionEffect01": "0x008f",
> > 	"S2C_ActionEffect08": "0x0247",
> > 	"S2C_ActionEffect16": "0x02c1",
> > 	"S2C_ActionEffect24": "0x0295",
> > 	"S2C_ActionEffect32": "0x034c",
> > 	"S2C_ActorCast": "0x02cc",
> > 	"S2C_ActorControl": "0x0164",
> > 	"S2C_ActorControlSelf": "0x0356",
> > 	"S2C_AddStatusEffect": "0x03cf"
> > }
> > ```
> 
> How do you find them ;-; The log window thing is very confusing and overwhelming

I clear log window everytime after got 1 opcode

**Comment by MrJuanHelao** [comment]
> 
> 
> sry repost
> please confirm again
> 
> ```
> {
> 	"C2S_ActionRequest": "0x03a0",
> 	"C2S_ActionRequestGroundTargeted": "0x036b",
> 	"S2C_ActionEffect01": "0x008f",
> 	"S2C_ActionEffect08": "0x0247",
> 	"S2C_ActionEffect16": "0x02c1",
> 	"S2C_ActionEffect24": "0x0295",
> 	"S2C_ActionEffect32": "0x034c",
> 	"S2C_ActorCast": "0x02cc",
> 	"S2C_ActorControl": "0x0164",
> 	"S2C_ActorControlSelf": "0x0356",
> 	"S2C_AddStatusEffect": "0x03cf",
> 	"Server_IpRange": "0.0.0.0/0",
> 	"Server_PortRange": "1-65535"
> }
> ```

Those are not working properly for me :(

**Comment by WeegeeVenom** [comment]
Yea, I just wanted to chime in and confirm that I got the same OPCodes. Playing on NA, and am using the latest version of XIVAlexander. (1.14.5.1)

> 
> 
> > sry repost
> > please confirm again
> > ```
> > {
> > 	"C2S_ActionRequest": "0x03a0",
> > 	"C2S_ActionRequestGroundTargeted": "0x036b",
> > 	"S2C_ActionEffect01": "0x008f",
> > 	"S2C_ActionEffect08": "0x0247",
> > 	"S2C_ActionEffect16": "0x02c1",
> > 	"S2C_ActionEffect24": "0x0295",
> > 	"S2C_ActionEffect32": "0x034c",
> > 	"S2C_ActorCast": "0x02cc",
> > 	"S2C_ActorControl": "0x0164",
> > 	"S2C_ActorControlSelf": "0x0356",
> > 	"S2C_AddStatusEffect": "0x03cf",
> > 	"Server_IpRange": "0.0.0.0/0",
> > 	"Server_PortRange": "1-65535"
> > }
> > ```
> 
> Those are not working properly for me :(

I don't think they worked for me when I was using the old version of XIVAlexander but they work now? Otherwise, check if you forgot to enable high latency mitigation maybe?

**Comment by MrJuanHelao** [comment]
Didn't notice the executable was creating another JSON file, so I was configuring the wrong one. It works fine now.
Thank you! :) 👍

**Comment by Soreepeong** [comment]
[game.JP.2021.06.16.0000.0000.json.txt](https://github.com/Soreepeong/XivAlexander/files/6696105/game.JP.2021.06.16.0000.0000.json.txt)

Remove `.txt` from extension and place it to the directory, and it should work for now.
