### ISSUE TITLE
Multiple sub 600 ms weaves

### ISSUE THREAD

**Issue by Mickeywasneverhere** [Soreepeong/XivAlexander#97]
This issue has occurred previously, but was basically fixed when auto-attack animation lock was taken into account. However, it popped up again with the introduction of delay detection in the newer versions of xivalexander. I am going to provide few examples regarding this.

Example 1:
![sus_-_Imgur](https://user-images.githubusercontent.com/86467826/123399813-59edaa00-d5a5-11eb-8be9-823a2bea194f.png)
Version: 1.14.6.1
Average ping: 99 ms
DC: Primal
VPN: Mudfish

Example 2:
![jjqxp2R](https://user-images.githubusercontent.com/86467826/123400192-c8326c80-d5a5-11eb-9a6c-3c5786db822f.png)
Version: 1.14.5.1
Average ping: 26 ms
DC: Chaos
VPN: None

Example 3:
![123401960-8efafc00-d5a7-11eb-8913-f5f3938d64d8](https://user-images.githubusercontent.com/86467826/123406443-36c5f900-d5ab-11eb-9a7b-ca8e2cb06b37.png)
Version: N/A
Average ping: N/A
DC: Crystal 
VPN: N/A

Example 4:
![MeTd4Pd](https://user-images.githubusercontent.com/86467826/123403651-1bf28500-d5a9-11eb-88ff-f2e309513707.png)
Version: 1.14.6.1
Average ping: 140 ms
DC: Crystal
VPN: Exitlag

Example 5:
![hNhp0Ld](https://user-images.githubusercontent.com/86467826/123405259-ed28de80-d5a9-11eb-87ed-b008259dc55d.png)
Version: 1.14.6.1
Average ping: 55 ms
DC: Chaos
VPN: Mudfish

**Comment by jjolano** [comment]
Can you attach a log from the program after doing some weaves? Check "Show Logging Window"

**Comment by Mickeywasneverhere** [comment]
Alright I will try to do one after raid.

**Comment by Mickeywasneverhere** [comment]
I apologize for the late reply but here is the log in a .txt format. 
[xivalex.txt](https://github.com/Soreepeong/XivAlexander/files/6719101/xivalex.txt)
This version is 1.146.1 with delay detection/latency correct/reduced packet delay on. I am also using mudfish but without the 0 ping mode.

**Comment by Soreepeong** [comment]
```
2021-06-26 00:31:59.362	AnimationLockLatencyHandler	156c: C2S_ActionRequest(03a0): actionId=1d37 sequence=0062
2021-06-26 00:31:59.453	AnimationLockLatencyHandler	156c: S2C_ActionEffect(008f): actionId=1d37 sourceSequence=0062 rtt=91ms latency=79ms latencyEstimate=88ms delayAdjusted=3ms wait=600ms->512ms
```
* Request at 31:59.362
  * Expected next minimum 31:59.962
* Response at 31:59.453
  * Adjusted to 0.512
  * 31:59.453 + 0.512 = 31:59.965

```
2021-06-26 00:31:59.959	AnimationLockLatencyHandler	156c: C2S_ActionRequest(03a0): actionId=1d4a sequence=0063
2021-06-26 00:32:00.077	AnimationLockLatencyHandler	156c: S2C_ActionEffect(008f): actionId=1d4a sourceSequence=0063 rtt=118ms latency=81ms latencyEstimate=97ms delayAdjusted=21ms wait=600ms->509ms
```
* Request at 31:59.959
  * Should have been later than 31:59.965
  * Expected next minimum 32:00.559 + 0.006 = 32:00.565
* Response at 32:00.077
  * Adjusted to 0.509
  * 32:00.077 + 0.509 = 32:00.586

```
2021-06-26 00:32:00.580	AnimationLockLatencyHandler	156c: C2S_ActionRequest(03a0): actionId=1d47 sequence=0064
2021-06-26 00:32:00.698	AnimationLockLatencyHandler	156c: S2C_ActionEffect(008f): actionId=1d47 sourceSequence=0064 rtt=118ms latency=79ms latencyEstimate=97ms delayAdjusted=21ms wait=600ms->508ms
```
* Request at 32:00.580
  * Should have been later than 32:00.586

The game's timestamp processing must be using different time source - either Timestamp given in traffic, GetTickCount, or timeGetTime. Will have to test if it's the case. 

Also, even when some actions will happen before supposed timestamp, this program will compensate for that, by counting in how much did the game let the user use action early, so the average of how early did the user get to use action compared to supposed time should not exceed zero.

**Comment by Mickeywasneverhere** [comment]
Does that indicate some sort of back end changes in the game?

**Comment by Soreepeong** [comment]
Nah, the game code dealing with this is unlikely to have been changed. I just have to figure out what causes the game to let the user use action before the specified delay.

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivAlexander/releases

Can you try this one? The latency reported from the socket ioctl is higher than ICMP ping, so xivalex will now refer to ping result too. Also, it will penalize the user by making next action delayed if it detects that the action has been used too early.

**Comment by Mickeywasneverhere** [comment]
Will definitely do and report back.

**Comment by Soreepeong** [comment]
That sounds about right. If you stand still while using actions, can you double weave comfortably?

**Comment by Mickeywasneverhere** [comment]
Yes I can double weave comfortably when I stand still.

**Comment by Soreepeong** [comment]
Refer to this: #23 
When you're moving around, the delay between action increases. You have to be standing still to double weave without clipping; if you do move, then probably won't happen.

**Comment by Mickeywasneverhere** [comment]
After trying the version for a bit it seems that some double weaves clip even when standing still, although this happens from time to time and I really don't understand why. I cannot replicate this consistently.

**Comment by Soreepeong** [comment]
That was the original reason why I suggested people to try disabling `Use Delay Detection` if it does that - to be honest, I don't understand why either. It just works fine under 100ms ping, but at 150ms it becomes flakey.
