### ISSUE TITLE
Auto Startup With XIVLauncher

### ISSUE THREAD

**Issue by SchwartzLizer** [Soreepeong/XivAlexander#99]
it can be possible to launch XivAlenxander with XIVLauncher in 1 click?

**Comment by Soreepeong** [comment]
Maybe try this? 
![image](https://user-images.githubusercontent.com/3614868/124171748-ee936300-dae3-11eb-866b-fe5760f637bd.png)

**Comment by Bananaman** [comment]
Thanks a lot. I pointed it to the 64-bit launcher and put it after ACT. It works.

![image](https://user-images.githubusercontent.com/38923130/134777054-d6a65a0a-e075-4c16-8603-e8f2cfce300e.png)

**Comment by Soreepeong** [comment]
Note that you can install XivAlexander now, which will let you don't even have to set up that step.
